/*
 * SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0
 * Copyright 2025 Telechips Inc.
 * Contact: shkim@telechips.com
 */

#ifndef TCC_JPU_C6__H
#define TCC_JPU_C6__H

#include "TCCxxxx_VPU_CODEC_COMMON.h"

#define JPU_API_VERSION "1.3"

/**
 @brief Specific operation codes
*/
#define JPU_GET_VERSION			0x1000 /**< Command to get the version of the JPU_C6. */
#define JPU_CTRL_LOG_STATUS 	0x1002 /**< Command to control the log status using the jpu_ctrl_log_status_t structure. This command can be issued at any time, even before initialization. */

#define MAX_NUM_INSTANCE		4

#define	YUV_FORMAT_420			0
#define	YUV_FORMAT_422			1
#define	YUV_FORMAT_224			2
#define	YUV_FORMAT_444			3
#define	YUV_FORMAT_400			4

// Decoding Status
#define JPU_DEC_SUCCESS					1
#define JPU_DEC_INVALID_INSTANCE		2
#define JPU_DEC_SUCCESS_PARTIAL_MODE	3

// Encoder Op Code
#define JPU_ENC_INIT				VPU_ENC_INIT				//!< init
#define JPU_ENC_REG_FRAME_BUFFER	VPU_ENC_REG_FRAME_BUFFER	//!< register frame buffer
#define JPU_ENC_ENCODE				VPU_ENC_ENCODE				//!< encode
#define JPU_ENC_CLOSE				VPU_ENC_CLOSE				//!< close

// Decoder Op Code
#define JPU_DEC_INIT				VPU_DEC_INIT				//!< init
#define JPU_DEC_SEQ_HEADER			VPU_DEC_SEQ_HEADER			//!< decode sequence header
#define JPU_DEC_REG_FRAME_BUFFER	VPU_DEC_REG_FRAME_BUFFER	//!< register frame buffer
#define JPU_DEC_REG_FRAME_BUFFER3	0x04						//!< register frame buffer
#define JPU_DEC_DECODE				VPU_DEC_DECODE				//!< decode
#define JPU_DEC_CLOSE				VPU_DEC_CLOSE				//!< close
#define JPU_DEC_GET_ROI_INFO		0x21						//!< get ROI info
#define JPU_CODEC_GET_VERSION		VPU_CODEC_GET_VERSION		//!< get JPU version

#define RETCODE_ERR_MIN_RESOLUTION			101
#define RETCODE_ERR_MAX_RESOLUTION			102

#define JPG_RET_SUCCESS						 0
#define JPG_RET_FAILURE						 1
#define JPG_RET_BIT_EMPTY					 2
#define JPG_RET_EOS							 3
#define JPG_RET_INVALID_HANDLE				 4
#define JPG_RET_INVALID_PARAM				 5
#define JPG_RET_INVALID_COMMAND				 6
#define JPG_RET_ROTATOR_OUTPUT_NOT_SET		 7
#define JPG_RET_ROTATOR_STRIDE_NOT_SET		 8
#define JPG_RET_FRAME_NOT_COMPLETE			 9
#define JPG_RET_INVALID_FRAME_BUFFER		10
#define JPG_RET_INSUFFICIENT_FRAME_BUFFERS	11
#define JPG_RET_INVALID_STRIDE				12
#define JPG_RET_WRONG_CALL_SEQUENCE			13
#define JPG_RET_CALLED_BEFORE				14
#define JPG_RET_NOT_INITIALIZED				15
#define JPG_RET_CODEC_EXIT					16
#define JPG_RET_SPEC_OUT					17
#define JPG_RET_INSUFFICIENT_BITSTREAM_BUF	18
#define	JPG_RET_CODEC_FINISH				19

#ifndef INC_DEVICE_TREE_PMAP
/**
 @brief Structure for JPU_GET_VERSION command
 */
typedef struct jpu_get_version_t {
	char *pszHeaderApiVersion; /**< [inp] Set the value to JPU_GET_VERSION to check API compatibility, or NULL to skip */
	char szGetVersion[32];	   /**< [out] Returns TCC_JPU_DEC or TCC_JPU_ENC version */
	char szGetBuildDate[32];   /**< [out] Returns TCC_JPU_DEC or TCC_JPU_ENC build date */
} jpu_get_version_t;

/**
 * @struct jpu_ctrl_log_status_t
 * @brief Structure for controlling logging status within the VPU 4K D2 decoder library.
 *
 * This structure is used to set the logging levels and conditions for the VPU 4K D2 decoder.
 * It allows fine-grained control over the types of logs that are printed, as well as specific
 * conditions under which logs should be generated.
 */
typedef struct jpu_ctrl_log_status_t {
	/**
	 * @brief A pointer to the callback function for logging prints to be used internally within the library.
	 *
	 * This callback function is used to print log messages generated by the library. The function
	 * should follow the printf-style format.
	 *
	 * @param format The format string for the log message.
	 * @param ... Additional arguments for the format string.
	 */
	void (*pfLogPrintCb)(const char *, ...);

	/**
	 * @brief Structure for specifying the log levels.
	 *
	 * Each member of this structure controls whether a specific type of log message is enabled or disabled.
	 * A value of 1 enables the log type, while a value of 0 disables it.
	 */
	struct {
		int bVerbose; /**< Enable verbose logging (on=1, off=0) */
		int bDebug;   /**< Enable debug logging (on=1, off=0) */
		int bInfo;    /**< Enable info logging (on=1, off=0) */
		int bWarn;    /**< Enable warning logging (on=1, off=0) */
		int bError;   /**< Enable error logging (on=1, off=0) */
		int bAssert;  /**< Enable assert logging (on=1, off=0) */
		int bFunc;    /**< Enable function begin/end logging (on=1, off=0) */
		int bTrace;   /**< Enable trace logging (on=1, off=0) */
	} stLogLevel;

	/**
	 * @brief Structure for specifying log conditions.
	 *
	 * Each member of this structure represents a condition that can be checked before generating a log message.
	 * These conditions can be used to control logging more precisely, based on specific states or events in the
	 * decoder.
	 */
	struct {
		int bDecodeSuccess; /**< Log when decoding is successful (on=1, off=0) */
		int bEncodeSuccess; /**< Log when encoding is successful (on=1, off=0) */
	} stLogCondition;
} jpu_ctrl_log_status_t;

//-----------------------------------------------------
// data structure to get information necessary to
// start decoding from the decoder (this is an output parameter)
//-----------------------------------------------------
typedef struct jpu_dec_initial_info_t {
	int m_iPicWidth;				//!< {(PicX+15)/16} * 16  (this width  will be used while allocating decoder frame buffers. picWidth  is a multiple of 16)
	int m_iPicHeight;				//!< {(PicY+15)/16} * 16  (this height will be used while allocating decoder frame buffers. picHeight is a multiple of 16)
	int m_iSourceFormat;			//!< the minimum number of frame buffers that are required for decoding. application must allocate at least this number of frame buffers.
	int m_iErrorReason;
	int m_iMinFrameBufferCount;
	int m_iMinFrameBufferSize[4];	//!< minimum frame buffer size
									//!< 0 ( Original Size )
									//!< 1 ( 1/2 Scaling Down )
									//!< 2 ( 1/4 Scaling Down )
									//!< 3 ( 1/8 Scaling Down )
	int m_Reserved[23];
} jpu_dec_initial_info_t;

//! data structure for initializing Video unit
typedef struct jpu_dec_init_t {
	codec_addr_t m_RegBaseVirtualAddr;	//!< virtual address BIT_BASE
	codec_addr_t m_BitstreamBufAddr[2];	//!< bitstream buf address : multiple of 4
	int m_iBitstreamBufSize;			//!< bitstream buf size	   : multiple of 1024

	int m_iCbCrInterleaveMode;

	unsigned int m_uiDecOptFlags;

	//! Callback Func
	void* (*m_Memcpy) (void*, const void*, unsigned int, unsigned int);	//!< memcpy
	void  (*m_Memset) (void*, int, unsigned int, unsigned int);			//!< memset
	int   (*m_Interrupt) (void);								//!< hw interrupt (return value is always 0)
	void* (*m_Ioremap) (unsigned int, unsigned int);
	void  (*m_Iounmap) (void *);
	unsigned int (*m_reg_read)(void *, unsigned int);
	void (*m_reg_write)(void *, unsigned int, unsigned int);

	int m_Reserved[19];
} jpu_dec_init_t;

// ===========================================================================
// [32 bit user-space bearer for |jpu_dec_init_t|]
typedef struct jpu_dec_init_64bit_t {
    codec_addr_t m_RegBaseVirtualAddr;
    codec_addr_t m_BitstreamBufAddr[2];
    int m_iBitstreamBufSize;

    int m_iCbCrInterleaveMode;

    unsigned int m_uiDecOptFlags;

    //! Callback Func
    unsigned long long cb_dummy_memcpy;
    unsigned long long cb_dummy_memset;
    unsigned long long cb_dummy_interrupt;
    unsigned long long cb_dummy_ioremap;
    unsigned long long cb_dummy_iounmap;
    unsigned long long cb_dummy_reg_read;
    unsigned long long cb_dummy_reg_write;

    int m_Reserved[19];
} jpu_dec_init_64bit_t;
// ===========================================================================

typedef struct jpu_dec_input_t {
	codec_addr_t m_BitstreamDataAddr[2];	//!< bitstream data address
	int m_iBitstreamDataSize;				//!< bitstream data size
	int m_Reserved[29];
} jpu_dec_input_t;

typedef struct jpu_dec_buffer_t {
	codec_addr_t m_FrameBufferStartAddr[2];	//!< physical[0] and virtual[1] address of a frame buffer of the decoder.
	int m_iFrameBufferCount;				//!< allocated frame buffer count
	int m_iJPGScaleRatio;					//!< JPEG Scaling Ratio
											//!< 0 ( Original Size )
											//!< 1 ( 1/2 Scaling Down )
											//!< 2 ( 1/4 Scaling Down )
											//!< 3 ( 1/8 Scaling Down )
	int m_Reserved[28];
} jpu_dec_buffer_t;

typedef struct jpu_dec_buffer3_t {
	codec_addr_t m_addrFrameBuffer[2][32][3];

	int m_iFrameBufferCount;	// allocated frame buffer count
	int m_iJPGScaleRatio;		// JPEG Scaling Ratio
					//  0: Original Size
					//  1: 1/2 Scaling Down
					//  2: 1/4 Scaling Down
					//  3: 1/8 Scaling Down
	int m_Reserved[28];
} jpu_dec_buffer3_t;

//-----------------------------------------------------
// data structure to get resulting information from
// JPU after decoding a frame
//-----------------------------------------------------

typedef struct jpu_dec_output_info_t {
	int m_iHeight;					//!< Height of input bitstream. In some cases, this value can be different from the height of previous frames.
	int m_iWidth;					//!< Width of input bitstream. In some cases, this value can be different from the height of previous frames.
	int m_iDecodingStatus;
	int m_iDispOutIdx;				//!< index of output frame buffer
	int m_iConsumedBytes;			//!< consumed bytes
	int m_iNumOfErrMBs;				//!< number of error macroblocks
	int m_Reserved[26];
} jpu_dec_output_info_t;

typedef struct jpu_dec_output_t {
	jpu_dec_output_info_t m_DecOutInfo;
	unsigned char *m_pCurrOut[2][3];	//! physical[0] and virtual[1] current  address of Y, Cb, Cr component
	int m_Reserved[25];
} jpu_dec_output_t;

// ===========================================================================
// [32 bit user-space bearer for |jpu_dec_output_t|]
typedef struct jpu_dec_output_64bit_t {
    jpu_dec_output_info_t m_DecOutInfo;
    unsigned long long m_nCurrOut[2][3];
    int m_Reserved[25];
} jpu_dec_output_64bit_t;
// ===========================================================================

/*!
 ***********************************************************************
 * \brief
 *		TCC_JPU_DEC		: main api function of libjpudec
 * \param
 *		[in]Op			: decoder operation
 * \param
 *		[in,out]pHandle	: libvpudec's handle
 * \param
 *		[in]pParam1		: init or input parameter
 * \param
 *		[in]pParam2		: output or info parameter
 * \return
 *		If successful, TCC_JPU_DEC returns 0 or plus. Otherwise, it returns a minus value.
 ***********************************************************************
 */
codec_result_t
TCC_JPU_DEC(int Op, codec_handle_t *pHandle, void *pParam1, void *pParam2);


//------------------------------------------------------------------------------
// encode struct and definition
//------------------------------------------------------------------------------

typedef struct jpu_enc_init_t {
	codec_addr_t m_RegBaseVirtualAddr;

	//! Encoding Info
	int m_iSourceFormat;				//!< input YUV format for mjpeg encoding
	int m_iPicWidth;					//!< multiple of 16
	int m_iPicHeight;					//!< multiple of 16

	int m_iEncQuality;					//!< jpeg encoding quality

	int m_iCbCrInterleaveMode;			//!< 0 (chroma separate mode   : CbCr data is written in separate frame memories)
										//!< 1 (chroma interleave mode : CbCr data is interleaved in chroma memory)

	codec_addr_t m_BitstreamBufferAddr[2]; //!< physical address : multiple of 4, virtual address : multiple of 4

	int m_iBitstreamBufferSize;			//!< multiple of 1024
	unsigned int m_uiEncOptFlags;

	//! Callback Func
	void* (*m_Memcpy) (void*, const void*, unsigned int, unsigned int);	//!< memcpy
	void  (*m_Memset) (void*, int, unsigned int, unsigned int);		//!< memset
	int   (*m_Interrupt) (void);						//!< hw interrupt (return value is always 0)
	void* (*m_Ioremap) (unsigned int, unsigned int);
	void  (*m_Iounmap) (void *);
	unsigned int (*m_reg_read)(void *, unsigned int);
	void (*m_reg_write)(void *, unsigned int, unsigned int);

	int m_Reserved[15];
} jpu_enc_init_t;

typedef struct jpu_enc_input_t {
	unsigned int m_PicYAddr;
	unsigned int m_PicCbAddr;
	unsigned int m_PicCrAddr;

	codec_addr_t m_BitstreamBufferAddr[2]; //!< physical address
	int m_iBitstreamBufferSize;
	int m_Reserved[26];
} jpu_enc_input_t;

typedef struct jpu_enc_output_t {
	codec_addr_t m_BitstreamOut[2];
	int m_iBitstreamOutSize;
	int m_iBitstreamHeaderSize;
	int m_Reserved[28];
} jpu_enc_output_t;

/*!
 ***********************************************************************
 * \brief
 *		TCC_JPU_ENC		: main api function of libjpudec
 * \param
 *		[in]Op			: encoder operation
 * \param
 *		[in,out]pHandle	: libvpudec's handle
 * \param
 *		[in]pParam1		: init or input parameter
 * \param
 *		[in]pParam2		: output or info parameter
 * \return
 *		If successful, TCC_JPU_ENC returns 0 or plus. Otherwise, it returns a minus value.
 ***********************************************************************
 */
codec_result_t
TCC_JPU_ENC(int Op, codec_handle_t *pHandle, void *pParam1, void *pParam2);

#endif
#endif	// TCC_JPU_C6__H
