/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC750X_LINUX_SUBCORE_VIDEOINPUT_H
#define DT_BINDINGS_PMAP_TCC750X_LINUX_SUBCORE_VIDEOINPUT_H

#undef SZ_1MB
#define SZ_1MB				(1024*1024)
#undef ARRAY_MBYTE
#define ARRAY_MBYTE(x)			((((x) + (SZ_1MB-1)) >> 20) << 20)

/* Output resolution for video capture memory */
#define CAMERA_OUTPUT_WIDTH		1920
#define CAMERA_OUTPUT_HEIGHT		1080

/* The number of buffers */
#define FRAMES_CAMERA_PREVIEW0		4
#define FRAMES_CAMERA_PREVIEW1		4
#define FRAMES_CAMERA_PREVIEW2		4
#define FRAMES_CAMERA_PREVIEW3		4
#define FRAMES_CAMERA_PREVIEW4		4

/* Reserved memory size */
#define PMAP_SIZE_CAMERA_PREVIEW0	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW0)
#define PMAP_SIZE_CAMERA_PREVIEW1	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW1)
#define PMAP_SIZE_CAMERA_PREVIEW2	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW2)
#define PMAP_SIZE_CAMERA_PREVIEW3	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW3)
#define PMAP_SIZE_CAMERA_PREVIEW4	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW4)

#endif	//DT_BINDINGS_PMAP_TCC750X_LINUX_SUBCORE_VIDEOINPUT_H
