# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.
#

obj-$(CONFIG_PHY_SEC08LPP_PCIE)		+= phy-sec08lpp-pcie.o
obj-$(CONFIG_PHY_SEC14LPP_PCIE)		+= phy-sec14lpp-pcie.o
obj-$(CONFIG_PHY_SS14LPP_X1NS_PCIE)		+= phy-ss14lpp-x1ns-pcie.o
obj-$(CONFIG_PHY_SS14LPP_X2NS_PCIE)		+= phy-ss14lpp-x2ns-pcie.o
