// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) Telechips Inc.
 */

#ifndef PCIE_AXON_H
#define PCIE_AXON_H

/*
 * PCIe controller wrapper link configuration registers
 */
#define PCIE_LINK_CFG00			(0x000U)
#define PCIE_LINK_CFG01			(0x004U)
#define PCIE_LINK_CFG02			(0x008U)
#define PCIE_LINK_CFG03			(0x00CU)
#define PCIE_LINK_CFG04			(0x010U)
#define PCIE_LINK_CFG07			(0x01CU)
#define PCIE_LINK_CFG08			(0x020U)
#define PCIE_LINK_CFG24			(0x060U)
#define PCIE_LINK_CFG25			(0x064U)
#define PCIE_LINK_CFG26			(0x068U)
#define PCIE_LINK_CFG30			(0x078U)
#define PCIE_LINK_CFG31			(0x07CU)
#define PCIE_LINK_CFG33			(0x084U)
#define PCIE_LINK_CFG43			(0x0ACU)
#define PCIE_LINK_CFG56			(0x0E0U)
#define PCIE_LINK_CFG88			(0x160U)
#define PCIE_LINK_CFG89			(0x164U)
#define PCIE_LINK_CFG91			(0x16CU)
#define PCIE_LINK_CFG92			(0x170U)
#define PCIE_LINK_CFG93			(0x174U)

#define PCIE_VDM_CTRL		(PCIE_LINK_CFG00)
#define PCIE_VDM_CODE		(PCIE_LINK_CFG01)
#define PCIE_VDM_DATA_LOWER		(PCIE_LINK_CFG02)
#define PCIE_VDM_DATA_UPPER		(PCIE_LINK_CFG03)
#define PCIE_LTSSM_CTRL		(PCIE_LINK_CFG04)
#define PCIE_AXI_CTRL		(PCIE_LINK_CFG07)
#define PCIE_PHY_CTRL		(PCIE_LINK_CFG08)
#define PCIE_LINK_STS		(PCIE_LINK_CFG24)
#define PCIE_LINK_STS_CLR		(PCIE_LINK_CFG25)
#define PCIE_RDLH_LINK_STS		(PCIE_LINK_CFG26)
#define PCIE_RADM_MSG_STS		(PCIE_LINK_CFG30)
#define PCIE_RADM_MSG_DATA		(PCIE_LINK_CFG31)
#define PCIE_SMLH_LINK_STS		(PCIE_LINK_CFG33)
#define PCIE_PHY_RST_CTRL		(PCIE_LINK_CFG43)
#define PCIE_SYS_INT		(PCIE_LINK_CFG56)
#define PCIE_DBI_INDIRECT_ADDR_MASK		(PCIE_LINK_CFG88)
#define PCIE_APP_CTRL		(PCIE_LINK_CFG89)
#define PCIE_LINK_INTR		(PCIE_LINK_CFG91)
#define PCIE_EDMA_INTR_STS		(PCIE_LINK_CFG92)
#define PCIE_EDMA_INTR_EN		(PCIE_LINK_CFG93)

/*
 * Mask/shift bits in PCIe related registers
 */
#define PCIE_LINK_CFG_VEN_MSG_GRANT_SHIFT (28U)
#define PCIE_LINK_CFG_VEN_MSG_FMT_SHIFT (26U)
#define PCIE_LINK_CFG_VEN_MSG_TYPE_SHIFT (21U)
#define PCIE_LINK_CFG_VEN_MSG_LEN_SHIFT (6U)
#define PCIE_LINK_CFG_VEN_MSG_REQ_SHIFT (0U)
#define PCIE_LINK_CFG_VEN_MSG_GRANT_MASK ((u32)0x1U << PCIE_LINK_CFG_VEN_MSG_GRANT_SHIFT)
#define PCIE_LINK_CFG_VEN_MSG_FMT_MASK ((u32)0x3U << PCIE_LINK_CFG_VEN_MSG_FMT_SHIFT)
#define PCIE_LINK_CFG_VEN_MSG_TYPE_MASK ((u32)0x1FU << PCIE_LINK_CFG_VEN_MSG_TYPE_SHIFT)
#define PCIE_LINK_CFG_VEN_MSG_LEN_MASK ((u32)0x3FFU << PCIE_LINK_CFG_VEN_MSG_LEN_SHIFT)
#define PCIE_LINK_CFG_VEN_MSG_REQ_MASK ((u32)0x1U << PCIE_LINK_CFG_VEN_MSG_REQ_SHIFT)

#define PCIE_LINK_CFG_VEN_MSG_TYPE(x)		((0x10U | ((u32)x)) << PCIE_LINK_CFG_VEN_MSG_TYPE_SHIFT)

#define PCIE_LINK_CFG_VEN_MSG_CODE_SHIFT (0U)
#define PCIE_LINK_CFG_VEN_MSG_CODE_MASK ((u32)0xFFU << PCIE_LINK_CFG_VEN_MSG_CODE_SHIFT)

#define PCIE_LINK_CFG_VDM_DATA_SHIFT (0U)
#define PCIE_LINK_CFG_VDM_DATA_MASK ((u32)0xFFFFFFFFU << PCIE_LINK_CFG_VDM_DATA_SHIFT)

#define PCIE_LINK_CFG_VENDOR_ID_SHIFT (16U)
#define PCIE_LINK_CFG_VENDOR_ID_MASK ((u32)0xFFFFU << PCIE_LINK_CFG_VENDOR_ID_SHIFT)

#define PCIE_LINK_CFG_RADM_VENDOR_MSG_SHIFT (3U)
#define PCIE_LINK_CFG_RADM_VENDOR_MSG_MASK ((u32)0x1U << PCIE_LINK_CFG_RADM_VENDOR_MSG_SHIFT)

#define PCIE_LINK_CFG_RDLH_LINK_UP_SHIFT		(22U)
#define PCIE_LINK_CFG_RDLH_LINK_UP_MASK		((u32)0x1U << PCIE_LINK_CFG_RDLH_LINK_UP_SHIFT)

#define PCIE_LINK_CFG_SMLH_LINK_UP_SHIFT		(17U)
#define PCIE_LINK_CFG_SMLH_LINK_UP_MASK		((u32)0x1U << PCIE_LINK_CFG_SMLH_LINK_UP_SHIFT)

#define PCIE_LINK_CFG_LTSSM_ENABLE_SHIFT		(2U)
#define PCIE_LINK_CFG_LTSSM_ENABLE_MASK		((u32)0x1U << PCIE_LINK_CFG_LTSSM_ENABLE_SHIFT)

#define PCIE_LINK_CFG_DEVICE_TYPE_SHIFT		(6U)
#define PCIE_LINK_CFG_DEVICE_TYPE_MASK		((u32)0xFU << PCIE_LINK_CFG_DEVICE_TYPE_SHIFT)

#define PCIE_LINK_CFG_INDIRECT_ADDR_MASK		(0x200000U)

#define PCIE_LINK_CFG_MSI_INT_MASK		(0x60040021U)
#define PCIE_LINK_CFG_INTX_MASK		(0x0FF8FF82U)
#define PCIE_LINK_CFG_INTR_EN_MASK		(0xFFFFFFFDU)

#define PCIE_LINK_CFG_SYS_INT_SHIFT		(0U)
#define PCIE_LINK_CFG_SYS_INT_MASK		((u32)0x1 << PCIE_LINK_CFG_SYS_INT_SHIFT)

#define PCIE_LINK_CFG_REFCLK_EXT_EN_SHIFT		(8U)
#define PCIE_LINK_CFG_PHY_REFCLK_SEL_SHIFT		(6U)
#define PCIE_LINK_CFG_REFCLK_EXT_EN_MASK		((u32)0x1U << PCIE_LINK_CFG_REFCLK_EXT_EN_SHIFT)
#define PCIE_LINK_CFG_PHY_REFCLK_SEL_MASK		((u32)0x3U << PCIE_LINK_CFG_PHY_REFCLK_SEL_SHIFT)

#define PCIE_LINK_CFG_POWER_UP_RST_SHIFT		(6U)
#define PCIE_LINK_CFG_POWER_UP_RST_MASK		((u32)0x1U << PCIE_LINK_CFG_POWER_UP_RST_SHIFT)

#define PCIE_LINK_CFG_EDMA_RD_INTR_STS_SHIFT		(4U)
#define PCIE_LINK_CFG_EDMA_WR_INTR_STS_SHIFT		(0U)
#define PCIE_LINK_CFG_EDMA_RD_INTR_STS_MASK		((u32)0xFU << PCIE_LINK_CFG_EDMA_RD_INTR_STS_SHIFT)
#define PCIE_LINK_CFG_EDMA_WR_INTR_STS_MASK		((u32)0xFU << PCIE_LINK_CFG_EDMA_WR_INTR_STS_SHIFT)
#define PCIE_LINK_CFG_EDMA_INTR_STS_MASK		(PCIE_LINK_CFG_EDMA_RD_INTR_STS_MASK | PCIE_LINK_CFG_EDMA_WR_INTR_STS_MASK)

#define PCIE_LINK_CFG_EDMA_RD_INTR_EN_SHIFT		(4U)
#define PCIE_LINK_CFG_EDMA_WR_INTR_EN_SHIFT		(0U)
#define PCIE_LINK_CFG_EDMA_RD_INTR_EN_MASK		((u32)0xFU << PCIE_LINK_CFG_EDMA_RD_INTR_EN_SHIFT)
#define PCIE_LINK_CFG_EDMA_WR_INTR_EN_MASK		((u32)0xFU << PCIE_LINK_CFG_EDMA_WR_INTR_EN_SHIFT)
#define PCIE_LINK_CFG_EDMA_INTR_EN_MASK		(PCIE_LINK_CFG_EDMA_RD_INTR_EN_MASK | PCIE_LINK_CFG_EDMA_WR_INTR_EN_MASK)
#endif		/* PCIE_AXON_H */
