/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
/*
 * Copyright (C) 2020 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC805X_LINUX_SUBCORE_VIDEOINPUT_H
#define DT_BINDINGS_PMAP_TCC805X_LINUX_SUBCORE_VIDEOINPUT_H

#undef SZ_1MB
#define SZ_1MB				(1024*1024)
#undef ARRAY_MBYTE
#define ARRAY_MBYTE(x)			((((x) + (SZ_1MB-1)) >> 20) << 20)

/* Input resolution for VIQE(de-interlacer) memory */
#define CAMERA_INPUT_PARALLEL_WIDTH	720
#define CAMERA_INPUT_PARALLEL_HEIGHT	480

/* Output resolution for video capture memory */
#define CAMERA_OUTPUT_WIDTH		1920
#define CAMERA_OUTPUT_HEIGHT		1080

/* The number of buffers */
#define FRAMES_CAMERA_VIQE		4
#define FRAMES_CAMERA_PREVIEW0		4
#define FRAMES_CAMERA_PREVIEW1		0
#define FRAMES_CAMERA_PREVIEW2		0
#define FRAMES_CAMERA_PREVIEW3		0
#define FRAMES_CAMERA_PREVIEW4		4
#define FRAMES_CAMERA_PREVIEW5		4
#define FRAMES_CAMERA_PREVIEW6		4
#define FRAMES_CAMERA_PREVIEW7		4

/* Reserved memory size */
#define PMAP_SIZE_CAMERA_VIQE		\
	ARRAY_MBYTE((CAMERA_INPUT_PARALLEL_WIDTH * (CAMERA_INPUT_PARALLEL_HEIGHT / 2) * 4 * FRAMES_CAMERA_VIQE) * 3 / 2)
#define PMAP_SIZE_CAMERA_PREVIEW0	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW0)
#define PMAP_SIZE_CAMERA_PREVIEW1	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW1)
#define PMAP_SIZE_CAMERA_PREVIEW2	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW2)
#define PMAP_SIZE_CAMERA_PREVIEW3	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW3)
#define PMAP_SIZE_CAMERA_PREVIEW4	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW4)
#define PMAP_SIZE_CAMERA_PREVIEW5	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW5)
#define PMAP_SIZE_CAMERA_PREVIEW6	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW6)
#define PMAP_SIZE_CAMERA_PREVIEW7	\
	ARRAY_MBYTE(CAMERA_OUTPUT_WIDTH * CAMERA_OUTPUT_HEIGHT * 4 * \
		FRAMES_CAMERA_PREVIEW7)

#endif	//DT_BINDINGS_PMAP_TCC805X_LINUX_SUBCORE_VIDEOINPUT_H
