/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */
#ifndef VIN_WRAP_CONFIG_H
#define	VIN_WRAP_CONFIG_H

#define get_vin_wrap_type(x)			((x) >> 8U)
#define get_vin_wrap_index(x)			((x) & 0xFFU)

/*
 * register offset
 */
#define VIN_CTL_OFFSET		(0x000U)
#define VIN_SWREST_OFFSET	(0x004U)
#define VIN_PWRDN_OFFSET	(0x008U)
#define VIN_APWRDN_OFFSET	(0x00CU)
#define VIN_IREQ0_MSK_OFFSET	(0x020U)
#define VIN_IREQ1_MSK_OFFSET	(0x024U)
#define VIN_IREQ2_MSK_OFFSET	(0x028U)
#define VIN_IREQ3_MSK_OFFSET	(0x02CU)
#define VIN_IREQ0_CLR_OFFSET	(0x030U)
#define VIN_IREQ1_CLR_OFFSET	(0x034U)
#define VIN_IREQ2_CLR_OFFSET	(0x038U)
#define VIN_IREQ3_CLR_OFFSET	(0x03CU)
#define VIN_IREQ_STS_OFFSET	(0x04CU)


/*
 * WDMA Stop Request Disable Registers
 * @Description: 0 - Enable, 1 - Disable
 */
#define S_REQ_SHIFT (0U) // Display Device 0 interrupt Status

#define S_REQ_MASK ((u32)0x1U << S_REQ_SHIFT)

/*
 * Soft Reset Registers
 * @Description: 0 - Release, 1 - Reset
 */
#define VIN0_SW_SHIFT		(0U)
#define VIN1_SW_SHIFT		(1U)
#define VIN2_SW_SHIFT		(2U)
#define VIN3_SW_SHIFT		(3U)
#define WDMA0_SW_SHIFT		(4U)
#define WDMA1_SW_SHIFT		(5U)
#define WDMA2_SW_SHIFT		(6U)
#define WDMA3_SW_SHIFT		(7U)

#define VIN0_SW_MASK		((u32)0x1U << VIN0_SW_SHIFT)
#define VIN1_SW_MASK		((u32)0x1U << VIN1_SW_SHIFT)
#define VIN2_SW_MASK		((u32)0x1U << VIN2_SW_SHIFT)
#define VIN3_SW_MASK		((u32)0x1U << VIN3_SW_SHIFT)
#define WDMA0_SW_MASK		((u32)0x1U << WDMA0_SW_SHIFT)
#define WDMA1_SW_MASK		((u32)0x1U << WDMA1_SW_SHIFT)
#define WDMA2_SW_MASK		((u32)0x1U << WDMA2_SW_SHIFT)
#define WDMA3_SW_MASK		((u32)0x1U << WDMA3_SW_SHIFT)

/*
 * Power Down Registers
 * @Description: 0 - On, 1 - Off
 */
#define VIN0_PWRDN_SHIFT	(0U)
#define VIN1_PWRDN_SHIFT	(1U)
#define VIN2_PWRDN_SHIFT	(2U)
#define VIN3_PWRDN_SHIFT	(3U)
#define WDMA0_PWRDN_SHIFT	(4U)
#define WDMA1_PWRDN_SHIFT	(4U)
#define WDMA2_PWRDN_SHIFT	(5U)
#define WDMA3_PWRDN_SHIFT	(6U)


#define VIN0_PWRDN_MASK		((u32)0x1U << VIN0_PWRDN_SHIFT)
#define VIN1_PWRDN_MASK		((u32)0x1U << VIN1_PWRDN_SHIFT)
#define VIN2_PWRDN_MASK		((u32)0x1U << VIN2_PWRDN_SHIFT)
#define VIN3_PWRDN_MASK		((u32)0x1U << VIN3_PWRDN_SHIFT)
#define WDMA0_PWRDN_MASK	((u32)0x1U << WDMA0_PWRDN_SHIFT)
#define WDMA1_PWRDN_MASK	((u32)0x1U << WDMA1_PWRDN_SHIFT)
#define WDMA2_PWRDN_MASK	((u32)0x1U << WDMA2_PWRDN_SHIFT)
#define WDMA3_PWRDN_MASK	((u32)0x1U << WDMA3_PWRDN_SHIFT)

/*
 * Auto Power Down Registers
 * @Description: 0 - Normal, 1 - AUto
 */
#define VIN_PWRDN_SHIFT		(0U)
#define WDMA_PWRDN_SHIFT	(4U)

#define VIN_PWRDN_MASK		((u32)0x1U << VIN_PWRDN_SHIFT)
#define WDMA_PWRDN_MASK		((u32)0x1U << WDMA_PWRDN_SHIFT)


/*
 * Interrupt Mask 0 Registers
 * @Description: 0 - Enable, 1 - Mask
 */
#define VIN_IREQ0_MSK_VIN0_SHIFT	(0U)
#define VIN_IREQ0_MSK_VIN1_SHIFT	(1U)
#define VIN_IREQ0_MSK_VIN2_SHIFT	(2U)
#define VIN_IREQ0_MSK_VIN3_SHIFT	(3U)
#define VIN_IREQ0_MSK_WDMA0_SHIFT	(4U)
#define VIN_IREQ0_MSK_WDMA1_SHIFT	(5U)
#define VIN_IREQ0_MSK_WDMA2_SHIFT	(6U)
#define VIN_IREQ0_MSK_WDMA3_SHIFT	(7U)

#define VIN_IREQ0_MSK_VIN0_MASK		((u32)0x1U << VIN_IREQ0_MSK_VIN0_SHIFT)
#define VIN_IREQ0_MSK_VIN1_MASK		((u32)0x1U << VIN_IREQ0_MSK_VIN1_SHIFT)
#define VIN_IREQ0_MSK_VIN2_MASK		((u32)0x1U << VIN_IREQ0_MSK_VIN2_SHIFT)
#define VIN_IREQ0_MSK_VIN3_MASK		((u32)0x1U << VIN_IREQ0_MSK_VIN3_SHIFT)
#define VIN_IREQ0_MSK_WMDA0_MASK	((u32)0x1U << VIN_IREQ0_MSK_WDNA0_SHIFT)
#define VIN_IREQ0_MSK_WDMA1_MASK	((u32)0x1U << VIN_IREQ0_MSK_WDNA1_SHIFT)
#define VIN_IREQ0_MSK_WDMA2_MASK	((u32)0x1U << VIN_IREQ0_MSK_WDNA2_SHIFT)
#define VIN_IREQ0_MSK_WDMA3_MASK	((u32)0x1U << VIN_IREQ0_MSK_WDNA3_SHIFT)

/*
 * Interrupt Mask 1 Registers
 * @Description: 0 - Enable, 1 - Mask
 */
#define VIN_IREQ1_MSK_VIN0_SHIFT	(0U)
#define VIN_IREQ1_MSK_VIN1_SHIFT	(1U)
#define VIN_IREQ1_MSK_VIN2_SHIFT	(2U)
#define VIN_IREQ1_MSK_VIN3_SHIFT	(3U)
#define VIN_IREQ1_MSK_WDMA0_SHIFT	(4U)
#define VIN_IREQ1_MSK_WDMA1_SHIFT	(5U)
#define VIN_IREQ1_MSK_WDMA2_SHIFT	(6U)
#define VIN_IREQ1_MSK_WDMA3_SHIFT	(7U)

#define VIN_IREQ1_MSK_VIN0_MASK		((u32)0x1U << VIN_IREQ1_MSK_VIN0_SHIFT)
#define VIN_IREQ1_MSK_VIN1_MASK		((u32)0x1U << VIN_IREQ1_MSK_VIN1_SHIFT)
#define VIN_IREQ1_MSK_VIN2_MASK		((u32)0x1U << VIN_IREQ1_MSK_VIN2_SHIFT)
#define VIN_IREQ1_MSK_VIN3_MASK		((u32)0x1U << VIN_IREQ1_MSK_VIN3_SHIFT)
#define VIN_IREQ1_MSK_WMDA0_MASK	((u32)0x1U << VIN_IREQ1_MSK_WDNA0_SHIFT)
#define VIN_IREQ1_MSK_WDMA1_MASK	((u32)0x1U << VIN_IREQ1_MSK_WDNA1_SHIFT)
#define VIN_IREQ1_MSK_WDMA2_MASK	((u32)0x1U << VIN_IREQ1_MSK_WDNA2_SHIFT)
#define VIN_IREQ1_MSK_WDMA3_MASK	((u32)0x1U << VIN_IREQ1_MSK_WDNA3_SHIFT)

/*
 * Interrupt Mask 2 Registers
 * @Description: 0 - Enable, 1 - Mask
 */
#define VIN_IREQ2_MSK_VIN0_SHIFT	(0U)
#define VIN_IREQ2_MSK_VIN1_SHIFT	(1U)
#define VIN_IREQ2_MSK_VIN2_SHIFT	(2U)
#define VIN_IREQ2_MSK_VIN3_SHIFT	(3U)
#define VIN_IREQ2_MSK_WDMA0_SHIFT	(4U)
#define VIN_IREQ2_MSK_WDMA1_SHIFT	(5U)
#define VIN_IREQ2_MSK_WDMA2_SHIFT	(6U)
#define VIN_IREQ2_MSK_WDMA3_SHIFT	(7U)

#define VIN_IREQ2_MSK_VIN0_MASK		((u32)0x1U << VIN_IREQ2_MSK_VIN0_SHIFT)
#define VIN_IREQ2_MSK_VIN1_MASK		((u32)0x1U << VIN_IREQ2_MSK_VIN1_SHIFT)
#define VIN_IREQ2_MSK_VIN2_MASK		((u32)0x1U << VIN_IREQ2_MSK_VIN2_SHIFT)
#define VIN_IREQ2_MSK_VIN3_MASK		((u32)0x1U << VIN_IREQ2_MSK_VIN3_SHIFT)
#define VIN_IREQ2_MSK_WMDA0_MASK	((u32)0x1U << VIN_IREQ2_MSK_WDNA0_SHIFT)
#define VIN_IREQ2_MSK_WDMA1_MASK	((u32)0x1U << VIN_IREQ2_MSK_WDNA1_SHIFT)
#define VIN_IREQ2_MSK_WDMA2_MASK	((u32)0x1U << VIN_IREQ2_MSK_WDNA2_SHIFT)
#define VIN_IREQ2_MSK_WDMA3_MASK	((u32)0x1U << VIN_IREQ2_MSK_WDNA3_SHIFT)

/*
 * Interrupt Mask 3 Registers
 * @Description: 0 - Enable, 1 - Mask
 */
#define VIN_IREQ3_MSK_VIN0_SHIFT	(0U)
#define VIN_IREQ3_MSK_VIN1_SHIFT	(1U)
#define VIN_IREQ3_MSK_VIN2_SHIFT	(2U)
#define VIN_IREQ3_MSK_VIN3_SHIFT	(3U)
#define VIN_IREQ3_MSK_WDMA0_SHIFT	(4U)
#define VIN_IREQ3_MSK_WDMA1_SHIFT	(5U)
#define VIN_IREQ3_MSK_WDMA2_SHIFT	(6U)
#define VIN_IREQ3_MSK_WDMA3_SHIFT	(7U)

#define VIN_IREQ3_MSK_VIN0_MASK		((u32)0x1U << VIN_IREQ3_MSK_VIN0_SHIFT)
#define VIN_IREQ3_MSK_VIN1_MASK		((u32)0x1U << VIN_IREQ3_MSK_VIN1_SHIFT)
#define VIN_IREQ3_MSK_VIN2_MASK		((u32)0x1U << VIN_IREQ3_MSK_VIN2_SHIFT)
#define VIN_IREQ3_MSK_VIN3_MASK		((u32)0x1U << VIN_IREQ3_MSK_VIN3_SHIFT)
#define VIN_IREQ3_MSK_WMDA0_MASK	((u32)0x1U << VIN_IREQ3_MSK_WDNA0_SHIFT)
#define VIN_IREQ3_MSK_WDMA1_MASK	((u32)0x1U << VIN_IREQ3_MSK_WDNA1_SHIFT)
#define VIN_IREQ3_MSK_WDMA2_MASK	((u32)0x1U << VIN_IREQ3_MSK_WDNA2_SHIFT)
#define VIN_IREQ3_MSK_WDMA3_MASK	((u32)0x1U << VIN_IREQ3_MSK_WDNA3_SHIFT)

/*
 * Interrupt Clear 0 Registers
 * @Description: 1 - Clear
 */
#define VIN_IREQ0_CLR_VIN0_SHIFT	(0U)
#define VIN_IREQ0_CLR_VIN1_SHIFT	(1U)
#define VIN_IREQ0_CLR_VIN2_SHIFT	(2U)
#define VIN_IREQ0_CLR_VIN3_SHIFT	(3U)
#define VIN_IREQ0_CLR_WDMA0_SHIFT	(4U)
#define VIN_IREQ0_CLR_WDMA1_SHIFT	(5U)
#define VIN_IREQ0_CLR_WDMA2_SHIFT	(6U)
#define VIN_IREQ0_CLR_WDMA3_SHIFT	(7U)

#define VIN_IREQ0_CRL_VIN0_MASK		((u32)0x1U << VIN_IREQ0_CRL_VIN0_SHIFT)
#define VIN_IREQ0_CRL_VIN1_MASK		((u32)0x1U << VIN_IREQ0_CRL_VIN1_SHIFT)
#define VIN_IREQ0_CRL_VIN2_MASK		((u32)0x1U << VIN_IREQ0_CRL_VIN2_SHIFT)
#define VIN_IREQ0_CRL_VIN3_MASK		((u32)0x1U << VIN_IREQ0_CRL_VIN3_SHIFT)
#define VIN_IREQ0_CRL_WMDA0_MASK	((u32)0x1U << VIN_IREQ0_CRL_WDNA0_SHIFT)
#define VIN_IREQ0_CRL_WDMA1_MASK	((u32)0x1U << VIN_IREQ0_CRL_WDNA1_SHIFT)
#define VIN_IREQ0_CRL_WDMA2_MASK	((u32)0x1U << VIN_IREQ0_CRL_WDNA2_SHIFT)
#define VIN_IREQ0_CRL_WDMA3_MASK	((u32)0x1U << VIN_IREQ0_CRL_WDNA3_SHIFT)

/*
 * Interrupt Clear 1 Registers
 * @Description: 1 - Clear
 */
#define VIN_IREQ1_CRL_VIN0_SHIFT	(0U)
#define VIN_IREQ1_CRL_VIN1_SHIFT	(1U)
#define VIN_IREQ1_CRL_VIN2_SHIFT	(2U)
#define VIN_IREQ1_CRL_VIN3_SHIFT	(3U)
#define VIN_IREQ1_CRL_WDMA0_SHIFT	(4U)
#define VIN_IREQ1_CRL_WDMA1_SHIFT	(5U)
#define VIN_IREQ1_CRL_WDMA2_SHIFT	(6U)
#define VIN_IREQ1_CRL_WDMA3_SHIFT	(7U)

#define VIN_IREQ1_CRL_VIN0_MASK		((u32)0x1U << VIN_IREQ1_CRL_VIN0_SHIFT)
#define VIN_IREQ1_CRL_VIN1_MASK		((u32)0x1U << VIN_IREQ1_CRL_VIN1_SHIFT)
#define VIN_IREQ1_CRL_VIN2_MASK		((u32)0x1U << VIN_IREQ1_CRL_VIN2_SHIFT)
#define VIN_IREQ1_CRL_VIN3_MASK		((u32)0x1U << VIN_IREQ1_CRL_VIN3_SHIFT)
#define VIN_IREQ1_CRL_WMDA0_MASK	((u32)0x1U << VIN_IREQ1_CRL_WDNA0_SHIFT)
#define VIN_IREQ1_CRL_WDMA1_MASK	((u32)0x1U << VIN_IREQ1_CRL_WDNA1_SHIFT)
#define VIN_IREQ1_CRL_WDMA2_MASK	((u32)0x1U << VIN_IREQ1_CRL_WDNA2_SHIFT)
#define VIN_IREQ1_CRL_WDMA3_MASK	((u32)0x1U << VIN_IREQ1_CRL_WDNA3_SHIFT)

/*
 * Interrupt Clear 2 Registers
 * @Description: 1 - Clear
 */
#define VIN_IREQ2_CRL_VIN0_SHIFT	(0U)
#define VIN_IREQ2_CRL_VIN1_SHIFT	(1U)
#define VIN_IREQ2_CRL_VIN2_SHIFT	(2U)
#define VIN_IREQ2_CRL_VIN3_SHIFT	(3U)
#define VIN_IREQ2_CRL_WDMA0_SHIFT	(4U)
#define VIN_IREQ2_CRL_WDMA1_SHIFT	(5U)
#define VIN_IREQ2_CRL_WDMA2_SHIFT	(6U)
#define VIN_IREQ2_CRL_WDMA3_SHIFT	(7U)

#define VIN_IREQ2_CRL_VIN0_MASK		((u32)0x1U << VIN_IREQ2_CRL_VIN0_SHIFT)
#define VIN_IREQ2_CRL_VIN1_MASK		((u32)0x1U << VIN_IREQ2_CRL_VIN1_SHIFT)
#define VIN_IREQ2_CRL_VIN2_MASK		((u32)0x1U << VIN_IREQ2_CRL_VIN2_SHIFT)
#define VIN_IREQ2_CRL_VIN3_MASK		((u32)0x1U << VIN_IREQ2_CRL_VIN3_SHIFT)
#define VIN_IREQ2_CRL_WMDA0_MASK	((u32)0x1U << VIN_IREQ2_CRL_WDNA0_SHIFT)
#define VIN_IREQ2_CRL_WDMA1_MASK	((u32)0x1U << VIN_IREQ2_CRL_WDNA1_SHIFT)
#define VIN_IREQ2_CRL_WDMA2_MASK	((u32)0x1U << VIN_IREQ2_CRL_WDNA2_SHIFT)
#define VIN_IREQ2_CRL_WDMA3_MASK	((u32)0x1U << VIN_IREQ2_CRL_WDNA3_SHIFT)

/*
 * Interrupt Clear 3 Registers
 * @Description: 1 - Clear
 */
#define VIN_IREQ3_CRL_VIN0_SHIFT	(0U)
#define VIN_IREQ3_CRL_VIN1_SHIFT	(1U)
#define VIN_IREQ3_CRL_VIN2_SHIFT	(2U)
#define VIN_IREQ3_CRL_VIN3_SHIFT	(3U)
#define VIN_IREQ3_CRL_WDMA0_SHIFT	(4U)
#define VIN_IREQ3_CRL_WDMA1_SHIFT	(5U)
#define VIN_IREQ3_CRL_WDMA2_SHIFT	(6U)
#define VIN_IREQ3_CRL_WDMA3_SHIFT	(7U)

#define VIN_IREQ3_CRL_VIN0_MASK		((u32)0x1U << VIN_IREQ3_CRL_VIN0_SHIFT)
#define VIN_IREQ3_CRL_VIN1_MASK		((u32)0x1U << VIN_IREQ3_CRL_VIN1_SHIFT)
#define VIN_IREQ3_CRL_VIN2_MASK		((u32)0x1U << VIN_IREQ3_CRL_VIN2_SHIFT)
#define VIN_IREQ3_CRL_VIN3_MASK		((u32)0x1U << VIN_IREQ3_CRL_VIN3_SHIFT)
#define VIN_IREQ3_CRL_WMDA0_MASK	((u32)0x1U << VIN_IREQ3_CRL_WDNA0_SHIFT)
#define VIN_IREQ3_CRL_WDMA1_MASK	((u32)0x1U << VIN_IREQ3_CRL_WDNA1_SHIFT)
#define VIN_IREQ3_CRL_WDMA2_MASK	((u32)0x1U << VIN_IREQ3_CRL_WDNA2_SHIFT)
#define VIN_IREQ3_CRL_WDMA3_MASK	((u32)0x1U << VIN_IREQ3_CRL_WDNA3_SHIFT)

/* define for only config & interrupt register */
#define VIN_WRAP_CONFIG_RESET 0x1U
#define VIN_WRAP_CONFIG_CLEAR 0x0U


typedef enum {
	VIN_WRAP_CONFIG_VIN,
	VIN_WRAP_CONFIG_WDMA
} VIN_WRAP_SWRESET_Component;

/* Interface APIs */
void VIN_WRAP_CONFIG_SWReset(unsigned int component, unsigned int resetmode);
void __iomem *VIN_WRAP_IREQConfig_GetAddress(void);
void vin_wrap_config_init(void);
#endif
