// SPDX-License-Identifier: GPL-2.0-or-later OR MIT
/*
 * Copyright (C) Telechips Inc.
 */
#include <linux/delay.h>

#include "dptx_v14.h"
#include "dptx_reg.h"
#include "dptx_dbg.h"


/*
 * For D5 (TCC807x)
 *
 *        +-----------------+
 *        |   pre-emphasis  |
 *        |      0  1  2  3 |
 *        + ----------------+
 * vswing | 0 |  1  6 13 13 |
 *        | 1 |  3  6 11    |
 *        | 2 |  5 10       |
 *        | 3 |  9          |
 *        + ----------------+
 */
static const uint32_t default_d5_main_eq[16] = {
	/* vswing 0 */
	0x01, 0x06, 0x0D, 0x0D,
	/* vswing 1 */
	0x03, 0x06, 0x0B, 0xFF,
	/* vswing 2 */
	0x05, 0x0A, 0xFF, 0xFF,
	/* vswing 3 */
	0x09, 0xFF, 0xFF, 0xFF,
};

/*
 * For D5 (TCC807x)
 *
 *        +-----------------+
 *        |   pre-emphasis  |
 *        |      0  1  2  3 |
 *        + ----------------+
 * vswing | 0 |  0  6  9 12 |
 *        | 1 |  0  6  9    |
 *        | 2 |  0  6       |
 *        | 3 |  0          |
 *        + ----------------+
 */
static const uint32_t default_d5_post_eq[16] = {
	/* vswing 0 */
	0x00, 0x06, 0x09, 0x0C,

	/* vswing 1 */
	0x00, 0x06, 0x09, 0xFF,

	/* vswing 2 */
	0x00, 0x06, 0xFF, 0xFF,

	/* vswing 3 */
	0x00, 0xFF, 0xFF, 0xFF,
};

static const uint32_t dptx_sec_main_reg_offset_table[4] = {
	SEC_PHY_REG0303,
	SEC_PHY_REG0403,
	SEC_PHY_REG0503,
	SEC_PHY_REG0603
};

static const uint32_t dptx_sec_post_reg_offset_table[4] = {
	SEC_PHY_REG0304,
	SEC_PHY_REG0404,
	SEC_PHY_REG0504,
	SEC_PHY_REG0604
};

struct sec_phy_reginfo {
	enum PHY_LINK_RATE link_rate;
	uint32_t reg_offset;
	uint32_t reg_val;
};

static struct sec_phy_reginfo sec_phy_link_setup_regs[] = {
	{LINK_RATE_RBR, SEC_PHY_REG0008, SEC_PHY_REG0008_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0008, SEC_PHY_REG0008_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0008, SEC_PHY_REG0008_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0008, SEC_PHY_REG0008_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0009, SEC_PHY_REG0009_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG000A, SEC_PHY_REG000A_INIT},

	/* Samsung Guide 2023-12-20 */
	{LINK_RATE_MAX, SEC_PHY_REG000B, SEC_PHY_REG000B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG000C, SEC_PHY_REG000C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG000D, SEC_PHY_REG000D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG000E, SEC_PHY_REG000E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG000F, SEC_PHY_REG000F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0010, SEC_PHY_REG0010_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0011, SEC_PHY_REG0011_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0012, SEC_PHY_REG0012_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0013, SEC_PHY_REG0013_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0014, SEC_PHY_REG0014_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0015, SEC_PHY_REG0015_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0016, SEC_PHY_REG0016_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0017, SEC_PHY_REG0017_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0018, SEC_PHY_REG0018_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0019, SEC_PHY_REG0019_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG001A, SEC_PHY_REG001A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG001B, SEC_PHY_REG001B_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG001C, SEC_PHY_REG001C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG001D, SEC_PHY_REG001D_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG001E, SEC_PHY_REG001E_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG001E, SEC_PHY_REG001E_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG001E, SEC_PHY_REG001E_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG001E, SEC_PHY_REG001E_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG001F, SEC_PHY_REG001F_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0020, SEC_PHY_REG0020_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0020, SEC_PHY_REG0020_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0020, SEC_PHY_REG0020_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0020, SEC_PHY_REG0020_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0021, SEC_PHY_REG0021_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0021, SEC_PHY_REG0021_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0021, SEC_PHY_REG0021_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0021, SEC_PHY_REG0021_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0022, SEC_PHY_REG0022_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0023, SEC_PHY_REG0023_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0024, SEC_PHY_REG0024_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0025, SEC_PHY_REG0025_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0025, SEC_PHY_REG0025_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0025, SEC_PHY_REG0025_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0025, SEC_PHY_REG0025_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0026, SEC_PHY_REG0026_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0027, SEC_PHY_REG0027_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0027, SEC_PHY_REG0027_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0027, SEC_PHY_REG0027_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0027, SEC_PHY_REG0027_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0028, SEC_PHY_REG0028_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0028, SEC_PHY_REG0028_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0028, SEC_PHY_REG0028_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0028, SEC_PHY_REG0028_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0029, SEC_PHY_REG0029_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG002A, SEC_PHY_REG002A_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG002A, SEC_PHY_REG002A_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG002A, SEC_PHY_REG002A_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG002A, SEC_PHY_REG002A_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG002B, SEC_PHY_REG002B_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG002B, SEC_PHY_REG002B_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG002B, SEC_PHY_REG002B_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG002B, SEC_PHY_REG002B_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG002C, SEC_PHY_REG002C_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG002C, SEC_PHY_REG002C_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG002C, SEC_PHY_REG002C_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG002C, SEC_PHY_REG002C_HBR3_INIT},

	/* Samsung Guide 2023-12-20 */
	{LINK_RATE_RBR, SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{LINK_RATE_HBR, SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{LINK_RATE_HBR2, SEC_PHY_REG002D, SEC_PHY_REG002D_RESET},
	{LINK_RATE_HBR3, SEC_PHY_REG002D, SEC_PHY_REG002D_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG002E, SEC_PHY_REG002E_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG002E, SEC_PHY_REG002E_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG002E, SEC_PHY_REG002E_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG002E, SEC_PHY_REG002E_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG002F, SEC_PHY_REG002F_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG002F, SEC_PHY_REG002F_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG002F, SEC_PHY_REG002F_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG002F, SEC_PHY_REG002F_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0030, SEC_PHY_REG0030_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0030, SEC_PHY_REG0030_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0030, SEC_PHY_REG0030_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0030, SEC_PHY_REG0030_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0031, SEC_PHY_REG0031_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0031, SEC_PHY_REG0031_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0031, SEC_PHY_REG0031_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0031, SEC_PHY_REG0031_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0032, SEC_PHY_REG0032_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0032, SEC_PHY_REG0032_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0032, SEC_PHY_REG0032_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0032, SEC_PHY_REG0032_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0033, SEC_PHY_REG0033_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0034, SEC_PHY_REG0034_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0035, SEC_PHY_REG0035_INIT},

	/* Samsung Guide 2023-12-20 */
	{LINK_RATE_MAX, SEC_PHY_REG0036, SEC_PHY_REG0036_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0037, SEC_PHY_REG0037_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0038, SEC_PHY_REG0038_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0039, SEC_PHY_REG0039_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG003A, SEC_PHY_REG003A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG003B, SEC_PHY_REG003B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG003C, SEC_PHY_REG003C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG003D, SEC_PHY_REG003D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG003E, SEC_PHY_REG003E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG003F, SEC_PHY_REG003F_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0040, SEC_PHY_REG0040_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0041, SEC_PHY_REG0041_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0042, SEC_PHY_REG0042_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0043, SEC_PHY_REG0043_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0044, SEC_PHY_REG0044_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0045, SEC_PHY_REG0045_INIT},

	/* Samsung Guide 2023-12-20 */
	{LINK_RATE_RBR, SEC_PHY_REG0046, SEC_PHY_REG0046_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0046, SEC_PHY_REG0046_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0047, SEC_PHY_REG0047_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0047, SEC_PHY_REG0047_HBR3_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0048, SEC_PHY_REG0048_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0049, SEC_PHY_REG0049_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG004A, SEC_PHY_REG004A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG004B, SEC_PHY_REG004B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG004C, SEC_PHY_REG004C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG004D, SEC_PHY_REG004D_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG004E, SEC_PHY_REG004E_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG004E, SEC_PHY_REG004E_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG004E, SEC_PHY_REG004E_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG004E, SEC_PHY_REG004E_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG004F, SEC_PHY_REG004F_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0050, SEC_PHY_REG0050_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0051, SEC_PHY_REG0051_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0051, SEC_PHY_REG0051_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0051, SEC_PHY_REG0051_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0051, SEC_PHY_REG0051_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0052, SEC_PHY_REG0052_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0052, SEC_PHY_REG0052_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0052, SEC_PHY_REG0052_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0052, SEC_PHY_REG0052_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0053, SEC_PHY_REG0053_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0053, SEC_PHY_REG0053_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0053, SEC_PHY_REG0053_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0053, SEC_PHY_REG0053_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0054, SEC_PHY_REG0054_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0054, SEC_PHY_REG0054_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0054, SEC_PHY_REG0054_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0054, SEC_PHY_REG0054_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0055, SEC_PHY_REG0055_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0055, SEC_PHY_REG0055_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0055, SEC_PHY_REG0055_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0055, SEC_PHY_REG0055_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0056, SEC_PHY_REG0056_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0056, SEC_PHY_REG0056_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0056, SEC_PHY_REG0056_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0056, SEC_PHY_REG0056_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0057, SEC_PHY_REG0057_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0057, SEC_PHY_REG0057_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0057, SEC_PHY_REG0057_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0057, SEC_PHY_REG0057_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0058, SEC_PHY_REG0058_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0058, SEC_PHY_REG0058_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0058, SEC_PHY_REG0058_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0058, SEC_PHY_REG0058_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0059, SEC_PHY_REG0059_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG005A, SEC_PHY_REG005A_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG005A, SEC_PHY_REG005A_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG005A, SEC_PHY_REG005A_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG005A, SEC_PHY_REG005A_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG005B, SEC_PHY_REG005B_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG005B, SEC_PHY_REG005B_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG005B, SEC_PHY_REG005B_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG005B, SEC_PHY_REG005B_HBR3_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG005C, SEC_PHY_REG005C_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG005D, SEC_PHY_REG005D_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG005D, SEC_PHY_REG005D_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG005D, SEC_PHY_REG005D_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG005D, SEC_PHY_REG005D_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG005E, SEC_PHY_REG005E_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG005E, SEC_PHY_REG005E_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG005E, SEC_PHY_REG005E_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG005E, SEC_PHY_REG005E_HBR3_INIT},

	/* Samsung Guide 2023-12-20 */
	{LINK_RATE_RBR, SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{LINK_RATE_HBR, SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{LINK_RATE_HBR2, SEC_PHY_REG005F, SEC_PHY_REG005F_RESET},
	{LINK_RATE_HBR3, SEC_PHY_REG005F, SEC_PHY_REG005F_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0060, SEC_PHY_REG0060_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0060, SEC_PHY_REG0060_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0060, SEC_PHY_REG0060_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0060, SEC_PHY_REG0060_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0061, SEC_PHY_REG0061_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0061, SEC_PHY_REG0061_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0061, SEC_PHY_REG0061_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0061, SEC_PHY_REG0061_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0062, SEC_PHY_REG0062_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0062, SEC_PHY_REG0062_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0062, SEC_PHY_REG0062_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0062, SEC_PHY_REG0062_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0063, SEC_PHY_REG0063_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0063, SEC_PHY_REG0063_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0063, SEC_PHY_REG0063_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0063, SEC_PHY_REG0063_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0064, SEC_PHY_REG0064_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0064, SEC_PHY_REG0064_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0064, SEC_PHY_REG0064_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0064, SEC_PHY_REG0064_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0065, SEC_PHY_REG0065_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0065, SEC_PHY_REG0065_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0065, SEC_PHY_REG0065_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0065, SEC_PHY_REG0065_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0066, SEC_PHY_REG0066_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0066, SEC_PHY_REG0066_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0066, SEC_PHY_REG0066_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0066, SEC_PHY_REG0066_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0067, SEC_PHY_REG0067_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0067, SEC_PHY_REG0067_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0067, SEC_PHY_REG0067_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0067, SEC_PHY_REG0067_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0068, SEC_PHY_REG0068_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0068, SEC_PHY_REG0068_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0068, SEC_PHY_REG0068_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0068, SEC_PHY_REG0068_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0069, SEC_PHY_REG0069_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0069, SEC_PHY_REG0069_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0069, SEC_PHY_REG0069_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0069, SEC_PHY_REG0069_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG006A, SEC_PHY_REG006A_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006A, SEC_PHY_REG006A_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006A, SEC_PHY_REG006A_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006A, SEC_PHY_REG006A_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG006B, SEC_PHY_REG006B_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006B, SEC_PHY_REG006B_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006B, SEC_PHY_REG006B_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006B, SEC_PHY_REG006B_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG006C, SEC_PHY_REG006C_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006C, SEC_PHY_REG006C_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006C, SEC_PHY_REG006C_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006C, SEC_PHY_REG006C_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG006D, SEC_PHY_REG006D_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006D, SEC_PHY_REG006D_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006D, SEC_PHY_REG006D_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006D, SEC_PHY_REG006D_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG006E, SEC_PHY_REG006E_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006E, SEC_PHY_REG006E_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006E, SEC_PHY_REG006E_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006E, SEC_PHY_REG006E_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG006F, SEC_PHY_REG006F_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG006F, SEC_PHY_REG006F_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG006F, SEC_PHY_REG006F_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG006F, SEC_PHY_REG006F_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0070, SEC_PHY_REG0070_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0070, SEC_PHY_REG0070_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0070, SEC_PHY_REG0070_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0070, SEC_PHY_REG0070_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0071, SEC_PHY_REG0071_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0071, SEC_PHY_REG0071_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0071, SEC_PHY_REG0071_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0071, SEC_PHY_REG0071_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0072, SEC_PHY_REG0072_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0072, SEC_PHY_REG0072_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0072, SEC_PHY_REG0072_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0072, SEC_PHY_REG0072_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0073, SEC_PHY_REG0073_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0073, SEC_PHY_REG0073_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0073, SEC_PHY_REG0073_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0073, SEC_PHY_REG0073_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0074, SEC_PHY_REG0074_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0074, SEC_PHY_REG0074_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0074, SEC_PHY_REG0074_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0074, SEC_PHY_REG0074_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0075, SEC_PHY_REG0075_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0075, SEC_PHY_REG0075_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0075, SEC_PHY_REG0075_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0075, SEC_PHY_REG0075_HBR3_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0076, SEC_PHY_REG0076_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0076, SEC_PHY_REG0076_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0076, SEC_PHY_REG0076_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0076, SEC_PHY_REG0076_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0077, SEC_PHY_REG0077_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0078, SEC_PHY_REG0078_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0079, SEC_PHY_REG0079_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007A, SEC_PHY_REG007A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007B, SEC_PHY_REG007B_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007C, SEC_PHY_REG007C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007D, SEC_PHY_REG007D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007E, SEC_PHY_REG007E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG007F, SEC_PHY_REG007F_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0080, SEC_PHY_REG0080_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG008A, SEC_PHY_REG008A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG008B, SEC_PHY_REG008B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG008C, SEC_PHY_REG008C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG008D, SEC_PHY_REG008D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG008E, SEC_PHY_REG008E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG008F, SEC_PHY_REG008F_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0090, SEC_PHY_REG0090_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0091, SEC_PHY_REG0091_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0092, SEC_PHY_REG0092_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0093, SEC_PHY_REG0093_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG009A, SEC_PHY_REG009A_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG031F, SEC_PHY_REG031F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0320, SEC_PHY_REG0320_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG041F, SEC_PHY_REG041F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0420, SEC_PHY_REG0420_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG051F, SEC_PHY_REG051F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0520, SEC_PHY_REG0520_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG061F, SEC_PHY_REG061F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0620, SEC_PHY_REG0620_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG003C, SEC_PHY_REG003C_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0081, SEC_PHY_REG0081_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0082, SEC_PHY_REG0082_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0083, SEC_PHY_REG0083_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0084, SEC_PHY_REG0084_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0084, SEC_PHY_REG0084_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0084, SEC_PHY_REG0084_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0084, SEC_PHY_REG0084_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0085, SEC_PHY_REG0085_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0087, SEC_PHY_REG0087_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0089, SEC_PHY_REG0089_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0095, SEC_PHY_REG0095_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0095, SEC_PHY_REG0095_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0095, SEC_PHY_REG0095_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0095, SEC_PHY_REG0095_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0097, SEC_PHY_REG0097_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR3_INIT},
	{LINK_RATE_RBR, SEC_PHY_REG0099, SEC_PHY_REG0099_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG009A, SEC_PHY_REG009A_2nd_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG009B, SEC_PHY_REG009B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0200, SEC_PHY_REG0200_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0206, SEC_PHY_REG0206_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0207, SEC_PHY_REG0207_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0303, SEC_PHY_REG0303_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0307, SEC_PHY_REG0307_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG030A, SEC_PHY_REG030A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG030B, SEC_PHY_REG030B_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG030C, SEC_PHY_REG030C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG030D, SEC_PHY_REG030D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG030E, SEC_PHY_REG030E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0310, SEC_PHY_REG0310_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0311, SEC_PHY_REG0311_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0316, SEC_PHY_REG0316_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG031B, SEC_PHY_REG031B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0403, SEC_PHY_REG0403_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0407, SEC_PHY_REG0407_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG040A, SEC_PHY_REG040A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG040B, SEC_PHY_REG040B_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG040C, SEC_PHY_REG040C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG040D, SEC_PHY_REG040D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG040E, SEC_PHY_REG040E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0410, SEC_PHY_REG0410_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0411, SEC_PHY_REG0411_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0416, SEC_PHY_REG0416_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG041B, SEC_PHY_REG041B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0503, SEC_PHY_REG0503_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0507, SEC_PHY_REG0507_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG050A, SEC_PHY_REG050A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG050B, SEC_PHY_REG050B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG050C, SEC_PHY_REG050C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG050D, SEC_PHY_REG050D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG050E, SEC_PHY_REG050E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0510, SEC_PHY_REG0510_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0511, SEC_PHY_REG0511_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0516, SEC_PHY_REG0516_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG051B, SEC_PHY_REG051B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0603, SEC_PHY_REG0603_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0607, SEC_PHY_REG0607_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG060A, SEC_PHY_REG060A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG060B, SEC_PHY_REG060B_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG060C, SEC_PHY_REG060C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG060D, SEC_PHY_REG060D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG060E, SEC_PHY_REG060E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0610, SEC_PHY_REG0610_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0611, SEC_PHY_REG0611_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0616, SEC_PHY_REG0616_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG061B, SEC_PHY_REG061B_INIT},

	{LINK_RATE_RBR, SEC_PHY_REG0099, SEC_PHY_REG0099_RBR_SC_EN},
	{LINK_RATE_HBR, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR_SC_EN},
	{LINK_RATE_HBR2, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR2_SC_EN},
	{LINK_RATE_HBR3, SEC_PHY_REG0099, SEC_PHY_REG0099_HBR3_SC_EN},

	{LINK_RATE_RBR, SEC_PHY_REG0097, SEC_PHY_REG0097_RBR_INIT},
	{LINK_RATE_HBR, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR_INIT},
	{LINK_RATE_HBR2, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR2_INIT},
	{LINK_RATE_HBR3, SEC_PHY_REG0097, SEC_PHY_REG0097_HBR3_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static struct sec_phy_reginfo sec_phy_aux_setup_regs[] = {
	{LINK_RATE_MAX, SEC_PHY_REG0113, SEC_PHY_REG0113_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0114, SEC_PHY_REG0114_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0115, SEC_PHY_REG0115_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0116, SEC_PHY_REG0116_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0117, SEC_PHY_REG0117_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0118, SEC_PHY_REG0118_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011A, SEC_PHY_REG011A_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011B, SEC_PHY_REG011B_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG011C, SEC_PHY_REG011C_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011D, SEC_PHY_REG011D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011E, SEC_PHY_REG011E_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011F, SEC_PHY_REG011F_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG010D, SEC_PHY_REG010D_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0110, SEC_PHY_REG0110_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG011F, SEC_PHY_REG011F_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0120, SEC_PHY_REG0120_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 1000},
	{LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 10},
	{LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_2nd_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 10},
	{LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_3rd_INIT},

	{LINK_RATE_MAX, SEC_PHY_DELAY_USEC_REG, 100},
	{LINK_RATE_MAX, SEC_PHY_REG0123, SEC_PHY_REG0123_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static struct sec_phy_reginfo sec_phy_sb_setup_regs[] = {
	{LINK_RATE_MAX, SEC_PHY_REG0103, SEC_PHY_REG0103_3rd_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_4th_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0102, SEC_PHY_REG0102_3rd_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG010F, SEC_PHY_REG010F_3rd_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0104, SEC_PHY_REG0104_4th_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0123, SEC_PHY_REG0123_2nd_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG0108, SEC_PHY_REG0108_INIT},
	{LINK_RATE_MAX, SEC_PHY_REG_MAX, SEC_PHY_REG_DTAT_0_RST}
};

static void dptx_reset_sec_phy(struct Dptx_Params *pstDptx)
{
	uint32_t reg_wval;

	if (pstDptx->ePhy_Dev == PHY_DEVICE_SEC) {
		reg_wval = ((uint32_t)PHY_CLK_DIV_DISABLE | (uint32_t)LC_REF_RO_PLL);
		(void)Dptx_Cfg_Set_PHY_Cfg(pstDptx, reg_wval);

		reg_wval = ((uint32_t)CFG_LANE_RESET | (uint32_t)CFG_CMN_RESET
			  | (uint32_t)CFG_INT_RESET);
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);

		reg_wval |= (uint32_t)CFG_DP_PHY_APB_RESET;
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);
		udelay(1);

		reg_wval &= ~(uint32_t)CFG_DP_PHY_APB_RESET;
		(void)Dptx_Cfg_SoftReset(pstDptx, reg_wval);
	}
}

static int32_t dptx_sec_set_num_of_lanes(const struct Dptx_Params *pstDptx, uint8_t ucLanes)
{
	uint32_t reg_addr, reg_offset, reg_val;
	int32_t ret = DPTX_RETURN_NO_ERROR;

	if (pstDptx->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (!IS_OFFSET_WITHIN_LIMIT(pstDptx->uiSEC_PHY_Reg_Offset)) {
			dptx_err("Invalid reg offset as 0x%x",
				  pstDptx->uiRegBank_RegAddr_Offset);
			ret = DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			reg_addr = pstDptx->uiSEC_PHY_Reg_Offset;
			reg_offset = (uint32_t)SEC_PHY_REG0207;

			switch (ucLanes) {
			case 1u:
				reg_val = 0x01U;
				break;
			case 2u:
				reg_val = 0x03U;
				break;
			case 4u:
				reg_val = 0x0FU;
				break;
			default:
				dptx_err("Invalid Num of lanes as 0x%x", ucLanes);
				ret = -DPTX_RETURN_EINVAL;
				break;
			}

		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if (IS_OFFSET_OVERFLOW(reg_addr, reg_offset)) {
				dptx_err("Register address overflow: base=0x%x, offset=0x%x",
					  reg_addr, reg_offset);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			Dptx_Reg_Writel(pstDptx,
					(reg_addr + reg_offset), reg_val);
		}
	}

	return ret;
}

int32_t Dptx_Sec_PHY_Init(struct Dptx_Params *pstDptx, uint8_t ucLinkRate, uint8_t ucLanes)
{
	uint32_t phy_cfg_val, reg_idx, reg_addr, reg_offset, reg_val;
	const struct sec_phy_reginfo *sec_phy_setup_regs;
	int32_t ret = DPTX_RETURN_NO_ERROR;
	enum PHY_LINK_RATE link_rate;
	bool phy_ready;

	if (pstDptx->ePhy_Dev == PHY_DEVICE_SEC) {
		dptx_reset_sec_phy(pstDptx);

		if (!IS_OFFSET_WITHIN_LIMIT(pstDptx->uiSEC_PHY_Reg_Offset)) {
			dptx_err("Invalid reg offset as 0x%x", pstDptx->uiRegBank_RegAddr_Offset);

			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			dptx_dbg("Init SEC Phy with Max rate(%u) = %s",
				  ucLinkRate,
				  (ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_RBR) ? "RBR" :
				  (ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR) ? "HBR" :
				  (ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR2) ? "HBR2" : "HBR3");

			reg_addr = pstDptx->uiSEC_PHY_Reg_Offset;

			sec_phy_setup_regs = (const struct sec_phy_reginfo *)sec_phy_link_setup_regs;

			/* Set LC (cascade) or RO PLL */
			phy_cfg_val = (ucLinkRate == (uint8_t)DPTX_PHYIF_CTRL_RATE_HBR3) ?
				((uint32_t)PHY_CLK_DIV_DISABLE | (uint32_t)RO_REF_RO_PLL) :
				((uint32_t)PHY_CLK_DIV_DISABLE | (uint32_t)LC_REF_RO_PLL);
			ret = Dptx_Cfg_Set_PHY_Cfg(pstDptx, phy_cfg_val);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			for (reg_idx = 0u;
			     (sec_phy_setup_regs[reg_idx].reg_offset != (uint32_t)SEC_PHY_REG_MAX);
			     reg_idx++) {
				link_rate = sec_phy_setup_regs[reg_idx].link_rate;
				if ((link_rate != LINK_RATE_MAX) &&
					((uint8_t)link_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}
				if (sec_phy_setup_regs[reg_idx].reg_offset == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(sec_phy_setup_regs[reg_idx].reg_val);
					continue;
				}

				dptx_debug("Reg[0x%x] = 0x%x", sec_phy_setup_regs[reg_idx].reg_offset, sec_phy_setup_regs[reg_idx].reg_val);

				reg_val = sec_phy_setup_regs[reg_idx].reg_val;
				reg_offset = sec_phy_setup_regs[reg_idx].reg_offset;

				Dptx_Reg_Writel(pstDptx, (reg_addr + reg_offset), reg_val);
			}

			/* enable PHY_BIAS and PHY_BGR */
			phy_cfg_val |= ((uint32_t)CFG_BIAS_EN | (uint32_t)CFG_BGR_EN);
			ret = Dptx_Cfg_Set_PHY_Cfg(pstDptx, phy_cfg_val);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			udelay(10);
			sec_phy_setup_regs = (const struct sec_phy_reginfo *)sec_phy_aux_setup_regs;

			for (reg_idx = 0; (sec_phy_setup_regs[reg_idx].reg_offset != (uint32_t)SEC_PHY_REG_MAX); reg_idx++) {

				link_rate = sec_phy_setup_regs[reg_idx].link_rate;

				if ((link_rate != LINK_RATE_MAX) &&
				    ((uint8_t)link_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}

				if (sec_phy_setup_regs[reg_idx].reg_offset == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(sec_phy_setup_regs[reg_idx].reg_val);
					continue;
				}

				dptx_debug("Reg[0x%x] = 0x%x", sec_phy_setup_regs[reg_idx].reg_offset, sec_phy_setup_regs[reg_idx].reg_val);

				reg_val = sec_phy_setup_regs[reg_idx].reg_val;
				reg_offset = sec_phy_setup_regs[reg_idx].reg_offset;

				Dptx_Reg_Writel(pstDptx, (reg_addr + reg_offset), reg_val);
			}
			/* release PHY_INIT_reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)(CFG_LANE_RESET | CFG_CMN_RESET | CFG_DP_MB_RESET));
			udelay(10);

			phy_cfg_val |= (uint32_t)CFG_PLL_EN;
			ret = Dptx_Cfg_Set_PHY_Cfg(pstDptx, phy_cfg_val);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			udelay(10);

			/* release PHY_CMN reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)CFG_LANE_RESET | (uint32_t)CFG_DP_MB_RESET);

			/* wait o_pll_lock_done and o_pll_clk_rdy */
			ret = Dptx_Cfg_Check_PHY_Pll(pstDptx, &phy_ready);
		}
		if (DPTX_RETURN_SUCCESS(ret) && phy_ready) {
			udelay(10);
			/* release PHY_lane_reset */
			(void)Dptx_Cfg_SoftReset(pstDptx, (uint32_t)CFG_DP_MB_RESET);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			/* wait o_phy_rdy */
			ret = Dptx_Cfg_Check_PHY_Ready(pstDptx, &phy_ready);
		}
		if (DPTX_RETURN_SUCCESS(ret) && phy_ready) {
			sec_phy_setup_regs = (const struct sec_phy_reginfo *)sec_phy_sb_setup_regs;

			for (reg_idx = 0; (sec_phy_setup_regs[reg_idx].reg_offset != (uint32_t)SEC_PHY_REG_MAX); reg_idx++) {

				link_rate = sec_phy_setup_regs[reg_idx].link_rate;

				if ((link_rate != LINK_RATE_MAX) &&
				    ((uint8_t)link_rate != ucLinkRate)) {
					/*For KCS */
					continue;
				}

				if (sec_phy_setup_regs[reg_idx].reg_offset == (uint32_t)SEC_PHY_DELAY_USEC_REG) {
					udelay(sec_phy_setup_regs[reg_idx].reg_val);
					continue;
				}

				reg_val = sec_phy_setup_regs[reg_idx].reg_val;
				reg_offset = sec_phy_setup_regs[reg_idx].reg_offset;

				if (reg_offset == (uint32_t)SEC_PHY_REG0108) {
					reg_val &= ~((uint32_t)3u << 4);
					reg_val |= ((pstDptx->hw_config.aux_hysteresis & 0x3u) << 4);
				}

				Dptx_Reg_Writel(pstDptx, (reg_addr + reg_offset), reg_val);
			}

			ret = Dptx_Cfg_Check_Sec_PHY_SB_Ready(pstDptx, &phy_ready);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			/* For KCS */
			ret = dptx_sec_set_num_of_lanes(pstDptx, ucLanes);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			for (reg_idx = 0; reg_idx < ucLanes; reg_idx++) {
				ret = dptx_sec_set_phy_sigan_quality(pstDptx, reg_idx, ucLinkRate, VOLTAGE_SWING_LEVEL_0, PRE_EMPHASIS_LEVEL_0);
				if (DPTX_RETURN_ERROR(ret)) {
					/* For KCS */
					break;
				}
			}
		}
	}
	return ret;
}

uint32_t dptx_sec_get_main_equalization(const struct Dptx_Params *dptx_params, uint8_t lane_idx)
{
	uint32_t reg_offset, reg_addr;
	uint32_t reg_val = 0u;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
		} else {
			if (!IS_OFFSET_WITHIN_LIMIT(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg offset as 0x%x", dptx_params->uiRegBank_RegAddr_Offset);
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_main_reg_offset_table[lane_idx];

				if (IS_OFFSET_OVERFLOW(reg_addr, reg_offset)) {
					dptx_err("Register address overflow: base=0x%x, offset=0x%x",
						  reg_addr, reg_offset);
				} else {
					reg_val = Dptx_Reg_Readl(dptx_params, (reg_addr +  reg_offset));
					reg_val &= 0x1Fu;
				}
			}
		}
	}
	return reg_val;
}

int32_t dptx_sec_set_main_equalization(const struct Dptx_Params *dptx_params, uint8_t lane_idx, uint32_t eq_val)
{
	uint32_t reg_offset, reg_addr, reg_val;
	int32_t ret = DPTX_RETURN_NO_ERROR;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (eq_val > 13u) {  /* 0 to 14 */
			dptx_err("Invalid VSW as %u", eq_val);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if (!IS_OFFSET_WITHIN_LIMIT(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg offset as 0x%x", dptx_params->uiRegBank_RegAddr_Offset);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
			reg_offset = dptx_sec_main_reg_offset_table[lane_idx];

			reg_val = (uint32_t)1u << 5; /* enable overrid */
			reg_val |= (eq_val & 0x1Fu);
			if (IS_OFFSET_OVERFLOW(reg_addr, reg_offset)) {
				dptx_err("Register address overflow: base=0x%x, offset=0x%x",
					  reg_addr, reg_offset);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			Dptx_Reg_Writel(dptx_params,
					(reg_addr +  reg_offset), reg_val);
		}
	}
	return ret;
}

uint32_t dptx_sec_get_post_equalization(const struct Dptx_Params *dptx_params, uint8_t lane_idx)
{
	uint32_t reg_offset, reg_addr;
	uint32_t reg_val = 0u;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (lane_idx > (uint8_t)3u) {
			dptx_err("Invalid lane idx as %u", lane_idx);
		} else {
			if (!IS_OFFSET_WITHIN_LIMIT(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg offset as 0x%x", dptx_params->uiRegBank_RegAddr_Offset);
			} else {
				reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
				reg_offset = dptx_sec_post_reg_offset_table[lane_idx];
				if (IS_OFFSET_OVERFLOW(reg_addr, reg_offset)) {
					dptx_err("Register address overflow: base=0x%x, offset=0x%x",
						  reg_addr, reg_offset);
				} else {
					reg_val = Dptx_Reg_Readl(dptx_params, (reg_addr +  reg_offset));
					reg_val &= 0xFu;
				}
			}
		}
	}
	return reg_val;
}

int32_t dptx_sec_set_post_equalization(const struct Dptx_Params *dptx_params, uint8_t lane_idx, uint32_t eq_val)
{
	int32_t ret = DPTX_RETURN_NO_ERROR;
	uint32_t reg_offset, reg_addr, reg_val;

	if (dptx_params->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if (eq_val > 15u) { /* 0 to 14 */
			dptx_err("Invalid VSW as %u", eq_val);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if (!IS_OFFSET_WITHIN_LIMIT(dptx_params->uiSEC_PHY_Reg_Offset)) {
				dptx_err("Invalid reg offset as 0x%x",
					  dptx_params->uiRegBank_RegAddr_Offset);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			reg_addr = dptx_params->uiSEC_PHY_Reg_Offset;
			reg_offset = dptx_sec_post_reg_offset_table[lane_idx];

			reg_val = (uint32_t)1u << 4; /* enable overrid */
			reg_val |= (eq_val & 0xFu);
			if (IS_OFFSET_OVERFLOW(reg_addr, reg_offset)) {
				dptx_err("Register address overflow: base=0x%x, offset=0x%x",
					  reg_addr, reg_offset);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			Dptx_Reg_Writel(dptx_params,
					(reg_addr +  reg_offset), reg_val);
		}
	}
	return ret;
}

int32_t dptx_sec_set_phy_sigan_quality(const struct Dptx_Params *dev_param,
				       uint32_t lane_idx,
				       uint8_t link_rate,
				       enum PHY_VOLTAGE_SWING_LEVEL voltage_swing,
				       enum PHY_PRE_EMPHASIS_LEVEL pre_emphasis)
{
	int32_t ret = DPTX_RETURN_NO_ERROR;
	uint8_t linear_idx;

	if (dev_param->ePhy_Dev != PHY_DEVICE_SEC) {
		dptx_debug("Nothing to do not for Samsung PHY");
	} else {
		if ((uint8_t)voltage_swing >= (uint8_t)VOLTAGE_SWING_LEVEL_MAX) {
			dptx_err("Invalid VSW as %u", (uint8_t)voltage_swing);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			if ((uint8_t)pre_emphasis >= (uint8_t)PRE_EMPHASIS_LEVEL_MAX) {
				dptx_err("Invalid Pre-emp as %u", (uint8_t)pre_emphasis);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (lane_idx > (uint8_t)PHY_LANE_3) {
			dptx_err("Invalid lane idx as %u", lane_idx);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (link_rate > (uint8_t)LINK_RATE_HBR3) {
			dptx_err("Invalid link rate as %u", link_rate);
			ret = -DPTX_RETURN_EINVAL;
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			linear_idx = ((uint8_t)voltage_swing * 4u) + (uint8_t)pre_emphasis;

			if ((linear_idx == 7u) || (linear_idx == 10u) ||
			    (linear_idx == 11u) || (linear_idx == 13u) ||
			    (linear_idx == 14u) || (linear_idx == 15u) ||
			    (linear_idx >= 16u)) {
				dptx_err("Not allowed voltage swing %u level and pre-emphsis %u level",
					  (uint8_t)voltage_swing, (uint8_t)pre_emphasis);
				ret = -DPTX_RETURN_EINVAL;
			}
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			ret = dptx_sec_set_main_equalization(dev_param, (uint8_t)lane_idx,
					dev_param->hw_config.phy_eq[link_rate].main_eq[linear_idx]);
		}
		if (DPTX_RETURN_SUCCESS(ret)) {
			ret = dptx_sec_set_post_equalization(dev_param, (uint8_t)lane_idx,
					dev_param->hw_config.phy_eq[link_rate].post_eq[linear_idx]);
		}
	}
	return ret;
}

void dptx_sec_get_default_phy_eq(const struct Dptx_Params *dev_param,
				 uint32_t default_main_eq[16],
				 uint32_t default_post_eq[16])
{
	if (dev_param->ePhy_Dev == PHY_DEVICE_SEC) {
		(void)memcpy(default_main_eq, default_d5_main_eq, sizeof(uint32_t) * 16u);
		(void)memcpy(default_post_eq, default_d5_post_eq, sizeof(uint32_t) * 16u);
	}
}

