# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

obj-$(CONFIG_TELECHIPS_DPTX_AUDIO)         += dptx_audio/
obj-$(CONFIG_SND_SOC_TELECHIPS_AUDIO_CHMUX) += tcc_audio_cfg.o
obj-$(CONFIG_SND_SOC_TELECHIPS_EXTENDED_TBD) += tcc_audio_masrc.o tcc_audio_reorder_splitter.o tcc_audio_volume.o tcc_audio_fifo_ctl_pcm.o tcc_audio_mixer.o
obj-$(CONFIG_SND_SOC_TELECHIPS) += tcc_adma_pcm.o tcc_audio_spdif.o tcc_audio_daif.o
obj-$(CONFIG_SND_SOC_TELECHIPS_CARD) += tcc-snd-card.o
