/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */
#ifndef TCC_AUDIO_ACFG_HW_H
#define TCC_AUDIO_ACFG_HW_H
/*** Audio subsystem Configuration Register Map (CFG Base Address + offset) ***/
#define TCC_CFG_DAIF_PORT_SEL			(0x0000)
#define TCC_CFG_SPDIF_PORT_SEL		(0x0004)
#define TCC_CFG_DP_PORT_SEL				(0x0008)
#define TCC_CFG_MAIC_PROT_CACHE0	(0x0010)
#define TCC_CFG_MAIC_PROT_CACHE1	(0x0014)
#define TCC_CFG_MAIC_PROT_CACHE2	(0x0018)
#define TCC_CFG_MAIC_PROT_CACHE3	(0x001C)
#define TCC_CFG_MAIC_PROT_CACHE4	(0x0020)
#define TCC_CFG_MAIC_PROT_CACHE5	(0x0024)
#define TCC_CFG_MAIC_PROT_CACHE6	(0x0028)
#define TCC_CFG_MAIC_PROT_CACHE7	(0x002C)
#define TCC_CFG_MAVC_PROT_CACHE0	(0x0030)
#define TCC_CFG_MAVC_PROT_CACHE1	(0x0034)
#define TCC_CFG_MAVC_PROT_CACHE2	(0x0038)
#define TCC_CFG_MAVC_PROT_CACHE3	(0x003C)
#define TCC_CFG_MAVC_PROT_CACHE4	(0x0040)
#define TCC_CFG_MAVC_PROT_CACHE5	(0x0044)
#define TCC_CFG_MAVC_PROT_CACHE6	(0x0048)
#define TCC_CFG_MAVC_PROT_CACHE7	(0x004C)
#define TCC_CFG_MARS_PROT_CACHE0	(0x0050)
#define TCC_CFG_MARS_PROT_CACHE1	(0x0054)
#define TCC_CFG_MARS_PROT_CACHE2	(0x0058)
#define TCC_CFG_MARS_PROT_CACHE3	(0x005C)
#define TCC_CFG_MARS_PROT_CACHE4	(0x0060)
#define TCC_CFG_MARS_PROT_CACHE5	(0x0064)
#define TCC_CFG_MASM_PROT_CACHE0	(0x0068)
#define TCC_CFG_MASM_PROT_CACHE1	(0x006C)
#define TCC_CFG_MASM_PROT_CACHE2	(0x0070)
#define TCC_CFG_MASM_PROT_CACHE3	(0x0074)
#define TCC_CFG_MASM_PROT_CACHE4	(0x0078)
#define TCC_CFG_MASRC_PROT_CACHE0	(0x007C)
#define TCC_CFG_MASRC_PROT_CACHE1	(0x0080)
#define TCC_CFG_MASRC_PROT_CACHE2	(0x0084)
#define TCC_CFG_MASRC_PROT_CACHE3	(0x0088)
#define TCC_CFG_MASRC_PROT_CACHE4	(0x008C)
#define TCC_CFG_MASRC_PROT_CACHE5	(0x0090)
#define TCC_CFG_ACFG_PROT_CACHE0	(0x0094)
#define TCC_CFG_ACFG_PROT_CACHE1	(0x0098)
#define TCC_CFG_ACFG_PROT_CACHE2	(0x009C)
#define TCC_CFG_ACFG_PROT_CACHE3	(0x00A0)
#define TCC_CFG_X2X_MST_CLK_CFG		(0x00A4)
#define TCC_CFG_X2X_SLV_CLK_CFG		(0x00A8)
#define TCC_CFG_X2X_SLV_PWR_CFG		(0x00AC)

/************ Multi-channel Audio FIFO Controller (MAFC) **************/
/* DAIF Port Selection Register DAIF_PORT_SEL  */
#define ACFG_DAIF_PORT_SEL_MAIC_Msk			((uint32_t)0x3U)

#define ACFG_DAIF_PORT_SEL_MAIC7_Pos		(28)
#define ACFG_DAIF_PORT_SEL_MAIC7_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC7_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC7_MAUDIO_PORT1	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC7_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC7_SAUDIO_PORT0	((uint32_t)0x1U << ACFG_DAIF_PORT_SEL_MAIC7_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC6_Pos		(24)
#define ACFG_DAIF_PORT_SEL_MAIC6_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC6_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC6_SAUDIO_PORT5	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC6_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC5_Pos		(20)
#define ACFG_DAIF_PORT_SEL_MAIC5_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC5_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC5_SAUDIO_PORT4	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC5_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC4_Pos		(16)
#define ACFG_DAIF_PORT_SEL_MAIC4_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC4_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC4_MAUDIO_PORT3	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC4_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC4_SAUDIO_PORT3	((uint32_t)0x1U << ACFG_DAIF_PORT_SEL_MAIC4_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC3_Pos		(12)
#define ACFG_DAIF_PORT_SEL_MAIC3_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC3_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC3_MAUDIO_PORT0	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC3_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC2_Pos		(8)
#define ACFG_DAIF_PORT_SEL_MAIC2_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC2_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC2_PORT0_MAUDIO	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC2_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC2_PORT1_SAUDIO	((uint32_t)0x1U << ACFG_DAIF_PORT_SEL_MAIC2_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC2_PORT2_SAUDIO	((uint32_t)0x1U << ACFG_DAIF_PORT_SEL_MAIC2_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC1_Pos		(4)
#define ACFG_DAIF_PORT_SEL_MAIC1_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC1_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC1_PORT4_MAUDIO	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC1_Pos)

#define ACFG_DAIF_PORT_SEL_MAIC0_Pos		(0)
#define ACFG_DAIF_PORT_SEL_MAIC0_Msk		((uint32_t)0x3U << ACFG_DAIF_PORT_SEL_MAIC0_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC0_PORT1_MAUDIO	((uint32_t)0x0U << ACFG_DAIF_PORT_SEL_MAIC0_Pos)
#define ACFG_DAIF_PORT_SEL_MAIC0_PORT0_SAUDIO	((uint32_t)0x1U << ACFG_DAIF_PORT_SEL_MAIC0_Pos)

/* S/PDIF Port Selection Register SPDIF_PORT_SEL */
#define ACFG_SPDIF_PORT_SEL_MAIC_Msk		((uint32_t)0xFU)

#define ACFG_SPDIF_PORT_SEL_PORT6_Pos		(24)
#define ACFG_SPDIF_PORT_SEL_PORT6_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT6_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT6_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT5_Pos		(20)
#define ACFG_SPDIF_PORT_SEL_PORT5_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT5_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT5_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT4_Pos		(16)
#define ACFG_SPDIF_PORT_SEL_PORT4_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT4_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT4_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT3_Pos		(12)
#define ACFG_SPDIF_PORT_SEL_PORT3_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT3_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT3_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT2_Pos		(8)
#define ACFG_SPDIF_PORT_SEL_PORT2_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT2_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT2_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT1_Pos		(4)
#define ACFG_SPDIF_PORT_SEL_PORT1_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT1_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT1_Pos)

#define ACFG_SPDIF_PORT_SEL_PORT0_Pos		(0)
#define ACFG_SPDIF_PORT_SEL_PORT0_Msk		((uint32_t)0xFU << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC0		((uint32_t)0x0U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC1		((uint32_t)0x1U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC2		((uint32_t)0x2U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC3		((uint32_t)0x3U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC4		((uint32_t)0x4U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC5		((uint32_t)0x5U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC6		((uint32_t)0x6U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)
#define ACFG_SPDIF_PORT_SEL_PORT0_MAIC7		((uint32_t)0x7U << ACFG_SPDIF_PORT_SEL_PORT0_Pos)

/* DP Port Selection Register DP_PORT_SEL */
#define ACFG_DP_PORT_SEL_MAIC_Msk		((uint32_t)0xFU)

#define ACFG_DP_PORT_SEL_PORT3_Pos		(12)
#define ACFG_DP_PORT_SEL_PORT3_Msk		((uint32_t)0xFU << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC0		((uint32_t)0x0U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC1		((uint32_t)0x1U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC2		((uint32_t)0x2U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC3		((uint32_t)0x3U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC4		((uint32_t)0x4U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC5		((uint32_t)0x5U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC6		((uint32_t)0x6U << ACFG_DP_PORT_SEL_PORT3_Pos)
#define ACFG_DP_PORT_SEL_PORT3_MAIC7		((uint32_t)0x7U << ACFG_DP_PORT_SEL_PORT3_Pos)

#define ACFG_DP_PORT_SEL_PORT2_Pos		(8)
#define ACFG_DP_PORT_SEL_PORT2_Msk		((uint32_t)0xFU << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC0		((uint32_t)0x0U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC1		((uint32_t)0x1U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC2		((uint32_t)0x2U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC3		((uint32_t)0x3U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC4		((uint32_t)0x4U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC5		((uint32_t)0x5U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC6		((uint32_t)0x6U << ACFG_DP_PORT_SEL_PORT2_Pos)
#define ACFG_DP_PORT_SEL_PORT2_MAIC7		((uint32_t)0x7U << ACFG_DP_PORT_SEL_PORT2_Pos)

#define ACFG_DP_PORT_SEL_PORT1_Pos		(4)
#define ACFG_DP_PORT_SEL_PORT1_Msk		((uint32_t)0xFU << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC0		((uint32_t)0x0U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC1		((uint32_t)0x1U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC2		((uint32_t)0x2U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC3		((uint32_t)0x3U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC4		((uint32_t)0x4U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC5		((uint32_t)0x5U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC6		((uint32_t)0x6U << ACFG_DP_PORT_SEL_PORT1_Pos)
#define ACFG_DP_PORT_SEL_PORT1_MAIC7		((uint32_t)0x7U << ACFG_DP_PORT_SEL_PORT1_Pos)

#define ACFG_DP_PORT_SEL_PORT0_Pos		(0)
#define ACFG_DP_PORT_SEL_PORT0_Msk		((uint32_t)0xFU << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC0		((uint32_t)0x0U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC1		((uint32_t)0x1U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC2		((uint32_t)0x2U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC3		((uint32_t)0x3U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC4		((uint32_t)0x4U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC5		((uint32_t)0x5U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC6		((uint32_t)0x6U << ACFG_DP_PORT_SEL_PORT0_Pos)
#define ACFG_DP_PORT_SEL_PORT0_MAIC7		((uint32_t)0x7U << ACFG_DP_PORT_SEL_PORT0_Pos)

/* AxPROT/AxCACHE Control Register x_PROT_CACHEn */
#define ACFG_PROT_CACHE_AR_CACHE_SEL_Pos	(28)
#define ACFG_PROT_CACHE_AR_CACHE_SEL_Msk	((uint32_t)0xFU << ACFG_PROT_CACHE_AR_CACHE_SEL_Pos)

#define ACFG_PROT_CACHE_AR_CACHE_CFG_Pos	(24)
#define ACFG_PROT_CACHE_AR_CACHE_CFG_Msk	((uint32_t)0xFU << ACFG_PROT_CACHE_AR_CACHE_CFG_Pos)

#define ACFG_PROT_CACHE_AR_PROT_SEL_Pos		(20)
#define ACFG_PROT_CACHE_AR_PROT_SEL_Msk		((uint32_t)0x7U << ACFG_PROT_CACHE_AR_PROT_SEL_Pos)

#define ACFG_PROT_CACHE_AR_PROT_CFG_Pos		(16)
#define ACFG_PROT_CACHE_AR_PROT_CFG_Msk		((uint32_t)0x7U << ACFG_PROT_CACHE_AR_PROT_CFG_Pos)

#define ACFG_PROT_CACHE_AW_CACHE_SEL_Pos	(12)
#define ACFG_PROT_CACHE_AW_CACHE_SEL_Msk	((uint32_t)0xFU << ACFG_PROT_CACHE_AW_CACHE_SEL_Pos)

#define ACFG_PROT_CACHE_AW_CACHE_CFG_Pos	(8)
#define ACFG_PROT_CACHE_AW_CACHE_CFG_Msk	((uint32_t)0xFU << ACFG_PROT_CACHE_AW_CACHE_CFG_Pos)

#define ACFG_PROT_CACHE_AW_PROT_SEL_Pos		(4)
#define ACFG_PROT_CACHE_AW_PROT_SEL_Msk		((uint32_t)0x7U << ACFG_PROT_CACHE_AW_PROT_SEL_Pos)

#define ACFG_PROT_CACHE_AW_PROT_CFG_Pos		(0)
#define ACFG_PROT_CACHE_AW_PROT_CFG_Msk		((uint32_t)0x7U << ACFG_PROT_CACHE_AW_PROT_CFG_Pos)

/* AXI Domain Bridge Master Clock Control Register X2X_MST_CLK_CFG */
#define ACFG_MST_CLK_CFG_DELAY_Pos		(16)
#define ACFG_MST_CLK_CFG_DELAY_Msk		((uint32_t)0xFFFFU << ACFG_MST_CLK_CFG_DELAY_Pos)

#define ACFG_MST_CLK_CFG_QFSM_STATE_Pos	(12)
#define ACFG_MST_CLK_CFG_QFSM_STATE_Msk	((uint32_t)0x7U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_STOPPED	((uint32_t)0x0U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_EXIT	((uint32_t)0x1U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_RUN	((uint32_t)0x2U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_DELAY	((uint32_t)0x3U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_REQUEST	((uint32_t)0x4U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_MST_CLK_CFG_QFSM_STATE_DENIED	((uint32_t)0x5U << ACFG_MST_CLK_CFG_QFSM_STATE_Pos)

#define ACFG_MST_CLK_CFG_M_QDENY_Pos	(11)
#define ACFG_MST_CLK_CFG_M_QDENY_Msk	((uint32_t)0x1U << ACFG_MST_CLK_CFG_M_QDENY_Pos)

#define ACFG_MST_CLK_CFG_M_QACCEPTN_Pos	(10)
#define ACFG_MST_CLK_CFG_M_QACCEPTN_Msk	((uint32_t)0x1U << ACFG_MST_CLK_CFG_M_QACCEPTN_Pos)

#define ACFG_MST_CLK_CFG_M_QACTIVE_Pos	(9)
#define ACFG_MST_CLK_CFG_M_QACTIVE_Msk	((uint32_t)0x1U << ACFG_MST_CLK_CFG_M_QACTIVE_Pos)

#define ACFG_MST_CLK_CFG_M_QREQN_Pos	(8)
#define ACFG_MST_CLK_CFG_M_QREAN_Msk	((uint32_t)0x1U << ACFG_MST_CLK_CFG_M_QREQN_Pos)

#define ACFG_MST_CLK_CFG_CC_MODE_ACK_Pos	(4)
#define ACFG_MST_CLK_CFG_CC_MODE_ACK_Msk	((uint32_t)0x3U << ACFG_MST_CLK_CFG_CC_MODE_ACK_Pos)

#define ACFG_MST_CLK_CFG_QACT_POLICY_Pos	(2)
#define ACFG_MST_CLK_CFG_QACT_POLICY_Msk	((uint32_t)0x1U << ACFG_MST_CLK_CFG_QACT_POLICY_Pos)
#define ACFG_MST_CLK_CFG_QACT_POLICY_1	((uint32_t)0x0U << ACFG_MST_CLK_CFG_QACT_POLICY_Pos)
#define ACFG_MST_CLK_CFG_QACT_POLICY_2	((uint32_t)0x1U << ACFG_MST_CLK_CFG_QACT_POLICY_Pos)

#define ACFG_MST_CLK_CFG_CC_MODE_REQ_Pos	(0)
#define ACFG_MST_CLK_CFG_CC_MODE_REQ_Msk	((uint32_t)0x3U << ACFG_MST_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_MST_CLK_CFG_CC_MODE_REQ_AUTO	((uint32_t)0x0U << ACFG_MST_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_MST_CLK_CFG_CC_MODE_REQ_MANUAL	((uint32_t)0x1U << ACFG_MST_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_MST_CLK_CFG_CC_MODE_REQ_BYPASS	((uint32_t)0x2U << ACFG_MST_CLK_CFG_CC_MODE_REQ_Pos)

/* AXI Domain Bridge Slave Clock Control Register X2X_SLV_CLK_CFG */
#define ACFG_SLV_CLK_CFG_DELAY_Pos		(16)
#define ACFG_SLV_CLK_CFG_DELAY_Msk		((uint32_t)0xFFFFU << ACFG_SLV_CLK_CFG_DELAY_Pos)

#define ACFG_SLV_CLK_CFG_QFSM_STATE_Pos	(12)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_Msk	((uint32_t)0x7U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_STOPPED	((uint32_t)0x0U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_EXIT	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_RUN	((uint32_t)0x2U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_DELAY	((uint32_t)0x3U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_REQUEST	((uint32_t)0x4U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_CLK_CFG_QFSM_STATE_DENIED	((uint32_t)0x5U << ACFG_SLV_CLK_CFG_QFSM_STATE_Pos)

#define ACFG_SLV_CLK_CFG_M_QDENY_Pos	(11)
#define ACFG_SLV_CLK_CFG_M_QDENY_Msk	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_M_QDENY_Pos)

#define ACFG_SLV_CLK_CFG_M_QACCEPTN_Pos	(10)
#define ACFG_SLV_CLK_CFG_M_QACCEPTN_Msk	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_M_QACCEPTN_Pos)

#define ACFG_SLV_CLK_CFG_M_QACTIVE_Pos	(9)
#define ACFG_SLV_CLK_CFG_M_QACTIVE_Msk	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_M_QACTIVE_Pos)

#define ACFG_SLV_CLK_CFG_M_QREQN_Pos	(8)
#define ACFG_SLV_CLK_CFG_M_QREQN_Msk	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_M_QREQN_Pos)

#define ACFG_SLV_CLK_CFG_CC_MODE_ACK_Pos	(4)
#define ACFG_SLV_CLK_CFG_CC_MODE_ACK_Msk	((uint32_t)0x3U << ACFG_SLV_CLK_CFG_CC_MODE_ACK_Pos)

#define ACFG_SLV_CLK_CFG_QACT_POLICY_Pos	(2)
#define ACFG_SLV_CLK_CFG_QACT_POLICY_Msk	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_QACT_POLICY_Pos)
#define ACFG_SLV_CLK_CFG_QACT_POLICY_1	((uint32_t)0x0U << ACFG_SLV_CLK_CFG_QACT_POLICY_Pos)
#define ACFG_SLV_CLK_CFG_QACT_POLICY_2	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_QACT_POLICY_Pos)

#define ACFG_SLV_CLK_CFG_CC_MODE_REQ_Pos	(0)
#define ACFG_SLV_CLK_CFG_CC_MODE_REQ_Msk	((uint32_t)0x3U << ACFG_SLV_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_CLK_CFG_CC_MODE_REQ_AUTO	((uint32_t)0x0U << ACFG_SLV_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_CLK_CFG_CC_MODE_REQ_MANUAL	((uint32_t)0x1U << ACFG_SLV_CLK_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_CLK_CFG_CC_MODE_REQ_BYPASS	((uint32_t)0x2U << ACFG_SLV_CLK_CFG_CC_MODE_REQ_Pos)

/* AXI Domain Bridge Slave Clock Control Register X2X_SLV_CLK_CFG */
#define ACFG_SLV_PWR_CFG_DELAY_Pos		(16)
#define ACFG_SLV_PWR_CFG_DELAY_Msk		((uint32_t)0xFFFFU << ACFG_SLV_PWR_CFG_DELAY_Pos)

#define ACFG_SLV_PWR_CFG_QFSM_STATE_Pos	(12)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_Msk	((uint32_t)0x7U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_STOPPED	((uint32_t)0x0U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_EXIT	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_RUN	((uint32_t)0x2U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_DELAY	((uint32_t)0x3U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_REQUEST	((uint32_t)0x4U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)
#define ACFG_SLV_PWR_CFG_QFSM_STATE_DENIED	((uint32_t)0x5U << ACFG_SLV_PWR_CFG_QFSM_STATE_Pos)

#define ACFG_SLV_PWR_CFG_M_QDENY_Pos	(11)
#define ACFG_SLV_PWR_CFG_M_QDENY_Msk	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_M_QDENY_Pos)

#define ACFG_SLV_PWR_CFG_M_QACCEPTN_Pos	(10)
#define ACFG_SLV_PWR_CFG_M_QACCEPTN_Msk	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_M_QACCEPTN_Pos)

#define ACFG_SLV_PWR_CFG_M_QACTIVE_Pos	(9)
#define ACFG_SLV_PWR_CFG_M_QACTIVE_Msk	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_M_QACTIVE_Pos)

#define ACFG_SLV_PWR_CFG_M_QREQN_Pos	(8)
#define ACFG_SLV_PWR_CFG_M_QREQN_Msk	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_M_QREQN_Pos)

#define ACFG_SLV_PWR_CFG_CC_MODE_ACK_Pos	(4)
#define ACFG_SLV_PWR_CFG_CC_MODE_ACK_Msk	((uint32_t)0x3U << ACFG_SLV_PWR_CFG_CC_MODE_ACK_Pos)

#define ACFG_SLV_PWR_CFG_QACT_POLICY_Pos	(2)
#define ACFG_SLV_PWR_CFG_QACT_POLICY_Msk	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_QACT_POLICY_Pos)
#define ACFG_SLV_PWR_CFG_QACT_POLICY_1	((uint32_t)0x0U << ACFG_SLV_PWR_CFG_QACT_POLICY_Pos)
#define ACFG_SLV_PWR_CFG_QACT_POLICY_2	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_QACT_POLICY_Pos)

#define ACFG_SLV_PWR_CFG_CC_MODE_REQ_Pos	(0)
#define ACFG_SLV_PWR_CFG_CC_MODE_REQ_Msk	((uint32_t)0x3U << ACFG_SLV_PWR_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_PWR_CFG_CC_MODE_REQ_AUTO	((uint32_t)0x0U << ACFG_SLV_PWR_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_PWR_CFG_CC_MODE_REQ_MANUAL	((uint32_t)0x1U << ACFG_SLV_PWR_CFG_CC_MODE_REQ_Pos)
#define ACFG_SLV_PWR_CFG_CC_MODE_REQ_BYPASS	((uint32_t)0x2U << ACFG_SLV_PWR_CFG_CC_MODE_REQ_Pos)
#endif
