/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Copyright (C) Telechips Inc.
 */
#ifndef TCC_AUDIO_MAIC_HW_H
#define TCC_AUDIO_MAIC_HW_H

#define TCC_DAI_MAX_FREQ \
	(200000000)		//200MHz
#define TCC_DAI_DP_LINK_MAX_FREQ \
	(400000000)		//400MHz
#define TCC_DAI_FILTER_MAX_FREQ \
	(1200000000)	//1200MHz
#define TCC_SPDIF_MAX_FREQ \
	(200000000)		//200MHz

#define TCC_AUDIO_ADMA_OFFSET \
	(0x0000)
#define TCC_AUDIO_GIRQ_OFFSET \
	(0x0080)
#define TCC_AUDIO_DAI_OFFSET \
	(0x1000)
#define TCC_AUDIO_SPDIF_OFFSET \
	(0x2000)
#define TCC_AUDIO_PORTCFG_OFFSET \
	(0x3000)

/******  ADMA Register Offset Information(Audio Base + offset) ******/
#define TCC_ADMA_RXDADAR_OFFSET \
	(0x0000)
#define TCC_ADMA_RXDAPARAM_OFFSET \
	(0x0004)
#define TCC_ADMA_RXDATCNT_OFFSET \
	(0x0008)
#define TCC_ADMA_RXDACDAR_OFFSET \
	(0x000C)
#define TCC_ADMA_RXCDDAR_OFFSET \
	(0x0010)
#define TCC_ADMA_RXCDPARAM_OFFSET \
	(0x0014)
#define TCC_ADMA_RXCDTCNT_OFFSET \
	(0x0018)
#define TCC_ADMA_RXCDCDAR_OFFSET \
	(0x001C)
#define TCC_ADMA_RXDADARL_OFFSET \
	(0x0028)
#define TCC_ADMA_RXDACDARL_OFFSET \
	(0x002C)
#define TCC_ADMA_RXCDDARL_OFFSET \
	(0x0030)
#define TCC_ADMA_RXCDCDARL_OFFSET \
	(0x0034)
#define TCC_ADMA_TRANSCTRL_OFFSET \
	(0x0038)
#define TCC_ADMA_RPTCTRL_OFFSET \
	(0x003C)
#define TCC_ADMA_TXDASAR_OFFSET	\
	(0x0040)
#define TCC_ADMA_TXDAPARAM_OFFSET \
	(0x0044)
#define TCC_ADMA_TXDATCNT_OFFSET \
	(0x0048)
#define TCC_ADMA_TXDACSAR_OFFSET \
	(0x004C)
#define TCC_ADMA_TXSPSAR_OFFSET \
	(0x0050)
#define TCC_ADMA_TXSPPARAM_OFFSET \
	(0x0054)
#define TCC_ADMA_TXSPTCNT_OFFSET \
	(0x0058)
#define TCC_ADMA_TXSPCSAR_OFFSET \
	(0x005C)
#define TCC_ADMA_TXDASARL_OFFSET \
	(0x0068)
#define TCC_ADMA_TXDACSARL_OFFSET \
	(0x006C)
#define TCC_ADMA_TXSPSARL_OFFSET \
	(0x0070)
#define TCC_ADMA_TXSPCSARL_OFFSET \
	(0x0074)
#define TCC_ADMA_CHCTRL_OFFSET \
	(0x0078)
#define TCC_ADMA_INTSTATUS_OFFSET \
	(0x007C)
#define TCC_ADMA_GINTREQ_OFFSET \
	(0x0080)
#define TCC_ADMA_GINTSTATUS_OFFSET \
	(0x0084)
#define TCC_ADMA_TXDAADRCNT_OFFSET \
	(0x0088)
#define TCC_ADMA_RXDAADRCNT_OFFSET \
	(0x008C)
#define TCC_ADMA_TXSPADRCNT_OFFSET \
	(0x0090)
#define TCC_ADMA_RXSPADRCNT_OFFSET \
	(0x0094)
#define TCC_ADMA_TXDAADRCNTR_OFFSET \
	(0x0098)
#define TCC_ADMA_RXDAADRCNTR_OFFSET \
	(0x009C)
#define TCC_ADMA_TXSPADRCNTR_OFFSET \
	(0x00A0)
#define TCC_ADMA_RXSPADRCNTR_OFFSET \
	(0x00A4)

#define TCC_ADMA_RXDADAR1_OFFSET \
	(0x0100)
#define TCC_ADMA_RXDADAR2_OFFSET \
	(0x0104)
#define TCC_ADMA_RXDADAR3_OFFSET \
	(0x0108)
#define TCC_ADMA_RXDACAR1_OFFSET \
	(0x010C)
#define TCC_ADMA_RXDACAR2_OFFSET \
	(0x0110)
#define TCC_ADMA_RXDACAR3_OFFSET \
	(0x0114)
#define TCC_ADMA_RXDADARL1_OFFSET \
	(0x0118)
#define TCC_ADMA_RXDADARL2_OFFSET \
	(0x011C)
#define TCC_ADMA_RXDADARL3_OFFSET \
	(0x0120)
#define TCC_ADMA_RXDACARL1_OFFSET \
	(0x0124)
#define TCC_ADMA_RXDACARL2_OFFSET \
	(0x0128)
#define TCC_ADMA_RXDACARL3_OFFSET \
	(0x012C)
#define TCC_ADMA_TXDASAR1_OFFSET \
	(0x0130)
#define TCC_ADMA_TXDASAR2_OFFSET \
	(0x0134)
#define TCC_ADMA_TXDASAR3_OFFSET \
	(0x0138)
#define TCC_ADMA_TXDACSAR1_OFFSET \
	(0x013C)
#define TCC_ADMA_TXDACSAR2_OFFSET \
	(0x0140)
#define TCC_ADMA_TXDACSAR3_OFFSET \
	(0x0144)
#define TCC_ADMA_TXDADARL1_OFFSET \
	(0x0148)
#define TCC_ADMA_TXDADARL2_OFFSET \
	(0x014C)
#define TCC_ADMA_TXDADARL3_OFFSET \
	(0x0150)
#define TCC_ADMA_TXDACARL1_OFFSET \
	(0x0154)
#define TCC_ADMA_TXDACARL2_OFFSET \
	(0x0158)
#define TCC_ADMA_TXDACARL3_OFFSET \
	(0x015C)

#define TCC_ADMA_RESET_OFFSET \
	(0x0180)

/****** General Interrupt Register Offset ******/
/******   (Audio Base + 0x0080 + offset)  ******/
#define TCC_GINT_REQ_OFFSET \
	(0x0000)
#define TCC_GINT_STATUS_OFFSET \
	(0x0004)


/****** DAI Register Offset Information(Audio Base + 0x1000 + offset) ******/
#define TCC_DAI_DAMR_OFFSET		(0x0040)
#define TCC_DAI_MCCR0_OFFSET	(0x0048)
#define TCC_DAI_MCCR1_OFFSET	(0x004C)
#define TCC_DAI_DRMR_OFFSET		(0x0050)
#define TCC_DAI_DCLKDIV_OFFSET	(0x0054)

/************* 여기부터 업데이트 필요 -> */
#define TCC_MAIC_DAIF_DAMR1			(0x058)
#define TCC_MAIC_DMA0_CTRL			(0x05C)
#define TCC_MAIC_RDMA0_ADDR_LSB		(0x060)
#define TCC_MAIC_RDMA0_ADDR_MSB		(0x064)
#define TCC_MAIC_RDMA0_DATA_CFG		(0x068)
#define TCC_MAIC_WDMA0_ADDR_LSB		(0x06C)
#define TCC_MAIC_WDMA0_ADDR_MSB		(0x070)
#define TCC_MAIC_WDMA0_DATA_CFG		(0x074)
#define TCC_MAIC_AXI_TASDMA_CFG		(0x078)
#define TCC_MAIC_TAS_FIFO_THRESHOLD	(0x080)
#define TCC_MAIC_TAS_FIFO_CFG		(0x084)
#define TCC_MAIC_TAS_BIT_CONVERT	(0x088) //Not used
#define TCC_MAIC_EXT_ADDR_ADMA		(0x090)

#define FIFO_CFG_FIFO_EN_Pos \
	(31U)
#define FIFO_CFG_FIFO_EN_Msk \
	((uint32_t)1U << FIFO_CFG_FIFO_EN_Pos)
#define FIFO_CFG_FIFO_EN_DISABLE \
	((uint32_t)0U << FIFO_CFG_FIFO_EN_Pos)
#define FIFO_CFG_FIFO_EN_ENABLE \
	((uint32_t)1U << FIFO_CFG_FIFO_EN_Pos)

#define FIFO_CFG_INIT_TX_FIFO_Pos \
	(0)
#define FIFO_CFG_INIT_TX_FIFO_Msk \
	(0xFFU << FIFO_CFG_INIT_TX_FIFO_Pos)

#define FIFO_CFG_INIT_RX_FIFO_Pos \
	(16)
#define FIFO_CFG_INIT_RX_FIFO_Msk \
	((uint32_t)0x7FU << FIFO_CFG_INIT_RX_FIFO_Pos)


/****** SPDIF Register Offset Information(Audio Base + 0x2000 + offset) ******/
#define TCC_SPDIF_TX_VERSION_OFFSET \
	(0x0000)
#define TCC_SPDIF_TX_CONFIG_OFFSET \
	(0x0004)
#define TCC_SPDIF_TX_CHSTAT_OFFSET \
	(0x0008)
#define TCC_SPDIF_TX_INTMASK_OFFSET \
	(0x000C)
#define TCC_SPDIF_TX_INTSTAT_OFFSET \
	(0x0010)
#define TCC_SPDIF_TX_USERDATA_BUF_OFFSET \
	(0x0080)
#define TCC_SPDIF_TX_CHSTAT_BUF_OFFSET \
	(0x0100)
#define TCC_SPDIF_TX_SAMPLEDATA_BUF_OFFSET \
	(0x0200)
#define TCC_SPDIFTX_DMACFG_OFFSET \
	(0x0400)

#define TCC_SPDIF_RX_VER_OFFSET \
	(0x0800)
#define TCC_SPDIF_RX_CONFIG_OFFSET \
	(0x0804)
#define TCC_SPDIF_RX_SIGSTAT_OFFSET \
	(0x0808)
#define TCC_SPDIF_RX_INTMASK_OFFSET \
	(0x080C)
#define TCC_SPDIF_RX_INTSTAT_OFFSET \
	(0x0810)
#define TCC_SPDIF_RX_PHASEDET_OFFSET \
	(0x0814)
#define TCC_SPDIF_RX_CAP_CHCTRL_OFFSET \
	(0x0840)
#define TCC_SPDIF_RX_CAP_CHSTAT_OFFSET \
	(0x0840)
#define TCC_SPDIF_RX_BUF_OFFSET	\
	(0x0A00)

/*** Port Configuration Register Offset ***/
/******   (IOBUS Cfg Base + offset)  ******/
#define IOBUS_CFG_DAI_71CH_CHMUX \
	(0x005C)
#define IOBUS_CFG_DAI_SRCH_CHMUX \
	(0x0060)
#define IOBUS_CFG_SPDIF_71CH0_CHMUX \
	(0x006C)
#define IOBUS_CFG_SPDIF_71CH1_CHMUX \
	(0x0070)
#define IOBUS_CFG_SPDIF_SRCH0_CHMUX \
	(0x008C)
#define IOBUS_CFG_SPDIF_SRCH1_CHMUX \
	(0x0090)

/****** ADMA Tx/Rx Parameter, Offset:0x04, 0x14, 0x44, 0x54 ******/
#define ADMA_PARAM_ADDR_MASK_Pos \
	(8)
#define ADMA_PARAM_ADDR_MASK_Msk \
	(0xffffffU << ADMA_PARAM_ADDR_MASK_Pos)

#define ADMA_PARAM_ADDR_INCREMENT_Pos \
	(0)
#define ADMA_PARAM_ADDR_INCREMENT_Msk \
	(0xffU << ADMA_PARAM_ADDR_INCREMENT_Pos)

/****** ADMA Tx/Rx Counter, Offset:0x08, 0x18, 0x48, 0x58 ******/
#define ADMA_COUNTER_CUR_COUNT_Pos \
	(16)
#define ADMA_COUNTER_CUR_COUNT_Msk \
	(0xffff0000U)

#define ADMA_COUNTER_START_COUNT_Pos \
	(0)
#define ADMA_COUNTER_START_COUNT_Msk \
	(0xffffffffU << ADMA_COUNTER_START_COUNT_Pos)
/****** ADMA Tx/Rx Address Counter, Offset:0x88, 0x8C, 0x90, 0x94 ******/
#define ADMA_ADRCNT_MODE_Pos \
	(31)
#define ADMA_ADRCNT_MODE_Msk \
	((uint32_t)1U << ADMA_ADRCNT_MODE_Pos)
#define ADMA_ADRCNT_MODE_SMASK \
	((uint32_t)0U << ADMA_ADRCNT_MODE_Pos)
#define ADMA_ADRCNT_MODE_ADRCNT \
	((uint32_t)1U << ADMA_ADRCNT_MODE_Pos)

#define ADMA_ADRCNT_ADDR_COUNT_Pos \
	(0)
#define ADMA_ADRCNT_ADDR_COUNT_Msk \
	(0x7fffffffU << ADMA_ADRCNT_ADDR_COUNT_Pos)

/****** ADMA Transfer Control, Offset:0x38 ******/
#define ADMA_TRANCTRL_DAITX_WSIZE_Pos \
	(0U)
#define ADMA_TRANCTRL_DAITX_WSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_DAITX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_WSIZE_8 \
	((uint32_t)0U << ADMA_TRANCTRL_DAITX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_WSIZE_16 \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_WSIZE_32 \
	((uint32_t)3U << ADMA_TRANCTRL_DAITX_WSIZE_Pos)

#define ADMA_TRANCTRL_SPDIFTX_WSIZE_Pos \
	(2)
#define ADMA_TRANCTRL_SPDIFTX_WSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_SPDIFTX_WSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_WSIZE_8 \
	((uint32_t)0U << ADMA_TRANCTRL_SPDIFTX_WSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_WSIZE_16 \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_WSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_WSIZE_32 \
	((uint32_t)3U << ADMA_TRANCTRL_SPDIFTX_WSIZE_Pos)

#define ADMA_TRANCTRL_DAIRX_WSIZE_Pos \
	(4)
#define ADMA_TRANCTRL_DAIRX_WSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_DAIRX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_WSIZE_8 \
	((uint32_t)0U << ADMA_TRANCTRL_DAIRX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_WSIZE_16 \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_WSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_WSIZE_32\
	((uint32_t)3U << ADMA_TRANCTRL_DAIRX_WSIZE_Pos)

#define ADMA_TRANCTRL_CDIFRX_WSIZE_Pos \
	(6)
#define ADMA_TRANCTRL_CDIFRX_WSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_CDIFRX_WSIZE_Pos)
#define ADMA_TRANCTRL_CDIF_RX_WSIZE_8 \
	((uint32_t)0U << ADMA_TRANCTRL_CDIFRX_WSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_WSIZE_16 \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_WSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_WSIZE_32 \
	((uint32_t)3U << ADMA_TRANCTRL_CDIFRX_WSIZE_Pos)

#define ADMA_TRANCTRL_DAITX_BSIZE_Pos \
	(8)
#define ADMA_TRANCTRL_DAITX_BSIZE_Msk \
((uint32_t)3U << ADMA_TRANCTRL_DAITX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_BCYCLE_1 \
	((uint32_t)0U << ADMA_TRANCTRL_DAITX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_BCYCLE_2 \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_BCYCLE_4 \
	((uint32_t)2U << ADMA_TRANCTRL_DAITX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAITX_BCYCLE_8 \
	((uint32_t)3U << ADMA_TRANCTRL_DAITX_BSIZE_Pos)

#define ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos \
	(10)
#define ADMA_TRANCTRL_SPDIFTX_BSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_BCYCLE_1 \
	((uint32_t)0U << ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_BCYCLE_2 \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_BCYCLE_4 \
	((uint32_t)2U << ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos)
#define ADMA_TRANCTRL_SPDIFTX_BCYCLE_8 \
	((uint32_t)3U << ADMA_TRANCTRL_SPDIFTX_BSIZE_Pos)

#define ADMA_TRANCTRL_DAIRX_BSIZE_Pos \
	(12)
#define ADMA_TRANCTRL_DAIRX_BSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_DAIRX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_BCYCLE_1 \
	((uint32_t)0U << ADMA_TRANCTRL_DAIRX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_BCYCLE_2 \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_BCYCLE_4 \
	((uint32_t)2U << ADMA_TRANCTRL_DAIRX_BSIZE_Pos)
#define ADMA_TRANCTRL_DAIRX_BCYCLE_8 \
	((uint32_t)3U << ADMA_TRANCTRL_DAIRX_BSIZE_Pos)

#define ADMA_TRANCTRL_CDIFRX_BSIZE_Pos \
	(14)
#define ADMA_TRANCTRL_CDIFRX_BSIZE_Msk \
	((uint32_t)3U << ADMA_TRANCTRL_CDIFRX_BSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_BCYCLE_1 \
	((uint32_t)0U << ADMA_TRANCTRL_CDIFRX_BSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_BCYCLE_2 \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_BSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_BCYCLE_4 \
	((uint32_t)2U << ADMA_TRANCTRL_CDIFRX_BSIZE_Pos)
#define ADMA_TRANCTRL_CDIFRX_BCYCLE_8 \
	((uint32_t)3U << ADMA_TRANCTRL_CDIFRX_BSIZE_Pos)

#define ADMA_TRANCTRL_DAITX_REPEAT_Pos \
	(16)
#define ADMA_TRANCTRL_DAITX_REPEAT_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_REPEAT_Pos)
#define ADMA_TRANCTRL_DAITX_REPEAT_DISABLE \
	((uint32_t)0U << ADMA_TRANCTRL_DAITX_REPEAT_Pos)
#define ADMA_TRANCTRL_DAITX_REPEAT_ENABLE \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_REPEAT_Pos)

#define ADMA_TRANCTRL_SPDIFTXREPEAT_Pos \
	(17)
#define ADMA_TRANCTRL_SPDIFTXREPEAT_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTXREPEAT_Pos)
#define ADMA_TRANCTRL_SPDIFTXREPEAT_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_SPDIFTXREPEAT_Pos)
#define ADMA_TRANCTRL_SPDIFTXREPEAT_EN \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTXREPEAT_Pos)

#define ADMA_TRANCTRL_DAIRX_REPEAT_Pos \
	(18)
#define ADMA_TRANCTRL_DAIRX_REPEAT_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_REPEAT_Pos)
#define ADMA_TRANCTRL_DAIRX_REPEAT_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_DAIRX_REPEAT_Pos)
#define ADMA_TRANCTRL_DAIRX_REPEAT_EN \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_REPEAT_Pos)

#define ADMA_TRANCTRL_CDIFRX_REPEAT_Pos \
	(19)
#define ADMA_TRANCTRL_CDIFRX_REPEAT_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_REPEAT_Pos)
#define ADMA_TRANCTRL_CDIFRX_REPEAT_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_CDIFRX_REPEAT_Pos)
#define ADMA_TRANCTRL_CDIF_RX_REPEAT_EN \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_REPEAT_Pos)

#define ADMA_TRANCTRL_DAITX_TRIG_Pos \
	(20)
#define ADMA_TRANCTRL_DAITX_TRIG_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_TRIG_Pos)
#define ADMA_TRANCTRL_DAITX_TRIG_EDGE \
	((uint32_t)0U << ADMA_TRANCTRL_DAITX_TRIG_Pos) // TRIGGER EDGE MODE
#define ADMA_TRANCTRL_DAITX_TRIG_LEVEL \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_TRIG_Pos) // TRIGGER LEVEL MODE

#define ADMA_TRANCTRL_SPDIFTX_TRIG_Pos \
	(21)
#define ADMA_TRANCTRL_SPDIFTX_TRIG_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_TRIG_Pos)
#define ADMA_TRANCTRL_SPDIFTX_TRIG_EDGE \
	((uint32_t)0U << ADMA_TRANCTRL_SPDIFTX_TRIG_Pos) // TRIGGER EDGE MODE
#define ADMA_TRANCTRL_SPDIFTX_TRIG_LEV \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_TRIG_Pos) // TRIGGER LEVEL MODE

#define ADMA_TRANCTRL_DAIRX_TRIG_Pos \
	(22)
#define ADMA_TRANCTRL_DAIRX_TRIG_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_TRIG_Pos)
#define ADMA_TRANCTRL_DAIRX_TRIG_EDGE \
	((uint32_t)0U << ADMA_TRANCTRL_DAIRX_TRIG_Pos)
#define ADMA_TRANCTRL_DAIRX_TRIG_LEVEL \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_TRIG_Pos)

#define ADMA_TRANCTRL_CDIFRX_TRIG_Pos \
	(23)
#define ADMA_TRANCTRL_CDIFRX_TRIG_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_TRIG_Pos)
#define ADMA_TRANCTRL_CDIFRX_TRIG_EDGE	\
	((uint32_t)0U << ADMA_TRANCTRL_CDIFRX_TRIG_Pos)
#define ADMA_TRANCTRL_CDIFRX_TRIG_LEVEL \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRX_TRIG_Pos)

#define ADMA_TRANCTRL_DAITX_AHBLOCK_Pos \
	(24)
#define ADMA_TRANCTRL_DAITX_AHBLOCK_Msk\
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_DAITX_AHBLOCK_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_DAITX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_DAITX_AHBLOCK_EN \
	((uint32_t)1U << ADMA_TRANCTRL_DAITX_AHBLOCK_Pos)

#define ADMA_TRANCTRL_SPDIFTX_AHBLOCK_Pos \
	(25)
#define ADMA_TRANCTRL_SPDIFTX_AHB_LOCK_MODE_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_SPDIFTX_AHBLOCK_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_SPDIFTX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_SPDIFTX_AHBLOCK_EN	 \
	((uint32_t)1U << ADMA_TRANCTRL_SPDIFTX_AHBLOCK_Pos)

#define ADMA_TRANCTRL_DAIRX_AHBLOCK_Pos \
	(26)
#define ADMA_TRANCTRL_DAIRX_AHBLOCK_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_DAIRX_AHBLOCK_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_DAIRX_AHBLOCK_Pos)
#define ADMA_TRANCTRL_DAIRX_AHBLOCK_EN \
	((uint32_t)1U << ADMA_TRANCTRL_DAIRX_AHBLOCK_Pos)

#define ADMA_TRANCTRL_CDIFRXAHBLOCK_Pos \
	(27)
#define ADMA_TRANCTRL_CDIFRXAHBLOCK_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRXAHBLOCK_Pos)
#define ADMA_TRANCTRL_CDIFRXAHBLOCK_DIS \
	((uint32_t)0U << ADMA_TRANCTRL_CDIFRXAHBLOCK_Pos)
#define ADMA_TRANCTRL_CDIFRXAHBLOCK_EN \
	((uint32_t)1U << ADMA_TRANCTRL_CDIFRXAHBLOCK_Pos)

// ADMA TX Continuous mode
#define ADMA_TRANCTRL_TXCONTI_Pos \
	(28)
#define ADMA_TRANCTRL_TX_DMA_CONTI_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_TXCONTI_Pos)
#define ADMA_TRANCTRL_TXCONTI_STARTADDR \
	((uint32_t)0U << ADMA_TRANCTRL_TXCONTI_Pos)
#define ADMA_TRANCTRL_TXCONTI_CURADDR \
	((uint32_t)1U << ADMA_TRANCTRL_TXCONTI_Pos)

#define ADMA_TRANCTRL_RXCONTI_Pos \
	(29)
#define ADMA_TRANCTRL_RXCONTI_Msk \
	((uint32_t)1U << ADMA_TRANCTRL_RXCONTI_Pos)
#define ADMA_TRANCTRL_RXCONTI_STARTADDR \
	((uint32_t)0U << ADMA_TRANCTRL_RXCONTI_Pos)
#define ADMA_TRANCTRL_RXCONTIS_CURADDR \
	((uint32_t)1U << ADMA_TRANCTRL_RXCONTI_Pos)

#define ADMA_TRANSCTRL_HOP_COUNT_MODE_Pos \
	(30)
#define ADMA_TRANSCTRL_HOP_COUNT_MODE_Msk \
	((uint32_t)1U << ADMA_TRANSCTRL_HOP_COUNT_MODE_Pos)
#define ADMA_TRANSCTRL_HOP_COUNT_INCR_MODE \
	((uint32_t)0U << ADMA_TRANSCTRL_HOP_COUNT_MODE_Pos)
#define ADMA_TRANSCTRL_HOP_COUNT_CLEAR_MODE \
	((uint32_t)1U << ADMA_TRANSCTRL_HOP_COUNT_MODE_Pos)

/****** ADMA Repeat Control, Offset:0x3C ******/
#define ADMA_RPTCTRL_RPTCNT_Pos \
	(0)
#define ADMA_RPTCTRL_RPTCNT_Msk \
	(0xffffffffffffU << ADMA_RPTCTRL_RPTCNT_Pos)
#define ADMA_RPTCTRL_RPTCNT_INFINITE \
	((uint32_t)0U << ADMA_RPTCTRL_RPTCNT_Pos)

#define ADMA_RPTCTRL_DAI_BUFTHRES_Pos \
	(24)
#define ADMA_RPTCTRL_DAI_BUFTHRES_Msk \
	((uint32_t)15 << ADMA_RPTCTRL_DAI_BUFTHRES_Pos)

#define ADMA_RPTCTRL_IRQ_MODE_Pos \
	(31)
#define ADMA_RPTCTRL_IRQ_MODE_Msk \
	((uint32_t)1U << ADMA_RPTCTRL_IRQ_MODE_Pos)
#define ADMA_RPTCTRL_IRQ_END_REPEAT \
	((uint32_t)1U << ADMA_RPTCTRL_IRQ_MODE_Pos)
#define ADMA_RPTCTRL_IRQ_REQUEST_DMA \
	((uint32_t)0U << ADMA_RPTCTRL_IRQ_MODE_Pos)

/****** ADMA Channel Control, Offset:0x78 ******/
#define ADMA_CHCTRL_DAI_TX_IRQ_MODE_Pos \
	(0)
#define ADMA_CHCTRL_DAI_TX_IRQ_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_IRQ_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_TX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_IRQ_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_IRQ_MODE_Pos)

#define ADMA_CHCTRL_SPDIF_TX_IRQ_MODE_Pos \
	(1)
#define ADMA_CHCTRL_SPDIF_TX_IRQ_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_IRQ_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_SPDIF_TX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_IRQ_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_IRQ_MODE_Pos)

#define ADMA_CHCTRL_DAI_RX_IRQ_MODE_Pos \
	(2)
#define ADMA_CHCTRL_DAI_RX_IRQ_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_IRQ_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_RX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_IRQ_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_IRQ_MODE_Pos)

#define ADMA_CHCTRL_CDIF_RX_IRQ_MODE_Pos \
	(3)
#define ADMA_CHCTRL_CDIF_RX_IRQ_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_IRQ_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_RX_IRQ_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_IRQ_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_IRQ_MODE_Pos)

#define ADMA_CHCTRL_DAI_TX_SWAP_TYPE_Pos \
	(4)
#define ADMA_CHCTRL_DAI_TX_SWAP_TYPE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_SWAP_TYPE_Pos)
#define ADMA_CHCTRL_DAI_TX_SWAP_HALF_WORD \
	((uint32_t)0U << ADMA_CHCTRL_DAI_TX_SWAP_TYPE_Pos)
#define ADMA_CHCTRL_DAI_TX_SWAP_BYTE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_SWAP_TYPE_Pos)

// SWAP TYPE
#define ADMA_CHCTRL_SPDIFTX_SWAP_Pos \
	(5)
#define ADMA_CHCTRL_SPDIFTX_SWAP_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDIFTX_SWAP_Pos)
#define ADMA_CHCTRL_SPDIFTX_SWAP_HALFW	\
	((uint32_t)0U << ADMA_CHCTRL_SPDIFTX_SWAP_Pos) // HALF WORD
#define ADMA_CHCTRL_SPDIFTX_SWAP_BYTE \
	((uint32_t)1U << ADMA_CHCTRL_SPDIFTX_SWAP_Pos)

#define ADMA_CHCTRL_DAIRX_SWAP_Pos \
	(6)
#define ADMA_CHCTRL_DAIRX_SWAP_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAIRX_SWAP_Pos)
#define ADMA_CHCTRL_DAIRX_SWAP_HALFW \
	((uint32_t)0U << ADMA_CHCTRL_DAIRX_SWAP_Pos) // HALF WORD
#define ADMA_CHCTRL_DAIRX_SWAP_BYTE \
	((uint32_t)1U << ADMA_CHCTRL_DAIRX_SWAP_Pos)

#define ADMA_CHCTRL_CDIFRX_SWAP_Pos \
	(7)
#define ADMA_CHCTRL_CDIFRX_SWAP_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIFRX_SWAP_Pos)
#define ADMA_CHCTRL_CDIFRX_SWAP_HALFW \
	((uint32_t)0U << ADMA_CHCTRL_CDIFRX_SWAP_Pos) // HALF WORD
#define ADMA_CHCTRL_CDIFRX_SWAP_BYTE \
	((uint32_t)1U << ADMA_CHCTRL_CDIFRX_SWAP_Pos)

#define ADMA_CHCTRL_DAITX_SWAP_Pos \
	(8)
#define ADMA_CHCTRL_DAITX_SWAP_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAITX_SWAP_Pos)
#define ADMA_CHCTRL_DAITX_SWAP_DIS \
	((uint32_t)0U << ADMA_CHCTRL_DAITX_SWAP_Pos)
#define ADMA_CHCTRL_DAITX_SWAP_EN \
	((uint32_t)1U << ADMA_CHCTRL_DAITX_SWAP_Pos)

#define ADMA_CHCTRL_SPDTX_SWAP_MODE_Pos \
	(9)
#define ADMA_CHCTRL_SPDTX_SWAP_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDTX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_SWAP_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_SPDTX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_SWAP_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_SPDTX_SWAP_MODE_Pos)

#define ADMA_CHCTRL_DAI_RX_SWAP_MODE_Pos \
	(10)
#define ADMA_CHCTRL_DAI_RX_SWAP_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_SWAP_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_RX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_SWAP_ENABLE\
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_SWAP_MODE_Pos)

#define ADMA_CHCTRL_CDIF_RX_SWAP_MODE_Pos \
	(11)
#define ADMA_CHCTRL_CDIF_RX_SWAP_MODE_Msk\
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_SWAP_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_RX_SWAP_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_SWAP_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_SWAP_MODE_Pos)

#define ADMA_CHCTRL_DAI_TXD_WIDTH_Pos \
	(12)
#define ADMA_CHCTRL_DAI_TXD_WIDTH_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TXD_WIDTH_Pos)
#define ADMA_CHCTRL_DAI_TXD_WIDTH_24BIT \
	((uint32_t)0U << ADMA_CHCTRL_DAI_TXD_WIDTH_Pos)
#define ADMA_CHCTRL_DAI_TXD_WIDTH_16BIT \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TXD_WIDTH_Pos)

#define ADMA_CHCTRL_SPDIF_TXD_WIDTH_Pos \
	(13)
#define ADMA_CHCTRL_SPDIF_TXD_WIDTH_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TXD_WIDTH_Pos)
#define ADMA_CHCTRL_SPDIF_TXD_WIDTH_24BIT \
	((uint32_t)0U << ADMA_CHCTRL_SPDIF_TXD_WIDTH_Pos)
#define ADMA_CHCTRL_SPDIF_TXD_WIDTH_16BIT \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TXD_WIDTH_Pos)

#define ADMA_CHCTRL_DAI_RXD_WIDTH_Pos \
	(14)
#define ADMA_CHCTRL_DAI_RXD_WIDTH_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RXD_WIDTH_Pos)
#define ADMA_CHCTRL_DAI_RXD_WIDTH_24BIT \
	((uint32_t)0U << ADMA_CHCTRL_DAI_RXD_WIDTH_Pos)
#define ADMA_CHCTRL_DAI_RXD_WIDTH_16BIT \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RXD_WIDTH_Pos)

#define ADMA_CHCTRL_CDIF_RXD_WIDTH_Pos \
	(15)
#define ADMA_CHCTRL_CDIF_RXD_WIDTH_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RXD_WIDTH_Pos)
#define ADMA_CHCTRL_CDIF_RXD_WIDTH_24BIT \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_RXD_WIDTH_Pos)
#define ADMA_CHCTRL_CDIF_RXD_WIDTH_16BIT \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RXD_WIDTH_Pos)

#define ADMA_CHCTRL_DAI_TX_LR_MODE_Pos \
	(16)
#define ADMA_CHCTRL_DAI_TX_LR_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_LR_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_LR_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_TX_LR_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_LR_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_LR_MODE_Pos)

#define ADMA_CHCTRL_SPDIF_TX_LR_MODE_Pos \
	(17)
#define ADMA_CHCTRL_SPDIF_TX_LR_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_LR_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_LR_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_SPDIF_TX_LR_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_LR_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_LR_MODE_Pos)

#define ADMA_CHCTRL_DAI_RX_LR_MODE_Pos \
	(18)
#define ADMA_CHCTRL_DAI_RX_LR_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_LR_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_LR_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_RX_LR_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_LR_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_LR_MODE_Pos)

#define ADMA_CHCTRL_CDIF_RX_LR_MODE_Pos \
	(19)
#define ADMA_CHCTRL_CDIF_RX_LR_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_LR_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_LR_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_RX_LR_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_LR_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_LR_MODE_Pos)

#define ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos \
	(20)
#define ADMA_CHCTRL_TX_MULTI_CH_SEL_Msk \
	((uint32_t)3U << ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_TX_MULTI_CH_3_1 \
	((uint32_t)0U << ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_TX_MULTI_CH_5_1_012 \
	((uint32_t)1U << ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_TX_MULTI_CH_5_1_013 \
	((uint32_t)2U << ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_TX_MULTI_CH_7_1 \
	((uint32_t)3U << ADMA_CHCTRL_TX_MULTI_CH_SEL_Pos)

#define ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos \
	(22)
#define ADMA_CHCTRL_RX_MULTI_CH_SEL_Msk \
	((uint32_t)3U << ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_RX_MULTI_CH_3_1 \
	((uint32_t)0U << ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_RX_MULTI_CH_5_1_012 \
	((uint32_t)1U << ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_RX_MULTI_CH_5_1_013 \
	((uint32_t)2U << ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos)
#define ADMA_CHCTRL_RX_MULTI_CH_7_1 \
	((uint32_t)3U << ADMA_CHCTRL_RX_MULTI_CH_SEL_Pos)


#define ADMA_CHCTRL_DAITX_MULTI_CH_Pos \
	(24)
#define ADMA_CHCTRL_DAI_TX_MULTI_CH_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAITX_MULTI_CH_Pos)
#define ADMA_CHCTRL_DAI_TX_MULTI_CH_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAITX_MULTI_CH_Pos)
#define ADMA_CHCTRL_DAI_TX_MULTI_CH_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAITX_MULTI_CH_Pos)

#define ADMA_CHCTRL_DAIRX_MULTI_CH_Pos \
	(25)
#define ADMA_CHCTRL_DAI_RX_MULTI_CH_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAIRX_MULTI_CH_Pos)
#define ADMA_CHCTRL_DAI_RX_MULTI_CH_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAIRX_MULTI_CH_Pos)
#define ADMA_CHCTRL_DAI_RX_MULTI_CH_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAIRX_MULTI_CH_Pos)

#define ADMA_CHCTRL_CDIF_SPDIF_SEL_Pos \
	(26)
#define ADMA_CHCTRL_CDIF_SPDIF_SEL_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_SPDIF_SEL_Pos)
#define ADMA_CHCTRL_CDIF_SPDIF_SEL_CDIF \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_SPDIF_SEL_Pos)
#define ADMA_CHCTRL_CDIF_SPDIF_SEL_SPDIF \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_SPDIF_SEL_Pos)

#define ADMA_CHCTRL_DAInSPD_SAMECLK_Pos \
	(27)
#define ADMA_CHCTRL_DAInSPD_SAMECLK_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAInSPD_SAMECLK_Pos)
#define ADMA_CHCTRL_DAInSPD_SAMECLK_DIS \
	((uint32_t)0U << ADMA_CHCTRL_DAInSPD_SAMECLK_Pos)
#define ADMA_CHCTRL_DAInSPD_SAMECLK_EN \
	((uint32_t)1U << ADMA_CHCTRL_DAInSPD_SAMECLK_Pos)

#define ADMA_CHCTRL_DAI_TX_DMA_MODE_Pos \
	(28)
#define ADMA_CHCTRL_DAI_TX_DMA_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_DMA_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_DMA_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_TX_DMA_MODE_Pos)
#define ADMA_CHCTRL_DAI_TX_DMA_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_TX_DMA_MODE_Pos)

#define ADMA_CHCTRL_SPDIF_TX_DMA_MODE_Pos \
	(29)
#define ADMA_CHCTRL_SPDIF_TX_DMA_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_DMA_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_DMA_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_SPDIF_TX_DMA_MODE_Pos)
#define ADMA_CHCTRL_SPDIF_TX_DMA_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_SPDIF_TX_DMA_MODE_Pos)

#define ADMA_CHCTRL_DAI_RX_DMA_MODE_Pos	 \
	(30)
#define ADMA_CHCTRL_DAI_RX_DMA_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_DMA_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_DMA_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_DAI_RX_DMA_MODE_Pos)
#define ADMA_CHCTRL_DAI_RX_DMA_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_DAI_RX_DMA_MODE_Pos)

#define ADMA_CHCTRL_CDIF_RX_DMA_MODE_Pos \
	(31)
#define ADMA_CHCTRL_CDIF_RX_DMA_MODE_Msk \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_DMA_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_DMA_DISABLE \
	((uint32_t)0U << ADMA_CHCTRL_CDIF_RX_DMA_MODE_Pos)
#define ADMA_CHCTRL_CDIF_RX_DMA_ENABLE \
	((uint32_t)1U << ADMA_CHCTRL_CDIF_RX_DMA_MODE_Pos)

/****** ADMA Interrupt Status, Offset:0x7C ******/
#define ADMA_ISTAT_DAI_TX_MASKED_Pos \
	(0)
#define ADMA_ISTAT_DAI_TX_MASKED_Msk \
	((uint32_t)1U << ADMA_ISTAT_DAI_TX_MASKED_Pos)
#define ADMA_ISTAT_DAI_TX_MASKED_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_DAI_TX_MASKED_Pos)
#define ADMA_ISTAT_DAI_TX_MASKED_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_DAI_TX_MASKED_Pos)

#define ADMA_ISTAT_SPDIF_TX_MASKED_Pos \
	(1)
#define ADMA_ISTAT_SPDIF_TX_MASKED_Msk \
	((uint32_t)1U << ADMA_ISTAT_SPDIF_TX_MASKED_Pos)
#define ADMA_ISTAT_SPDIF_TX_MASKED_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_SPDIF_TX_MASKED_Pos)
#define ADMA_ISTAT_SPDIF_TX_MASKED_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_SPDIF_TX_MASKED_Pos)

#define ADMA_ISTAT_DAI_RX_MASKED_Pos \
	(2)
#define ADMA_ISTAT_DAI_RX_MASKED_Msk \
	((uint32_t)1U << ADMA_ISTAT_DAI_RX_MASKED_Pos)
#define ADMA_ISTAT_DAI_RX_MASKED_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_DAI_RX_MASKED_Pos)
#define ADMA_ISTAT_DAI_RX_MASKED_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_DAI_RX_MASKED_Pos)

#define ADMA_ISTAT_CDIF_RX_MASKED_Pos \
	(3)
#define ADMA_ISTAT_CDIF_RX_MASKED_Msk \
	((uint32_t)1U << ADMA_ISTAT_CDIF_RX_MASKED_Pos)
#define ADMA_ISTAT_CDIF_RX_MASKED_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_CDIF_RX_MASKED_Pos)
#define ADMA_ISTAT_CDIF_RX_MASKED_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_CDIF_RX_MASKED_Pos)

#define ADMA_ISTAT_DAI_TX_Pos \
	(4)
#define ADMA_ISTAT_DAI_TX_Msk \
	((uint32_t)1U << ADMA_ISTAT_DAI_TX_Pos)
#define ADMA_ISTAT_DAI_TX_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_DAI_TX_Pos)
#define ADMA_ISTAT_DAI_TX_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_DAI_TX_Pos)

#define ADMA_ISTAT_SPDIF_TX_Pos \
	(5)
#define ADMA_ISTAT_SPDIF_TX_Msk \
	((uint32_t)1U << ADMA_ISTAT_SPDIF_TX_Pos)
#define ADMA_ISTAT_SPDIF_TX_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_SPDIF_TX_Pos)
#define ADMA_ISTAT_SPDIF_TX_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_SPDIF_TX_Pos)

#define ADMA_ISTAT_DAI_RX_Pos \
	(6)
#define ADMA_ISTAT_DAI_RX_Msk \
	((uint32_t)1U << ADMA_ISTAT_DAI_RX_Pos)
#define ADMA_ISTAT_DAI_RX_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_DAI_RX_Pos)
#define ADMA_ISTAT_DAI_RX_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_DAI_RX_Pos)

#define ADMA_ISTAT_CDIF_RX_Pos \
	(7)
#define ADMA_ISTAT_CDIF_RX_Msk \
	((uint32_t)1U << ADMA_ISTAT_CDIF_RX_Pos)
#define ADMA_ISTAT_CDIF_RX_NOT_OCCURED \
	((uint32_t)0U << ADMA_ISTAT_CDIF_RX_Pos)
#define ADMA_ISTAT_CDIF_RX_OCCURED \
	((uint32_t)1U << ADMA_ISTAT_CDIF_RX_Pos)

/****** General Interrupt Enable Register, Offset:0x80 ******/
#define ADMA_GINT_CDIF_RX_Pos \
	(0)
#define ADMA_GINT_CDIF_RX_Msk \
	((uint32_t)1U << ADMA_GINT_CDIF_RX_Pos)
#define ADMA_GINT_DAI_RX_Pos \
	(1)
#define ADMA_GINT_DAI_RX_Msk \
	((uint32_t)1U << ADMA_GINT_DAI_RX_Pos)
#define ADMA_GINT_DAI_TX_Pos \
	(2)
#define ADMA_GINT_DAI_TX_Msk \
	((uint32_t)1U << ADMA_GINT_DAI_TX_Pos)

/****** ADMA DMA Reset, Offset:0x180 ******/
#define ADMA_RESET_DMA_TX_Pos \
	(0)
#define ADMA_RESET_DMA_TX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_TX_Pos)
#define ADMA_RESET_DMA_TX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_TX_Pos)
#define ADMA_RESET_DMA_TX_RELEASE \
	((uint32_t)0U << ADMA_RESET_DMA_TX_Pos)

#define ADMA_RESET_DMA_RX_Pos \
	(1)
#define ADMA_RESET_DMA_RX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_RX_Pos)
#define ADMA_RESET_DMA_RX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_RX_Pos)
#define ADMA_RESET_DMA_RX_RELEASE \
	((uint32_t)0U << ADMA_RESET_DMA_RX_Pos)

#define ADMA_RESET_DMA_DAI_TX_Pos \
	(2)
#define ADMA_RESET_DMA_DAI_TX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_DAI_TX_Pos)
#define ADMA_RESET_DMA_DAI_TX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_DAI_TX_Pos)
#define ADMA_RESET_DMA_DAI_TX_RELEASE \
	((uint32_t)0U << ADMA_RESET_DMA_DAI_TX_Pos)

#define ADMA_RESET_DMA_DAI_RX_Pos			(3)
#define ADMA_RESET_DMA_DAI_RX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_DAI_RX_Pos)
#define ADMA_RESET_DMA_DAI_RX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_DAI_RX_Pos)
#define ADMA_RESET_DMA_DAI_RX_RELEASE \
	((uint32_t)0U << ADMA_RESET_DMA_DAI_RX_Pos)

#define ADMA_RESET_DMA_SPDIF_TX_Pos			(4)
#define ADMA_RESET_DMA_SPDIF_TX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_SPDIF_TX_Pos)
#define ADMA_RESET_DMA_SPDIF_TX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_SPDIF_TX_Pos)
#define ADMA_RESET_DMA_SPDIF_TX_RELEASE\
	((uint32_t)0U << ADMA_RESET_DMA_SPDIF_TX_Pos)

#define ADMA_RESET_DMA_SPDIF_RX_Pos			(5)
#define ADMA_RESET_DMA_SPDIF_RX_Msk \
	((uint32_t)1U << ADMA_RESET_DMA_SPDIF_RX_Pos)
#define ADMA_RESET_DMA_SPDIF_RX_RESET \
	((uint32_t)1U << ADMA_RESET_DMA_SPDIF_RX_Pos)
#define ADMA_RESET_DMA_SPDIF_RX_RELEASE \
	((uint32_t)0U << ADMA_RESET_DMA_SPDIF_RX_Pos)

/****** DAI Digital Audio Mode Register (DAMR), Offset:0x1000 ******/
#define DAMR_DAI_RX2TX_LOOPBACK_Pos \
	(0)
#define DAMR_DAI_RX2TX_LOOPBACK_Msk \
	((uint32_t)1U << DAMR_DAI_RX2TX_LOOPBACK_Pos)
#define DAMR_DAI_RX2TX_LOOPBACK_DISABLE \
	((uint32_t)0U << DAMR_DAI_RX2TX_LOOPBACK_Pos)
#define DAMR_DAI_RX2TX_LOOPBACK_ENABLE \
	((uint32_t)1U << DAMR_DAI_RX2TX_LOOPBACK_Pos)

#define DAMR_DAI_MONITOR_MODE_Pos \
	(1)
#define DAMR_DAI_MONITOR_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_MONITOR_MODE_Pos)
#define DAMR_DAI_MONITOR_DISABLE \
	((uint32_t)0U << DAMR_DAI_MONITOR_MODE_Pos)
#define DAMR_DAI_MONITOR_ENABLE \
	((uint32_t)1U << DAMR_DAI_MONITOR_MODE_Pos)

#define DAMR_CDIF_MONITOR_MODE_Pos \
	(2)
#define DAMR_CDIF_MONITOR_MODE_Msk\
	((uint32_t)1U << DAMR_CDIF_MONITOR_MODE_Pos)
#define DAMR_CDIF_MONITOR_DISABLE \
	((uint32_t)0U << DAMR_CDIF_MONITOR_MODE_Pos)
#define DAMR_CDIF_MONITOR_ENABLE \
	((uint32_t)1U << DAMR_CDIF_MONITOR_MODE_Pos)

#define DAMR_DAI_BIT_CLK_POLARITY_Pos \
	(3)
#define DAMR_DAI_BIT_CLK_POLARITY_Msk \
	((uint32_t)1U << DAMR_DAI_BIT_CLK_POLARITY_Pos)
#define DAMR_DAI_BIT_CLK_POSITIVE \
	((uint32_t)0U << DAMR_DAI_BIT_CLK_POLARITY_Pos)
#define DAMR_DAI_BIT_CLK_NAGATIVE \
	((uint32_t)1U << DAMR_DAI_BIT_CLK_POLARITY_Pos)

#define DAMR_AUDIO_DATA_FILTER_MODE_Pos \
	(7)
#define DAMR_AUDIO_DATA_FILTER_MODE_Msk \
	((uint32_t)1U << DAMR_AUDIO_DATA_FILTER_MODE_Pos)
#define DAMR_AUDIO_DATA_FILTER_DISABLE \
	((uint32_t)0U << DAMR_AUDIO_DATA_FILTER_MODE_Pos)
#define DAMR_AUDIO_DATA_FILTER_ENABLE \
	((uint32_t)1U << DAMR_AUDIO_DATA_FILTER_MODE_Pos)

#define DAMR_DAI_FRAME_CLK_MASTER_Pos \
	(9)
#define DAMR_DAI_FRAME_CLK_MASTER_Msk \
	((uint32_t)1U << DAMR_DAI_FRAME_CLK_MASTER_Pos)
#define DAMR_DAI_FRAME_CLK_MASTER_EXT \
	((uint32_t)0U << DAMR_DAI_FRAME_CLK_MASTER_Pos)
#define DAMR_DAI_FRAME_CLK_MASTER_SYS \
	((uint32_t)1U << DAMR_DAI_FRAME_CLK_MASTER_Pos)

#define DAMR_DAI_BIT_CLK_MASTER_Pos \
	(10)
#define DAMR_DAI_BIT_CLK_MASTER_Msk \
	((uint32_t)1U << DAMR_DAI_BIT_CLK_MASTER_Pos)
#define DAMR_DAI_BIT_CLK_MASTER_EXT \
	((uint32_t)0U << DAMR_DAI_BIT_CLK_MASTER_Pos)
#define DAMR_DAI_BIT_CLK_MASTER_SYS \
	((uint32_t)1U << DAMR_DAI_BIT_CLK_MASTER_Pos)

#define DAMR_DAI_SYS_CLK_MASTER_Pos \
	(11)
#define DAMR_DAI_SYS_CLK_MASTER_Msk \
	((uint32_t)1U << DAMR_DAI_SYS_CLK_MASTER_Pos)
#define DAMR_DAI_SYS_CLK_MASTER_EXT \
	((uint32_t)0U << DAMR_DAI_SYS_CLK_MASTER_Pos)
#define DAMR_DAI_SYS_CLK_MASTER_SYS \
	((uint32_t)1U << DAMR_DAI_SYS_CLK_MASTER_Pos)

#define DAMR_DAI_SYNC_MODE_Pos \
	(12)
#define DAMR_DAI_SYNC_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_SYNC_MODE_Pos)
#define DAMR_DAI_SYNC_IIS_DSP_TDM \
	((uint32_t)0U << DAMR_DAI_SYNC_MODE_Pos)
#define DAMR_DAI_SYNC_LR_JUSTIFIED \
	((uint32_t)1U << DAMR_DAI_SYNC_MODE_Pos)

#define DAMR_DAI_RECEIVER_MODE_Pos \
	(13)
#define DAMR_DAI_RECEIVER_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_RECEIVER_MODE_Pos)
#define DAMR_DAI_RECEIVER_DISABLE \
	((uint32_t)0U << DAMR_DAI_RECEIVER_MODE_Pos)
#define DAMR_DAI_RECEIVER_ENABLE \
	((uint32_t)1U << DAMR_DAI_RECEIVER_MODE_Pos)

#define DAMR_DAI_TRANSMITTER_MODE_Pos \
	(14)
#define DAMR_DAI_TRANSMITTER_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_TRANSMITTER_MODE_Pos)
#define DAMR_DAI_TRANSMITTER_DISABLE \
	((uint32_t)0U << DAMR_DAI_TRANSMITTER_MODE_Pos)
#define DAMR_DAI_TRANSMITTER_ENABLE \
	((uint32_t)1U << DAMR_DAI_TRANSMITTER_MODE_Pos)

#define DAMR_DAI_ENABLE_MODE_Pos \
	(15)
#define DAMR_DAI_ENABLE_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_ENABLE_MODE_Pos)
#define DAMR_DAI_DISABLE \
	((uint32_t)0U << DAMR_DAI_ENABLE_MODE_Pos)
#define DAMR_DAI_ENABLE \
	((uint32_t)1U << DAMR_DAI_ENABLE_MODE_Pos)

#define DAMR_DAI_POLARITY_MODE_Pos \
	(16)
#define DAMR_DAI_POLARITY_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_POLARITY_MODE_Pos)
#define DAMR_DAI_POLARITY_NEGATIVE \
	((uint32_t)0U << DAMR_DAI_POLARITY_MODE_Pos)
#define DAMR_DAI_POLARITY_POSITIVE \
	((uint32_t)1U << DAMR_DAI_POLARITY_MODE_Pos)

#define DAMR_DAI_TX2RX_LOOPBACK_Pos \
	(17)
#define DAMR_DAI_TX2RX_LOOPBACK_Msk \
	((uint32_t)1U << DAMR_DAI_TX2RX_LOOPBACK_Pos)
#define DAMR_DAI_TX2RX_LOOPBACK_DISABLE \
	((uint32_t)0U << DAMR_DAI_TX2RX_LOOPBACK_Pos)
#define DAMR_DAI_TX2RX_LOOPBACK_ENABLE \
	((uint32_t)1U << DAMR_DAI_TX2RX_LOOPBACK_Pos)

#define DAMR_DAI_TX_SHIFT_Pos \
	(18)
#define DAMR_DAI_TX_SHIFT_Msk \
	((uint32_t)3U << DAMR_DAI_TX_SHIFT_Pos)
#define DAMR_DAI_TX_SHIFT_MSB_24 \
	((uint32_t)0U << DAMR_DAI_TX_SHIFT_Pos)
#define DAMR_DAI_TX_SHIFT_MSB_16 \
	((uint32_t)1U << DAMR_DAI_TX_SHIFT_Pos)
#define DAMR_DAI_TX_SHIFT_LSB_24 \
	((uint32_t)2U << DAMR_DAI_TX_SHIFT_Pos)
#define DAMR_DAI_TX_SHIFT_LSB_16 \
	((uint32_t)3U << DAMR_DAI_TX_SHIFT_Pos)

#define DAMR_DAI_RX_SHIFT_Pos \
	(20)
#define DAMR_DAI_RX_SHIFT_Msk \
	((uint32_t)3U << DAMR_DAI_RX_SHIFT_Pos)
#define DAMR_DAI_RX_SHIFT_MSB_24 \
	((uint32_t)0U << DAMR_DAI_RX_SHIFT_Pos)
#define DAMR_DAI_RX_SHIFT_MSB_16 \
	((uint32_t)1U << DAMR_DAI_RX_SHIFT_Pos)
#define DAMR_DAI_RX_SHIFT_LSB_24 \
	((uint32_t)2U << DAMR_DAI_RX_SHIFT_Pos)
#define DAMR_DAI_RX_SHIFT_LSB_16 \
	((uint32_t)3U << DAMR_DAI_RX_SHIFT_Pos)

#define DAMR_DAI_RXD_SIGN_EXT_MODE_Pos \
	(22)
#define DAMR_DAI_RXD_SIGN_EXT_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_RXD_SIGN_EXT_MODE_Pos)
#define DAMR_DAI_RXD_ZERO_EXT \
	((uint32_t)0U << DAMR_DAI_RXD_SIGN_EXT_MODE_Pos)
#define DAMR_DAI_RXD_SIGN_EXT \
	((uint32_t)1U << DAMR_DAI_RXD_SIGN_EXT_MODE_Pos)

#define DAMR_TX_JUSTIFIED_MODE_Pos \
	(23)
#define DAMR_TX_JUSTIFIED_MODE_Msk \
	((uint32_t)1U << DAMR_TX_JUSTIFIED_MODE_Pos)
#define DAMR_TX_JUSTIFIED_LEFT \
	((uint32_t)0U << DAMR_TX_JUSTIFIED_MODE_Pos)
#define DAMR_TX_JUSTIFIED_RIGHT \
	((uint32_t)1U << DAMR_TX_JUSTIFIED_MODE_Pos)

#define DAMR_RX_JUSTIFIED_MODE_Pos \
	(24)
#define DAMR_RX_JUSTIFIED_MODE_Msk \
	((uint32_t)1U << DAMR_RX_JUSTIFIED_MODE_Pos)
#define DAMR_RX_JUSTIFIED_LEFT \
	((uint32_t)0U << DAMR_RX_JUSTIFIED_MODE_Pos)
#define DAMR_RX_JUSTIFIED_RIGHT \
	((uint32_t)1U << DAMR_RX_JUSTIFIED_MODE_Pos)

#define DAMR_DSP_MODE_Pos \
	(25)
#define DAMR_DSP_MODE_Msk \
	((uint32_t)1U << DAMR_DSP_MODE_Pos)
#define DAMR_DSP_IIS_MODE \
	((uint32_t)0U << DAMR_DSP_MODE_Pos)
#define DAMR_DSP_OR_TDM_MODE \
	((uint32_t)1U << DAMR_DSP_MODE_Pos)

#define DAMR_DSP_WORD_LEN_Pos \
	(26)
#define DAMR_DSP_WORD_LEN_Msk \
	((uint32_t)1U << DAMR_DSP_WORD_LEN_Pos)
#define DAMR_DSP_WORD_LEN_16BIT \
	((uint32_t)1U << DAMR_DSP_WORD_LEN_Pos)
#define DAMR_DSP_WORD_LEN_24BIT	\
	((uint32_t)0U << DAMR_DSP_WORD_LEN_Pos)

#define DAMR_AUDIO_FILTER_MODE_Pos \
	(27)
#define DAMR_AUDIO_FILTER_MODE_Msk \
	((uint32_t)1U << DAMR_AUDIO_FILTER_MODE_Pos)
#define DAMR_AUDIO_FILTER_DISABLE \
	((uint32_t)0U << DAMR_AUDIO_FILTER_MODE_Pos)
#define DAMR_AUDIO_FILTER_ENABLE \
	((uint32_t)1U << DAMR_AUDIO_FILTER_MODE_Pos)

#define DAMR_MULTIPORT_MODE_Pos \
	(28)
#define DAMR_MULTIPORT_MODE_Msk \
	((uint32_t)1U << DAMR_MULTIPORT_MODE_Pos)
#define DAMR_MULTIPORT_DISABLE \
	((uint32_t)0U << DAMR_MULTIPORT_MODE_Pos)
#define DAMR_MULTIPORT_ENABLE \
	((uint32_t)1U << DAMR_MULTIPORT_MODE_Pos)

#define DAMR_DAI_BUF_THRESHOLD_MODE_Pos \
	(29)
#define DAMR_DAI_BUF_THRESHOLD_MODE_Msk \
	((uint32_t)1U << DAMR_DAI_BUF_THRESHOLD_MODE_Pos)
#define DAMR_DAI_BUF_THRESHOLD_DISABLE \
	((uint32_t)0U << DAMR_DAI_BUF_THRESHOLD_MODE_Pos)
#define DAMR_DAI_BUF_THRESHOLD_ENABLE \
	((uint32_t)1U << DAMR_DAI_BUF_THRESHOLD_MODE_Pos)

#define DAMR_LRCK_SRC_MODE_Pos \
	(30)
#define DAMR_LRCK_SRC_MODE_Msk \
	((uint32_t)1U << DAMR_LRCK_SRC_MODE_Pos)
#define DAMR_LRCK_SRC_LRCK_PAD \
	((uint32_t)0U << DAMR_LRCK_SRC_MODE_Pos)
#define DAMR_LRCK_SRC_DIRECT_MASTER \
	((uint32_t)1U << DAMR_LRCK_SRC_MODE_Pos)

#define DAMR_BCLK_SRC_MODE_Pos \
	(31)
#define DAMR_BCLK_SRC_MODE_Msk \
	((uint32_t)1U << DAMR_BCLK_SRC_MODE_Pos)
#define DAMR_BCLK_SRC_BCLK_PAD \
	((uint32_t)0U << DAMR_BCLK_SRC_MODE_Pos)
#define DAMR_BCLK_SRC_DIRECT_MASTER \
	((uint32_t)1U << DAMR_BCLK_SRC_MODE_Pos)

/****** DAI Multi Channel Control Register0 (MCCR0), Offset:0x1048 ******/
#define MCCR0_FRAME_SIZE_Pos \
	(0)
#define MCCR0_FRAME_SIZE_Msk \
	(0x1FFU << MCCR0_FRAME_SIZE_Pos)
#define MCCR0_FRAME_SIZE_32TDM_32BITSLOT \
	((uint32_t)4U << MCCR0_FRAME_SIZE_Pos)
#define MCCR0_FRAME_SIZE_32TDM_24BITSLOT \
	((uint32_t)5U << MCCR0_FRAME_SIZE_Pos)


#define MCCR0_FRAME_INVERT_Pos \
	(9)
#define MCCR0_FRAME_INVERT_Msk \
	((uint32_t)1U << MCCR0_FRAME_INVERT_Pos)
#define MCCR0_FRAME_INVERT_DISABLE \
	((uint32_t)0U << MCCR0_FRAME_INVERT_Pos)
#define MCCR0_FRAME_INVERT_ENABLE \
	((uint32_t)1U << MCCR0_FRAME_INVERT_Pos)

#define MCCR0_FRAME_CLK_DIV_Pos \
	(10)
#define MCCR0_FRAME_CLK_DIV_Msk	 \
	((uint32_t)3U << MCCR0_FRAME_CLK_DIV_Pos)
///< 32fs->fs
#define MCCR0_FRAME_CLK_DIV_32 \
	((uint32_t)0U << MCCR0_FRAME_CLK_DIV_Pos)
///< 48fs->fs
#define MCCR0_FRAME_CLK_DIV_48 \
	((uint32_t)1U << MCCR0_FRAME_CLK_DIV_Pos)
///< 64fs->fs
#define MCCR0_FRAME_CLK_DIV_64 \
	((uint32_t)2U << MCCR0_FRAME_CLK_DIV_Pos)
///< xfs->fs
#define MCCR0_FRAME_CLK_DIV_USE \
	((uint32_t)3U << MCCR0_FRAME_CLK_DIV_Pos)

#define MCCR0_TDM_BIT_CLK_DIV_Pos \
	(12)
#define MCCR0_TDM_BIT_CLK_DIV_Msk \
	((uint32_t)3U << MCCR0_TDM_BIT_CLK_DIV_Pos)
///< disable
#define MCCR0_TDM_BIT_CLK_DIV_DISABLE \
	((uint32_t)0U << MCCR0_TDM_BIT_CLK_DIV_Pos)
///< 256fs->256fs
#define MCCR0_TDM_BIT_CLK_DIV_1 \
	((uint32_t)1U << MCCR0_TDM_BIT_CLK_DIV_Pos)
///< 512fs->256fs, 256fs->128fs
#define MCCR0_TDM_BIT_CLK_DIV_2 \
	((uint32_t)2U << MCCR0_TDM_BIT_CLK_DIV_Pos)

#define MCCR0_TDM_MODE_Pos \
	(14)
#define MCCR0_TDM_MODE_Msk \
	((uint32_t)3U << MCCR0_TDM_MODE_Pos)
#define MCCR0_TDM_MODE_0 \
	((uint32_t)0U << MCCR0_TDM_MODE_Pos)
#define MCCR0_TDM_MODE_1 \
	((uint32_t)1U << MCCR0_TDM_MODE_Pos)
#define MCCR0_TDM_MODE_2 \
	((uint32_t)2U << MCCR0_TDM_MODE_Pos)

#define MCCR0_FRAME_END_POSTION_Pos \
	(16)
#define MCCR0_FRAME_END_POSTION_Msk \
	((uint32_t)0x1FFU << MCCR0_FRAME_END_POSTION_Pos)

#define MCCR0_FRAME_BEGIN_POSITION_Pos \
	(25)
#define MCCR0_FRAME_BEGIN_POSITION_Msk \
	((uint32_t)3U << MCCR0_FRAME_BEGIN_POSITION_Pos)
#define MCCR0_FRAME_BEGIN_EARLY_MODE \
	((uint32_t)0U << MCCR0_FRAME_BEGIN_POSITION_Pos)
#define MCCR0_FRAME_BEGIN_NORMAL_MODE \
	((uint32_t)1U << MCCR0_FRAME_BEGIN_POSITION_Pos)
#define MCCR0_FRAME_BEGIN_MODE2 \
	((uint32_t)2U << MCCR0_FRAME_BEGIN_POSITION_Pos)
#define MCCR0_FRAME_BEGIN_MODE3 \
	((uint32_t)3U << MCCR0_FRAME_BEGIN_POSITION_Pos)

#define MCCR0_MODE_SELECT_Pos \
	(26)
#define MCCR0_MODE_SELECT_Msk \
	((uint32_t)1U << MCCR0_MODE_SELECT_Pos)
#define MCCR0_MODE_SELECT_DISABLE \
	((uint32_t)0U << MCCR0_MODE_SELECT_Pos)
#define MCCR0_MODE_SELECT_ENABLE \
	((uint32_t)1U << MCCR0_MODE_SELECT_Pos)

#define MCCR0_CIRRUS_LATE_Pos \
	(27)
#define MCCR0_CIRRUS_LATE_Msk \
	((uint32_t)1U << MCCR0_CIRRUS_LATE_Pos)
#define MCCR0_CIRRUS_LATE_DISABLE \
	((uint32_t)0U << MCCR0_CIRRUS_LATE_Pos)
#define MCCR0_CIRRUS_LATE_ENABLE \
	((uint32_t)1U << MCCR0_CIRRUS_LATE_Pos)

#define MCCR0_DAO4_MASK_Pos \
	(27)
#define MCCR0_DAO4_MASK_Msk \
	((uint32_t)1U << MCCR0_DAO3_MASK_Pos)
#define MCCR0_DAO4_MASK_DISABLE \
	((uint32_t)0U << MCCR0_DAO3_MASK_Pos)
#define MCCR0_DAO4_MASK_ENABLE \
	((uint32_t)1U << MCCR0_DAO3_MASK_Pos)

#define MCCR0_DAO3_MASK_Pos \
	(28)
#define MCCR0_DAO3_MASK_Msk \
	((uint32_t)1U << MCCR0_DAO3_MASK_Pos)
#define MCCR0_DAO3_MASK_DISABLE \
	((uint32_t)0U << MCCR0_DAO3_MASK_Pos)
#define MCCR0_DAO3_MASK_ENABLE \
	((uint32_t)1U << MCCR0_DAO3_MASK_Pos)

#define MCCR0_DAO2_MASK_Pos \
	(29)
#define MCCR0_DAO2_MASK_Msk \
	((uint32_t)1U << MCCR0_DAO2_MASK_Pos)
#define MCCR0_DAO2_MASK_DISABLE \
	((uint32_t)0U << MCCR0_DAO2_MASK_Pos)
#define MCCR0_DAO2_MASK_ENABLE \
	((uint32_t)1U << MCCR0_DAO2_MASK_Pos)

#define MCCR0_DAO1_MASK_Pos \
	(30)
#define MCCR0_DAO1_MASK_Msk \
	((uint32_t)1U << MCCR0_DAO1_MASK_Pos)
#define MCCR0_DAO1_MASK_DISABLE \
	((uint32_t)0U << MCCR0_DAO1_MASK_Pos)
#define MCCR0_DAO1_MASK_ENABLE \
	((uint32_t)1U << MCCR0_DAO1_MASK_Pos)

#define MCCR0_DAO0_MASK_Pos \
	(31)
#define MCCR0_DAO0_MASK_Msk \
	((uint32_t)1U << MCCR0_DAO0_MASK_Pos)
#define MCCR0_DAO0_MASK_DISABLE \
	((uint32_t)0U << MCCR0_DAO0_MASK_Pos)
#define MCCR0_DAO0_MASK_ENABLE \
	((uint32_t)1U << MCCR0_DAO0_MASK_Pos)

/****** DAI Multi Channel Control Register0 (MCCR0), Offset:0x1048 ******/
#define MCCR1_VALID_END_Pos \
	(0)
#define MCCR1_VALID_END_Msk	 \
	(0x1FFU << MCCR1_VALID_END_Pos)

#define MCCR1_DAO0_PATH_Pos \
	(9)
#define MCCR1_DAO0_PATH_Msk \
	((uint32_t)1U << MCCR1_DAO0_PATH_Pos)
#define MCCR1_DAO0_PATH_ADMA \
	((uint32_t)0U << MCCR1_DAO0_PATH_Pos)
#define MCCR1_DAO0_PATH_ASRC \
	((uint32_t)1U << MCCR1_DAO0_PATH_Pos)

#define MCCR1_DAO1_PATH_Pos \
	(10)
#define MCCR1_DAO1_PATH_Msk \
	((uint32_t)1U << MCCR1_DAO1_PATH_Pos)
#define MCCR1_DAO1_PATH_ADMA \
	((uint32_t)0U << MCCR1_DAO1_PATH_Pos)
#define MCCR1_DAO1_PATH_ASRC \
	((uint32_t)1U << MCCR1_DAO1_PATH_Pos)

#define MCCR1_DAO2_PATH_Pos \
	(11)
#define MCCR1_DAO2_PATH_Msk \
	((uint32_t)1U << MCCR1_DAO2_PATH_Pos)
#define MCCR1_DAO2_PATH_ADMA \
	((uint32_t)0U << MCCR1_DAO2_PATH_Pos)
#define MCCR1_DAO2_PATH_ASRC \
	((uint32_t)1U << MCCR1_DAO2_PATH_Pos)

#define MCCR1_DAO3_PATH_Pos \
	(12)
#define MCCR1_DAO3_PATH_Msk \
	((uint32_t)1U << MCCR1_DAO3_PATH_Pos)
#define MCCR1_DAO3_PATH_ADMA \
	((uint32_t)0U << MCCR1_DAO3_PATH_Pos)
#define MCCR1_DAO3_PATH_ASRC \
	((uint32_t)1U << MCCR1_DAO3_PATH_Pos)

#define MCCR1_TDM_RX_CH_Pos \
	(13)
#define MCCR1_TDM_RX_CH_Msk \
	((uint32_t)7U << MCCR1_TDM_RX_CH_Pos)
#define MCCR1_TDM_RX_CH_2CH \
	((uint32_t)0U << MCCR1_TDM_RX_CH_Pos)
#define MCCR1_TDM_RX_CH_4CH \
	((uint32_t)1U << MCCR1_TDM_RX_CH_Pos)
#define MCCR1_TDM_RX_CH_8CH \
	((uint32_t)2U << MCCR1_TDM_RX_CH_Pos)
#define MCCR1_TDM_RX_CH_16CH \
	((uint32_t)3U << MCCR1_TDM_RX_CH_Pos)
#define MCCR1_TDM_RX_CH_32CH \
	((uint32_t)4U << MCCR1_TDM_RX_CH_Pos)

#define MCCR1_TDM_RX_FDBK_Pos \
	(17)
#define MCCR1_TDM_RX_FDBK_Msk \
	((uint32_t)1U << MCCR1_TDM_RX_FDBK_Pos)
#define MCCR1_TDM_RX_FDBK_DISABLE \
	((uint32_t)0U << MCCR1_TDM_RX_FDBK_Pos)
#define MCCR1_TDM_RX_FDBK_ENABLE \
	((uint32_t)1U << MCCR1_TDM_RX_FDBK_Pos)

#define MCCR1_TDM_RX_EARLY_Pos \
	(18)
#define MCCR1_TDM_RX_EARLY_Msk \
	((uint32_t)1U << MCCR1_TDM_RX_EARLY_Pos)
#define MCCR1_TDM_RX_EARLY_DISABLE \
	((uint32_t)0U << MCCR1_TDM_RX_EARLY_Pos)
#define MCCR1_TDM_RX_EARLY_ENABLE \
	((uint32_t)1U << MCCR1_TDM_RX_EARLY_Pos)

/****** DAI Digital Radio Mode Register (DRMR), Offset:0x1050 ******/
#define DRMR_RX_FIFO_CLEAR_Pos \
	(21)
#define DRMR_RX_FIFO_CLEAR_Msk \
	((uint32_t)1U << DRMR_RX_FIFO_CLEAR_Pos)
#define DRMR_RX_FIFO_RELEASE \
	((uint32_t)0U << DRMR_RX_FIFO_CLEAR_Pos)
#define DRMR_RX_FIFO_CLEAR \
	((uint32_t)1U << DRMR_RX_FIFO_CLEAR_Pos)

#define DRMR_TX_FIFO_CLEAR_Pos \
	(20)
#define DRMR_TX_FIFO_CLEAR_Msk \
	((uint32_t)1U << DRMR_TX_FIFO_CLEAR_Pos)
#define DRMR_TX_FIFO_RELEASE \
	((uint32_t)0U << DRMR_TX_FIFO_CLEAR_Pos)
#define DRMR_TX_FIFO_CLEAR \
	((uint32_t)1U << DRMR_TX_FIFO_CLEAR_Pos)

/****** DAI Clock Divider Register (DRMR), Offset:0x1050 ******/
#define DCLKDIV_DAI_FRAME_CLK_DIV_Pos \
	(0)
#define DCLKDIV_DAI_FRAME_CLK_DIV_Msk \
	((uint32_t)7U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< 32fs->fs
#define DCLKDIV_DAI_FRAME_CLK_DIV_32 \
	((uint32_t)0U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< 48fs->fs
#define DCLKDIV_DAI_FRAME_CLK_DIV_48 \
	((uint32_t)1U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< 64fs->fs
#define DCLKDIV_DAI_FRAME_CLK_DIV_64 \
	((uint32_t)2U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< xfs->fs
#define DCLKDIV_DAI_FRAME_CLK_DIV_X \
	((uint32_t)3U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)

///< TDM slot size: 32bit
#define DCLKDIV_DAI_TDM_SLOT_SIZE_32 \
	((uint32_t)3U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< 512fs->fs (only for DP)
#define DCLKDIV_DAI_FRAME_CLK_DIV_512 \
	((uint32_t)4U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< TDM slot size: 16bit
#define DCLKDIV_DAI_TDM_SLOT_SIZE_16 \
	((uint32_t)5U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)
///< TDM slot size: 24bit
#define DCLKDIV_DAI_TDM_SLOT_SIZE_24 \
	((uint32_t)6U << DCLKDIV_DAI_FRAME_CLK_DIV_Pos)

#define DCLKDIV_DAI_BIT_CLK_DIV_Pos \
	(8)
#define DCLKDIV_DAI_BIT_CLK_DIV_Msk \
	((uint32_t)7U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 256fs ->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_4 \
	((uint32_t)0U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 384fs ->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_6 \
	((uint32_t)1U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 512fs ->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_8 \
	((uint32_t)2U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 1024fs->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_16 \
	((uint32_t)3U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 1536fs->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_24 \
	((uint32_t)4U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 2048fs->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_32 \
	((uint32_t)5U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 3072fs->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_48 \
	((uint32_t)6U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)
///< 4096fs->64fs
#define DCLKDIV_DAI_BIT_CLK_DIV_64 \
	((uint32_t)7U << DCLKDIV_DAI_BIT_CLK_DIV_Pos)

/****** Digital Audio Mode Register1 (DAMR1), Offset:0x1058 ******/
#define TCC_MAIC_DAMR1_TAS_EN_Pos				(31)
#define TCC_MAIC_DAMR1_TAS_EN_MsK				((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_EN_Pos)
#define TCC_MAIC_DAMR1_TAS_EN_ENABLE			((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_EN_Pos)
#define TCC_MAIC_DAMR1_TAS_EN_DISABLE			((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_EN_Pos)

#define TCC_MAIC_DAMR1_TAS_LOOP_Pos				(30)
#define TCC_MAIC_DAMR1_TAS_LOOP_MsK				((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_LOOP_Pos)
#define TCC_MAIC_DAMR1_TAS_LOOP_ENABLE			((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_LOOP_Pos)
#define TCC_MAIC_DAMR1_TAS_LOOP_DISABLE			((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_LOOP_Pos)

#define TCC_MAIC_DAMR1_TAS_SEL_Pos				(29)
#define TCC_MAIC_DAMR1_TAS_SEL_MsK				((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_SEL_Pos)
#define TCC_MAIC_DAMR1_TAS_SEL_ADMA				((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_SEL_Pos)
#define TCC_MAIC_DAMR1_TAS_SEL_TAS				((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_SEL_Pos)

#define TCC_MAIC_DAMR1_TAS_TCHVLD_Pos			(26)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_MsK			((uint32_t)0x7U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_NA			((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_TAS_2CH		((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_TAS_4CH		((uint32_t)0x2U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_TAS_8CH		((uint32_t)0x3U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_TCHVLD_TAS_16CH		((uint32_t)0x4U << TCC_MAIC_DAMR1_TAS_TCHVLD_Pos)

#define TCC_MAIC_DAMR1_TAS_RCHVLD_Pos			(23)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_MsK			((uint32_t)0x7U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_NA			((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_TAS_2CH		((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_TAS_4CH		((uint32_t)0x2U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_TAS_8CH		((uint32_t)0x3U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)
#define TCC_MAIC_DAMR1_TAS_RCHVLD_TAS_16CH		((uint32_t)0x4U << TCC_MAIC_DAMR1_TAS_RCHVLD_Pos)

#define TCC_MAIC_DAMR1_TAS_TX_CLR_Pos			(20)
#define TCC_MAIC_DAMR1_TAS_TX_CLR_MsK			((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_TX_CLR_Pos)
#define TCC_MAIC_DAMR1_TAS_TX_CLR_ENABLE		((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_TX_CLR_Pos)
#define TCC_MAIC_DAMR1_TAS_TX_CLR_DISABLE		((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_TX_CLR_Pos)

#define TCC_MAIC_DAMR1_TAS_RX_CLR_Pos			(19)
#define TCC_MAIC_DAMR1_TAS_RX_CLR_MsK			((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_RX_CLR_Pos)
#define TCC_MAIC_DAMR1_TAS_RX_CLR_ENABLE		((uint32_t)0x1U << TCC_MAIC_DAMR1_TAS_RX_CLR_Pos)
#define TCC_MAIC_DAMR1_TAS_RX_CLR_DISABLE		((uint32_t)0x0U << TCC_MAIC_DAMR1_TAS_RX_CLR_Pos)

#define TCC_MAIC_DAMR1_32MOD_Pos				(0)
#define TCC_MAIC_DAMR1_32MOD_MsK				((uint32_t)0x1U << TCC_MAIC_DAMR1_32MOD_Pos)
#define TCC_MAIC_DAMR1_32MOD_ENABLE				((uint32_t)0x1U << TCC_MAIC_DAMR1_32MOD_Pos)
#define TCC_MAIC_DAMR1_32MOD_DISABLE			((uint32_t)0x0U << TCC_MAIC_DAMR1_32MOD_Pos)


/****** Extend address for ADMA, Offset:0x1090 ******/
#define TCC_MAIC_EXT_ADDR_Pos					(2)
#define TCC_MAIC_EXT_ADDR_Msk					((uint32_t)0xFU << TCC_MAIC_EXT_ADDR_Pos)

/****** SPDIF Tx Version, Offset:0x00 ******/
#define SPDIF_TX_VERSION_VER_Pos \
	(0)
#define SPDIF_TX_VERSION_VER_Msk \
	((uint32_t)0xfU << SPDIF_TX_VERSION_VER_Pos)

#define SPDIF_TX_VERSION_DATA_WIDTH_Pos \
	(4)
#define SPDIF_TX_VERSION_DATA_WIDTH_Msk \
	((uint32_t)0x1U << SPDIF_TX_VERSION_DATA_WIDTH_Pos)

#define SPDIF_TX_VERSION_ADDRWIDTH_Pos \
	(5)
#define SPDIF_TX_VERSION_ADDRWIDTH_Msk \
	((uint32_t)0x3fU << SPDIF_TX_VERSION_ADDRWIDTH_Pos)

#define SPDIFTX_VERS_USERDATA_BUF_Pos \
	(11)
#define SPDIF_TX_VERSION_USER_DATA_BUF_Msk \
	((uint32_t)0x1U << SPDIFTX_VERS_USERDATA_BUF_Pos)

#define SPDIF_TX_VERSION_CHSTAT_BUF_Pos \
	(12)
#define SPDIF_TX_VERSION_CHSTAT_BUF_Msk \
	((uint32_t)0x1U << SPDIF_TX_VERSION_CHSTAT_BUF_Pos)

/****** SPDIF Tx Config, Offset:0x04 ******/
#define SPDIF_TX_CONFIG_TX_ENABLE_Pos \
	(0)
#define SPDIF_TX_CONFIG_TX_ENABLE_Msk \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_TX_ENABLE_Pos)
#define SPDIF_TX_CONFIG_TX_ENABLE \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_TX_ENABLE_Pos)
#define SPDIF_TX_CONFIG_TX_DISABLE \
	((uint32_t)0x0U << SPDIF_TX_CONFIG_TX_ENABLE_Pos)

#define SPDIF_TX_CONFIG_DATA_VALID_Pos \
	(1)
#define SPDIF_TX_CONFIG_DATA_VALID_Msk \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_DATA_VALID_Pos)
#define SPDIF_TX_CONFIG_DATA_VALID_ENABLE \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_DATA_VALID_Pos)
#define SPDIF_TX_CONFIG_DATA_VALID_DISABLE \
	((uint32_t)0x0U << SPDIF_TX_CONFIG_DATA_VALID_Pos)

#define SPDIF_TX_CONFIG_IRQ_ENABLE_Pos \
	(2)
#define SPDIF_TX_CONFIG_IRQ_ENABLE_Msk \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_IRQ_ENABLE_Pos)
#define SPDIF_TX_CONFIG_IRQ_ENABLE \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_IRQ_ENABLE_Pos)
#define SPDIF_TX_CONFIG_IRQ_DISABLE \
	((uint32_t)0x0U << SPDIF_TX_CONFIG_IRQ_ENABLE_Pos)

#define SPDIF_TX_CONFIG_CHSTAT_EN_Pos \
	(4)
#define SPDIF_TX_CONFIG_CHSTAT_EN_Msk \
	((uint32_t)0x3U << SPDIF_TX_CONFIG_CHSTAT_EN_Pos)
#define SPDIF_TX_CONFIG_FROM_TXCHSTAT \
	((uint32_t)0x0U << SPDIF_TX_CONFIG_CHSTAT_EN_Pos)
#define SPDIF_TX_CONFIG_FROM_CHSTAT0 \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_CHSTAT_EN_Pos)
#define SPDIF_TX_CONFIG_FROM_CHSTAT1 \
	((uint32_t)0x2U << SPDIF_TX_CONFIG_CHSTAT_EN_Pos)

#define SPDIF_TX_CONFIG_UDATA_EN_Pos \
	(6)
#define SPDIF_TX_CONFIG_UDATA_EN_Msk \
	((uint32_t)0x3U << SPDIF_TX_CONFIG_UDATA_EN_Pos)
#define SPDIF_TX_CONFIG_UDATA_ZERO \
	((uint32_t)0x0U << SPDIF_TX_CONFIG_UDATA_EN_Pos)
#define SPDIF_TX_CONFIG_FROM_UDATA0 \
	((uint32_t)0x1U << SPDIF_TX_CONFIG_UDATA_EN_Pos)
#define SPDIF_TX_CONFIG_FROM_UDATA1 \
	((uint32_t)0x2U << SPDIF_TX_CONFIG_UDATA_EN_Pos)

#define SPDIF_TX_CONFIG_RATIO_Pos \
	(8)
#define SPDIF_TX_CONFIG_RATIO_Msk \
	((uint32_t)0xffU << SPDIF_TX_CONFIG_RATIO_Pos)

#define SPDIF_TX_CONFIG_MODE_Pos \
	(20)
#define SPDIF_TX_CONFIG_MODE_Msk \
	((uint32_t)0xfU << SPDIF_TX_CONFIG_MODE_Pos)

/****** SPDIF Tx ChStat, Offset:0x08 ******/
#define SPDIF_TX_CHSTAT_FORMAT_Pos \
	(0)
#define SPDIF_TX_CHSTAT_FORMAT_Msk \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_FORMAT_Pos)
#define SPDIF_TX_CHSTAT_FORMAT_AUDIO \
	((uint32_t)0x0U << SPDIF_TX_CHSTAT_FORMAT_Pos)
#define SPDIF_TX_CHSTAT_FORMAT_DATA \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_FORMAT_Pos)

#define SPDIF_TX_CHSTAT_COPYRIGHT_Pos \
	(1)
#define SPDIF_TX_CHSTAT_COPYRIGHT_Msk \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_COPYRIGHT_Pos)
#define SPDIF_TX_CHSTAT_COPY_INHIBITED \
	((uint32_t)0x0U << SPDIF_TX_CHSTAT_COPYRIGHT_Pos)
#define SPDIF_TX_CHSTAT_COPY_PERMITTED \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_COPYRIGHT_Pos)

#define SPDIF_TX_CHSTAT_PREEMPHASIS_Pos \
	(2)
#define SPDIF_TX_CHSTAT_PREEMPHASIS_Msk \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_PREEMPHASIS_Pos)
#define SPDIF_TX_CHSTAT_PREEMPHASIS_NONE \
	((uint32_t)0x0U << SPDIF_TX_CHSTAT_PREEMPHASIS_Pos)
#define SPDIF_TX_CHSTAT_PREEMPHASIS_50_15us \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_PREEMPHASIS_Pos)

#define SPDIF_TX_CHSTAT_STATUS_GEN_Pos \
	(3)
#define SPDIF_TX_CHSTAT_STATUS_GEN_Msk \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_STATUS_GEN_Pos)
#define SPDIF_TX_CHSTAT_STATUS_NO_INDICATION \
	((uint32_t)0x0U << SPDIF_TX_CHSTAT_STATUS_GEN_Pos)
#define SPDIF_TX_CHSTAT_STATUS_PRE_RECORDED \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_STATUS_GEN_Pos)

#define SPDIF_TX_CHSTAT_FREQ_Pos \
	(6)
#define SPDIF_TX_CHSTAT_FREQ_Msk \
	((uint32_t)0x3U << SPDIF_TX_CHSTAT_FREQ_Pos)
#define SPDIF_TX_CHSTAT_FREQ_44100 \
	((uint32_t)0x0U << SPDIF_TX_CHSTAT_FREQ_Pos)
#define SPDIF_TX_CHSTAT_FREQ_48000 \
	((uint32_t)0x1U << SPDIF_TX_CHSTAT_FREQ_Pos)
#define SPDIF_TX_CHSTAT_FREQ_32000 \
	((uint32_t)0x2U << SPDIF_TX_CHSTAT_FREQ_Pos)
#define SPDIF_TX_CHSTAT_FREQ_SRC \
	((uint32_t)0x3U << SPDIF_TX_CHSTAT_FREQ_Pos)

/****** SPDIF Tx INTMASK, Offset:0x0C ******/
#define SPDIFTX_INTMASK_LDATA_BUFEMP_Pos \
	(1)
#define SPDIFTX_INTMASK_LDATA_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTMASK_LDATA_BUFEMP_Pos)

#define SPDIFTX_INTMASK_HDATA_BUFEMP_Pos \
	(2)
#define SPDIFTX_INTMASK_HDATA_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTMASK_HDATA_BUFEMP_Pos)

#define SPDIFTX_INTMASK_LCH_BUFEMP_Pos \
	(3)
#define SPDIFTX_INTMASK_LCH_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTMASK_LCH_BUFEMP_Pos)

#define SPDIFTX_INTMASK_HCH_BUFEMP_Pos \
	(4)
#define SPDIFTX_INTMASK_HCH_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTMASK_HCH_BUFEMP_Pos)

/****** SPDIF Tx INTSTAT, Offset:0x10 ******/
#define SPDIFTX_INTSTAT_LDATA_BUFEMP_Pos \
	(1)
#define SPDIFTX_INTSTAT_LDATA_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTSTAT_LDATA_BUFEMP_Pos)

#define SPDIFTX_INTSTAT_HDATA_BUFEMP_Pos \
	(2)
#define SPDIFTX_INTSTAT_HDATA_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTSTAT_HDATA_BUFEMP_Pos)

#define SPDIFTX_INTSTAT_LCH_BUFEMP_Pos \
	(3)
#define SPDIFTX_INTSTAT_LCH_BUFEMP_Msk	\
	((uint32_t)0x1U << SPDIFTX_INTSTAT_LCH_BUFEMP_Pos)

#define SPDIFTX_INTSTAT_HCH_BUFEMP_Pos \
	(4)
#define SPDIFTX_INTSTAT_HCH_BUFEMP_Msk \
	((uint32_t)0x1U << SPDIFTX_INTSTAT_HCH_BUFEMP_Pos)

/****** SPDIF Tx USERDATA_BUF, Offset:0x80~DC ******/
#define SPDIFTX_UDATA_BUF_COUNT \
	(24U)
#define SPDIFTX_UDATA_BUF_ACH_Pos \
	(0)
#define SPDIFTX_UDATA_BUF_ACH_Msk \
	((uint32_t)0xffU << SPDIFTX_UDATA_BUF_ACH_Pos)

#define SPDIFTX_UDATA_BUF_BCH_Pos \
	(8)
#define SPDIFTX_UDATA_BUF_BCH_Msk \
	((uint32_t)0xffU << SPDIFTX_UDATA_BUF_BCH_Pos)

/****** SPDIF Tx CHSTAT_BUF, Offset:0x100~15C ******/
#define SPDIF_TX_CHSTAT_BUF_COUNT \
	(24U)
#define SPDIF_TX_CHSTAT_BUF_CHANNEL_A_Pos \
	(0)
#define SPDIF_TX_CHSTAT_BUF_CHANNEL_A_Msk \
	((uint32_t)0xffU << SPDIF_TX_CHSTAT_BUF_CHANNEL_A_Pos)

#define SPDIF_TX_CHSTAT_BUF_CHANNEL_B_Pos \
	(8)
#define SPDIF_TX_CHSTAT_BUF_CHANNEL_B_Msk \
	((uint32_t)0xffU << SPDIF_TX_CHSTAT_BUF_CHANNEL_B_Pos)

/****** SPDIF Tx SAMPLEDATA_BUF, Offset:0x200~3FC ******/
#define SPDIFTX_SDATA_BUF_COUNT \
	(16U)
#define SPDIFTX_SDATA_BUF_LOW16B_Pos \
	(0)
#define SPDIFTX_SDATA_BUF_LOW16B_Msk \
	(0xffffU << SPDIFTX_SDATA_BUF_LOW16B_Pos)

#define SPDIFTX_SDATA_BUF_HIGH8B_Pos \
	(16)
#define SPDIFTX_SDATA_BUF_HIGH8B_Msk \
	(0xffU << SPDIFTX_SDATA_BUF_HIGH8B_Pos)


/****** SPDIF Tx SAMPLEDATA_BUF, Offset:0x400 ******/
#define SPDIFTX_DMACFG_FIFO_THRES_Pos \
	(0)
#define SPDIFTX_DMACFG_FIFO_THRES_Msk \
	((uint32_t)0xfU << SPDIFTX_DMACFG_FIFO_THRES_Pos)

#define SPDIFTX_DMACFG_FIFO_CLEAR_Pos \
	(7)
#define SPDIFTX_DMACFG_FIFO_CLEAR_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_FIFO_CLEAR_Pos)
#define SPDIFTX_DMACFG_FIFO_CLEAR_ENABLE \
	((uint32_t)0x1U << SPDIFTX_DMACFG_FIFO_CLEAR_Pos)
#define SPDIFTX_DMACFG_FIFO_CLEAR_DISABLE \
	((uint32_t)0x0U << SPDIFTX_DMACFG_FIFO_CLEAR_Pos)

#define SPDIFTX_DMACFG_AMODE0_Pos \
	(8)
#define SPDIFTX_DMACFG_AMODE0_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_AMODE0_Pos)
#define SPDIFTX_DMACFG_AMODE0_ENABLE \
	((uint32_t)0x1U << SPDIFTX_DMACFG_AMODE0_Pos)
#define SPDIFTX_DMACFG_AMODE0_DISABLE \
	((uint32_t)0x0U << SPDIFTX_DMACFG_AMODE0_Pos)

#define SPDIFTX_DMACFG_AMODE1_Pos \
	(9)
#define SPDIFTX_DMACFG_AMODE1_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_AMODE1_Pos)
#define SPDIFTX_DMACFG_AMODE1_ENABLE \
	((uint32_t)0x1U << SPDIFTX_DMACFG_AMODE1_Pos)
#define SPDIFTX_DMACFG_AMODE1_DISABLE \
	((uint32_t)0x0U << SPDIFTX_DMACFG_AMODE1_Pos)

#define SPDIFTX_DMACFG_SDATA_DMAREQ_Pos \
	(10)
#define SPDIFTX_DMACFG_SDATA_DMAREQ_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_SDATA_DMAREQ_Pos)
#define SPDIFTX_DMACFG_SDATA_DMAREQ_EN \
	((uint32_t)0x1U << SPDIFTX_DMACFG_SDATA_DMAREQ_Pos)
#define SPDIFTX_DMACFG_SDATA_DMAREQ_DIS \
	((uint32_t)0x0U << SPDIFTX_DMACFG_SDATA_DMAREQ_Pos)

#define SPDIFTX_DMACFG_UDATA_DMAREQ_Pos \
	(11)
#define SPDIFTX_DMACFG_UDATA_DMAREQ_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_UDATA_DMAREQ_Pos)
#define SPDIFTX_DMACFG_UDATA_DMAREQ_EN \
	((uint32_t)0x1U << SPDIFTX_DMACFG_UDATA_DMAREQ_Pos)
#define SPDIFTX_DMACFG_UDATA_DMAREQ_DIS \
	((uint32_t)0x0U << SPDIFTX_DMACFG_UDATA_DMAREQ_Pos)

#define SPDIFTX_DMACFG_READADDR_MODE_Pos \
	(12)
#define SPDIFTX_DMACFG_READADDR_MODE_Msk \
	((uint32_t)0x3U << SPDIFTX_DMACFG_READADDR_MODE_Pos)
#define SPDIFTX_DMACFG_READADDR_24BIT \
	((uint32_t)0x0U << SPDIFTX_DMACFG_READADDR_MODE_Pos)
#define SPDIFTX_DMACFG_READADDR_24BIT_LR \
	((uint32_t)0x1U << SPDIFTX_DMACFG_READADDR_MODE_Pos)
#define SPDIFTX_DMACFG_READADDR_16BIT \
	((uint32_t)0x2U << SPDIFTX_DMACFG_READADDR_MODE_Pos)
#define SPDIFTX_DMACFG_READADDR_16BIT_LR \
	((uint32_t)0x3U << SPDIFTX_DMACFG_READADDR_MODE_Pos)

#define SPDIFTX_DMACFG_SWAP_Pos \
	(14)
#define SPDIFTX_DMACFG_SWAP_Msk \
	((uint32_t)0x1U << SPDIFTX_DMACFG_SWAP_Pos)
#define SPDIFTX_DMACFG_SWAP_DISABLE \
	((uint32_t)0x0U << SPDIFTX_DMACFG_SWAP_Pos)
#define SPDIFTX_DMACFG_SWAP_ENABLE \
	((uint32_t)0x1U << SPDIFTX_DMACFG_SWAP_Pos)

#define SPDIFTX_DMACFG_VCNT_Pos \
	(16)
#define SPDIFTX_DMACFG_VCNT_Msk \
	((uint32_t)0x1fU << SPDIFTX_DMACFG_VCNT_Pos)

/****** SPDIF Rx Version, Offset:0x800 ******/
#define SPDIF_RX_VER_VER_Pos \
	(0)
#define SPDIF_RX_VER_VER_Msk \
	((uint32_t)0xfU << SPDIF_RX_VER_VER_Pos)

#define SPDIF_RX_VER_DATA_WIDTH_Pos \
	(4)
#define SPDIF_RX_VER_DATA_WIDTH_Msk \
	((uint32_t)0x1U << SPDIF_RX_VER_DATA_WIDTH_Pos)
#define SPDIF_RX_VER_DATA_WIDTH_16BIT \
	((uint32_t)0x0U << SPDIF_RX_VER_DATA_WIDTH_Pos)
#define SPDIF_RX_VER_DATA_WIDTH_24BIT \
	((uint32_t)0x1U << SPDIF_RX_VER_DATA_WIDTH_Pos)

#define SPDIF_RX_VER_ADDR_WIDTH_Pos \
	(5)
#define SPDIF_RX_VER_ADDR_WIDTH_Msk \
	((uint32_t)0x7fU << SPDIF_RX_VER_ADDR_WIDTH_Pos)

#define SPDIF_RX_VER_BUF_AVAIL_BIT_Pos \
	(16)
#define SPDIF_RX_VER_BUF_AVAIL_BIT_Msk \
	((uint32_t)0xfU << SPDIF_RX_VER_BUF_AVAIL_BIT_Pos)

/****** SPDIF Rx Config, Offset:0x804 ******/
#define SPDIF_RX_CONFIG_RX_ENABLE_Pos \
	(0)
#define SPDIF_RX_CONFIG_RX_ENABLE_Msk \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_RX_ENABLE_Pos)
#define SPDIF_RX_CONFIG_RX_ENABLE \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_RX_ENABLE_Pos)
#define SPDIF_RX_CONFIG_RX_DISABLE \
	((uint32_t)0x0U << SPDIF_RX_CONFIG_RX_ENABLE_Pos)

#define SPDIF_RX_CONFIG_STORED_DATA_Pos \
	(1)
#define SPDIF_RX_CONFIG_STORED_DATA_Msk \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_STORED_DATA_Pos)
#define SPDIF_RX_CONFIG_STORED_NO_DATA \
	((uint32_t)0x0U << SPDIF_RX_CONFIG_STORED_DATA_Pos)
#define SPDIF_RX_CONFIG_STORED_DATA \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_STORED_DATA_Pos)

#define SPDIF_RX_CONFIG_IRQ_ENABLE_Pos \
	(2)
#define SPDIF_RX_CONFIG_IRQ_ENABLE_Msk \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_IRQ_ENABLE_Pos)
#define SPDIF_RX_CONFIG_IRQ_ENABLE \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_IRQ_ENABLE_Pos)
#define SPDIF_RX_CONFIG_IRQ_DISABLE \
	((uint32_t)0x0U << SPDIF_RX_CONFIG_IRQ_ENABLE_Pos)

#define SPDIF_RX_CONFIG_HOLD_CH_Pos (3)
#define SPDIF_RX_CONFIG_HOLD_CH_Msk \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_HOLD_CH_Pos)
#define SPDIF_RX_CONFIG_HOLD_CH_A \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_HOLD_CH_Pos)
#define SPDIF_RX_CONFIG_HOLD_CH_B \
	((uint32_t)0x0U << SPDIF_RX_CONFIG_HOLD_CH_Pos)

#define SPDIFRX_CONF_STR_VALID_TYPE_Pos \
	(4)
#define SPDIFRX_CONF_STR_VALID_TYPE_Msk \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_VALID_TYPE_Pos)
#define SPDIFRX_CONF_STR_VALID_REGARDLESS \
	((uint32_t)0x0U << SPDIFRX_CONF_STR_VALID_TYPE_Pos)
#define SPDIFRX_CONF_STR_VALID_ONLY \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_VALID_TYPE_Pos)

#define SPDIFRX_CONF_STR_VALID_BIT_Pos \
	(16)
#define SPDIFRX_CONF_STR_VALID_BIT_Msk \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_VALID_BIT_Pos)
#define SPDIFRX_CONF_STR_VALID_BIT_DIS \
	((uint32_t)0x0U << SPDIFRX_CONF_STR_VALID_BIT_Pos)
#define SPDIFRX_CONF_STR_VALID_BIT_EN \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_VALID_BIT_Pos)

#define SPDIFRX_CONF_STR_USERDATA_Pos \
	(17)
#define SPDIFRX_CONF_STR_USERDATA_Msk \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_USERDATA_Pos)
#define SPDIFRX_CONF_STR_USERDATA_DIS \
	((uint32_t)0x0U << SPDIFRX_CONF_STR_USERDATA_Pos)
#define SPDIFRX_CONF_STR_USERDATA_EN \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_USERDATA_Pos)

#define SPDIFRX_CONF_STR_STATUS_BIT_Pos (18)
#define SPDIFRX_CONF_STR_STATUS_BIT_Msk \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_STATUS_BIT_Pos)
#define SPDIFRX_CONF_STR_STATUS_BIT_DIS \
	((uint32_t)0x0U << SPDIFRX_CONF_STR_STATUS_BIT_Pos)
#define SPDIFRX_CONF_STR_STATUS_BIT_EN \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_STATUS_BIT_Pos)

#define SPDIFRX_CONF_STR_PARITY_BIT_Pos (19)
#define SPDIFRX_CONF_STR_PARITY_BIT_Msk \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_PARITY_BIT_Pos)
#define SPDIFRX_CONF_STR_PARITY_BIT_DIS \
	((uint32_t)0x0U << SPDIFRX_CONF_STR_PARITY_BIT_Pos)
#define SPDIFRX_CONF_STR_PARITY_BIT_EN \
	((uint32_t)0x1U << SPDIFRX_CONF_STR_PARITY_BIT_Pos)

#define SPDIF_RX_CONFIG_MODE_Pos \
	(20)
#define SPDIF_RX_CONFIG_MODE_Msk \
	((uint32_t)0xfU << SPDIF_RX_CONFIG_MODE_Pos)

#define SPDIF_RX_CONFIG_BLK_MARK_Pos \
	(24)
#define SPDIF_RX_CONFIG_BLK_MARK_Msk \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_BLK_MARK_Pos)
#define SPDIF_RX_CONFIG_BLK_MARK_DIS \
	((uint32_t)0x0U << SPDIF_RX_CONFIG_BLK_MARK_Pos)
#define SPDIF_RX_CONFIG_BLK_MARK_EN \
	((uint32_t)0x1U << SPDIF_RX_CONFIG_BLK_MARK_Pos)

/****** SPDIF Rx Signal Status, Offset:0x808 ******/
#define SPDIF_RX_SIGSTAT_LOCK_Pos \
	(0)
#define SPDIF_RX_SIGSTAT_LOCK_Msk \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_LOCK_Pos)
#define SPDIF_RX_SIGSTAT_LOCKED \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_LOCK_Pos)
#define SPDIF_RX_SIGSTAT_NO_LOCKED \
	((uint32_t)0x0U << SPDIF_RX_SIGSTAT_LOCK_Pos)

#define SPDIF_RX_SIGSTAT_FORMAT_Pos \
	(1)
#define SPDIF_RX_SIGSTAT_FORMAT_Msk \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_FORMAT_Pos)
#define SPDIF_RX_SIGSTAT_FORMAT_PROFESS \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_FORMAT_Pos)
#define SPDIF_RX_SIGSTAT_FORMAT_CONSUME \
	((uint32_t)0x0U << SPDIF_RX_SIGSTAT_FORMAT_Pos)

#define SPDIF_RX_SIGSTAT_DATA_TYPE_Pos \
	(2)
#define SPDIF_RX_SIGSTAT_DATA_TYPE_Msk \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_DATA_TYPE_Pos)
#define SPDIF_RX_SIGSTAT_DATA_TYPE_AUDIO \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_DATA_TYPE_Pos)
#define SPDIF_RX_SIGSTAT_DATA_TYPE_NON_AUDIO \
	((uint32_t)0x0U << SPDIF_RX_SIGSTAT_DATA_TYPE_Pos)

#define SPDIF_RX_SIGSTAT_EMPH_Pos \
	(3)
#define SPDIF_RX_SIGSTAT_EMPH_Msk \
	((uint32_t)0x7U << SPDIF_RX_SIGSTAT_EMPH_Pos)

#define SPDIF_RX_SIGSTAT_COPY_INFO_Pos \
	(6)
#define SPDIF_RX_SIGSTAT_COPY_INFO_Msk \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_COPY_INFO_Pos)
#define SPDIF_RX_SIGSTAT_COPY_PERMITTED \
	((uint32_t)0x1U << SPDIF_RX_SIGSTAT_COPY_INFO_Pos)
#define SPDIF_RX_SIGSTAT_COPY_INHIBITED \
	((uint32_t)0x0U << SPDIF_RX_SIGSTAT_COPY_INFO_Pos)

/****** SPDIF Rx INTMASK, Offset:0x80C ******/
#define SPDRX_INTMASK_LOCKBIT_CHAN_Pos \
	(0)
#define SPDRX_INTMASK_LOCKBIT_CHAN_Msk \
	((uint32_t)0x1U << SPDRX_INTMASK_LOCKBIT_CHAN_Pos)

#define SPDRX_INTMASK_LSBF_Pos \
	(1)
#define SPDRX_INTMASK_LSBF_Msk \
	((uint32_t)0x1U << SPDRX_INTMASK_LSBF_Pos)

#define SPDRX_INTMASK_HSBF_Pos \
	(2)
#define SPDRX_INTMASK_HSBF_Msk \
	((uint32_t)0x1U << SPDRX_INTMASK_HSBF_Pos)

#define SPDRX_INTMASK_PARITYERR_ACH_Pos \
	(3)
#define SPDRX_INTMASK_PARITYERR_ACH_Msk \
	((uint32_t)0x1U << SPDRX_INTMASK_PARITYERR_ACH_Pos)

#define SPDRX_INTMASK_PARITYERR_BCH_Pos \
	(4)
#define SPDRX_INTMASK_PARITYERR_BCH_Msk \
	((uint32_t)0x1U << SPDRX_INTMASK_PARITYERR_BCH_Pos)

#define SPDIF_RX_INTMASK_CAPTURE0_Pos \
	(16)
#define SPDIF_RX_INTMASK_CAPTURE0_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE0_Pos)

#define SPDIF_RX_INTMASK_CAPTURE1_Pos \
	(17)
#define SPDIF_RX_INTMASK_CAPTURE1_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE1_Pos)

#define SPDIF_RX_INTMASK_CAPTURE2_Pos \
	(18)
#define SPDIF_RX_INTMASK_CAPTURE2_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE2_Pos)

#define SPDIF_RX_INTMASK_CAPTURE3_Pos \
	(19)
#define SPDIF_RX_INTMASK_CAPTURE3_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE3_Pos)

#define SPDIF_RX_INTMASK_CAPTURE4_Pos \
	(20)
#define SPDIF_RX_INTMASK_CAPTURE4_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE4_Pos)

#define SPDIF_RX_INTMASK_CAPTURE5_Pos \
	(21)
#define SPDIF_RX_INTMASK_CAPTURE5_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE5_Pos)

#define SPDIF_RX_INTMASK_CAPTURE6_Pos \
	(22)
#define SPDIF_RX_INTMASK_CAPTURE6_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE6_Pos)

#define SPDIF_RX_INTMASK_CAPTURE7_Pos \
	(23)
#define SPDIF_RX_INTMASK_CAPTURE7_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE7_Pos)

#define SPDIF_RX_INTMASK_CAPTURE_DMA_Pos \
	(24)
#define SPDIF_RX_INTMASK_CAPTURE_DMA_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTMASK_CAPTURE_DMA_Pos)

#define SPDIF_RX_INTMASK_BURST_SELECT_Pos \
	(25)
#define SPDIF_RX_INTMASK_BURST_SELECT_Msk \
	((uint32_t)0x3U << SPDIF_RX_INTMASK_BURST_SELECT_Pos)

/****** SPDIF Rx INTSTAT, Offset:0x810 ******/
#define SPDRX_INTSTAT_LOCKBIT_CHAN_Pos \
	(0)
#define SPDRX_INTSTAT_LOCKBIT_CHAN_Msk \
	((uint32_t)0x1U << SPDRX_INTSTAT_LOCK_BIT_CHAN_Pos)

#define SPDRX_INTSTAT_LSBF_Pos \
	(1)
#define SPDRX_INTSTAT_LSBF_Msk \
	((uint32_t)0x1U << SPDRX_INTSTAT_LSBF_Pos)

#define SPDRX_INTSTAT_HSBF_Pos \
	(2)
#define SPDRX_INTSTAT_HSBF_Msk \
	((uint32_t)0x1U << SPDRX_INTSTAT_HSBF_Pos)

#define SPDRX_INTSTAT_PARITYERR_ACH_Pos \
	(3)
#define SPDRX_INTSTAT_PARITYERR_ACH_Msk \
	((uint32_t)0x1U << SPDRX_INTSTAT_PARITYERR_ACH_Pos)

#define SPDRX_INTSTAT_PARITYERR_BCH_Pos \
	(4)
#define SPDRX_INTSTAT_PARITYERR_BCH_Msk \
	((uint32_t)0x1U << SPDRX_INTSTAT_PARITYERR_BCH_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE0_Pos \
	(16)
#define SPDIF_RX_INTSTAT_CAPTURE0_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE0_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE1_Pos \
	(17)
#define SPDIF_RX_INTSTAT_CAPTURE1_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE1_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE2_Pos \
	(18)
#define SPDIF_RX_INTSTAT_CAPTURE2_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE2_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE3_Pos \
	(19)
#define SPDIF_RX_INTSTAT_CAPTURE3_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE3_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE4_Pos \
	(20)
#define SPDIF_RX_INTSTAT_CAPTURE4_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE4_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE5_Pos \
	(21)
#define SPDIF_RX_INTSTAT_CAPTURE5_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE5_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE6_Pos \
	(22)
#define SPDIF_RX_INTSTAT_CAPTURE6_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE6_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE7_Pos \
	(23)
#define SPDIF_RX_INTSTAT_CAPTURE7_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE7_Pos)

#define SPDIF_RX_INTSTAT_CAPTURE_DMA_Pos \
	(24)
#define SPDIF_RX_INTSTAT_CAPTURE_DMA_Msk \
	((uint32_t)0x1U << SPDIF_RX_INTSTAT_CAPTURE_DMA_Pos)

#define SPDIF_RX_INTSTAT_BURST_SELECT_Pos \
	(25)
#define SPDIF_RX_INTSTAT_BURST_SELECT_Msk \
	((uint32_t)0x3U << SPDIF_RX_INTSTAT_BURST_SELECT_Pos)

/****** SPDIF Rx CAP_CHCTRL, Offset:0x840~87C ******/
#define SPDIF_RX_CAP_CHCTRL_BITLEN_Pos \
	(0)
#define SPDIF_RX_CAP_CHCTRL_BITLEN_Msk \
	((uint32_t)0x1fU << SPDIF_RX_CAP_CHCTRL_BITLEN_Pos)

#define SPDIF_RX_CAP_CHCTRL_SOURCE_CH_Pos \
	(6)
#define SPDIF_RX_CAP_CHCTRL_SOURCE_CH_Msk \
	((uint32_t)0x1U << SPDIF_RX_CAP_CHCTRL_SOURCE_CH_Pos)
#define SPDIF_RX_CAP_CHCTRL_SOURCE_CH_A \
	((uint32_t)0x0U << SPDIF_RX_CAP_CHCTRL_SOURCE_CH_Pos)
#define SPDIF_RX_CAP_CHCTRL_SOURCE_CH_B \
	((uint32_t)0x1U << SPDIF_RX_CAP_CHCTRL_SOURCE_CH_Pos)

#define SPDIF_RX_CAP_CHCTRL_DATA_TYPE_Pos \
	(7)
#define SPDIF_RX_CAP_CHCTRL_DATA_TYPE_Msk \
	((uint32_t)0x1U << SPDIF_RX_CAP_CHCTRL_DATA_TYPE_Pos)
#define SPDIF_RX_CAP_CHCTRL_DATA_TYPE_USER \
	((uint32_t)0x0U << SPDIF_RX_CAP_CHCTRL_DATA_TYPE_Pos)
#define SPDIF_RX_CAP_CHCTRL_DATA_TYPE_CHSTAT \
	((uint32_t)0x1U << SPDIF_RX_CAP_CHCTRL_DATA_TYPE_Pos)

// Bit Position
#define SPDIFRX_CAP_CHCTRL_BIT_POSI_Pos \
	(8)
#define SPDIF_RX_CAP_CHCTRL_BIT_POSITION_Msk \
	((uint32_t)0xffU << SPDIFRX_CAP_CHCTRL_BIT_POSI_Pos)

/****** SPDIF Rx BUF, Offset:0xA00~A1C******/
#define SPDIF_RX_BUF_DATA_LOW_Pos \
	(0)
#define SPDIF_RX_BUF_DATA_LOW_Msk \
	((uint32_t)0xffffU << SPDIF_RX_BUF_DATA_LOW_Pos)

#define SPDIF_RX_BUF_DATA_HIGH_Pos \
	(16)
#define SPDIF_RX_BUF_DATA_HIGH_Msk \
	((uint32_t)0xffU << SPDIF_RX_BUF_DATA_HIGH_Pos)

#define SPDIF_RX_BUF_BLK_START_Pos \
	(27)
#define SPDIF_RX_BUF_BLK_START_Msk \
	((uint32_t)0x1U << SPDIF_RX_BUF_BLK_START_Pos)

#define SPDIF_RX_BUF_VALID_Pos \
	(28)
#define SPDIF_RX_BUF_VALID_Msk \
	((uint32_t)0x1U << SPDIF_RX_BUF_VALID_Pos)

#define SPDIF_RX_BUF_USER_DATA_Pos \
	(29)
#define SPDIF_RX_BUF_USER_DATA_Msk \
	((uint32_t)0x1U << SPDIF_RX_BUF_USER_DATA_Pos)

#define SPDIF_RX_BUF_CHSTAT_Pos \
	(30)
#define SPDIF_RX_BUF_CHSTAT_Msk \
	((uint32_t)0x1U << SPDIF_RX_BUF_CHSTAT_Pos)

#define SPDIF_RX_BUF_PARITY_Pos \
	(31)
#define SPDIF_RX_BUF_PARITY_Msk \
	((uint32_t)0x1U << SPDIF_RX_BUF_PARITY_Pos)

#define IOBUS_CFGDAI_CHMUX71CH_0SEL_Pos \
	(0)
#define IOBUS_CFGDAI_CHMUX71CH_0SEL_Msk \
	((uint32_t)0x1FU << IOBUS_CFGDAI_CHMUX71CH_0SEL_Pos)

#define IOBUS_CFGDAI_CHMUX71CH_1SEL_Pos \
	(8)
#define IOBUS_CFGDAI_CHMUX71CH_1SEL_Msk \
	((uint32_t)0x1FU << IOBUS_CFGDAI_CHMUX71CH_1SEL_Pos)

#define IOBUS_CFGDAI_CHMUX71CH_2SEL_Pos \
	(16)
#define IOBUS_CFGDAI_CHMUX71CH_2SEL_Msk \
	((uint32_t)0x1FU << IOBUS_CFGDAI_CHMUX71CH_2SEL_Pos)

#define IOBUS_CFGDAI_CHMUX71CH_3SEL_Pos \
	(24)
#define IOBUS_CFGDAI_CHMUX71CH_3SEL_Msk \
	((uint32_t)0x1FU << IOBUS_CFGDAI_CHMUX71CH_3SEL_Pos)

#define IOBUS_CFGDAI_CHMUXSRCH_0SEL_Pos \
	(0)
#define IOBUS_CFGDAI_CHMUXSRCH_0SEL_Msk \
	((uint32_t)0x3FU << IOBUS_CFGDAI_CHMUXSRCH_0SEL_Pos)

#define IOBUS_CFGDAI_CHMUXSRCH_1SEL_Pos \
	(8)
#define IOBUS_CFGDAI_CHMUXSRCH_1SEL_Msk \
	((uint32_t)0x3FU << IOBUS_CFGDAI_CHMUXSRCH_1SEL_Pos)

#define IOBUS_CFGDAI_CHMUXSRCH_2SEL_Pos \
	(16)
#define IOBUS_CFGDAI_CHMUXSRCH_2SEL_Msk \
	((uint32_t)0x3FU << IOBUS_CFGDAI_CHMUXSRCH_2SEL_Pos)

#define IOBUS_CFGDAI_CHMUXSRCH_3SEL_Pos \
	(24)
#define IOBUS_CFGDAI_CHMUXSRCH_3SEL_Msk \
	((uint32_t)0x3FU << IOBUS_CFGDAI_CHMUXSRCH_3SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUX71CH_0SEL_Pos \
	(0)
#define IOBUS_CFGSPDIF_CHMUX71CH_0SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUX71CH_0SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUX71CH_1SEL_Pos \
	(16)
#define IOBUS_CFGSPDIF_CHMUX71CH_1SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUX71CH_1SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUX71CH_2SEL_Pos \
	(0)
#define IOBUS_CFGSPDIF_CHMUX71CH_2SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUX71CH_2SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUXSRCH_0SEL_Pos \
	(0)
#define IOBUS_CFGSPDIF_CHMUXSRCH_0SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUXSRCH_0SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUXSRCH_1SEL_Pos \
	(16)
#define IOBUS_CFGSPDIF_CHMUXSRCH_1SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUXSRCH_1SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUXSRCH_2SEL_Pos \
	(0)
#define IOBUS_CFGSPDIF_CHMUXSRCH_2SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUXSRCH_2SEL_Pos)

#define IOBUS_CFGSPDIF_CHMUXSRCH_3SEL_Pos \
	(16)
#define IOBUS_CFGSPDIF_CHMUXSRCH_3SEL_Msk \
	((uint32_t)0x7FU << IOBUS_CFGSPDIF_CHMUXSRCH_3SEL_Pos)
#endif
