# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

snd-soc-tcc-asrc-objs := tcc_asrc.o tcc_pl080.o tcc_asrc_drv.o tcc_asrc_m2m.o tcc_asrc_dai.o tcc_asrc_pcm.o

obj-$(CONFIG_SND_SOC_TELECHIPS_ASRC)  += snd-soc-tcc-asrc.o
obj-$(CONFIG_SND_SOC_TELECHIPS_ASRC_CARD)  += tcc-asrc-card.o
