# SPDX-License-Identifier: GPL-2.0-only
#
# Telechips misc devices
#

obj-$(CONFIG_ICTC) += ictc.o
obj-$(CONFIG_TELECHIPS_SDR) += telechips_sdr/tcc_sdr.o
obj-$(CONFIG_OPENEDGES_NPU) += npu/

#
# Display part drivers
#
obj-$(CONFIG_TELECHIPS_WMIXER)	+= wmixer_drv.o
obj-$(CONFIG_TELECHIPS_SCALER)	+= scaler_drv.o
obj-$(CONFIG_TELECHIPS_G2D)		+= tcc_grp.o
obj-$(CONFIG_TELECHIPS_MISC)		+= tccmisc_drv.o
