/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC807X_ANDROID_IVI_DISPLAY_H
#define DT_BINDINGS_PMAP_TCC807X_ANDROID_IVI_DISPLAY_H

#undef SZ_1MB
#undef ARRAY_16MBYTE
#undef ARRAY_MBYTE
#undef ARRAY_256KBYTE
#undef TCC_ALIGN
#define SZ_1MB			(1024 * 1024)
#define ARRAY_16MBYTE(x)	((((x) + ((16 * SZ_1MB) - 1)) >> 24) << 24)
#define ARRAY_MBYTE(x)		((((x) + (SZ_1MB - 1)) >> 20) << 20)
#define ARRAY_256KBYTE(x)	((((x) + ((SZ_1MB / 4) - 1)) >> 18) << 18)
#define TCC_ALIGN(value, base)	(((value) + ((base) - 1))&~((base) - 1))

/*------------------------------------------------------------------------------
 * Define
 *------------------------------------------------------------------------------
 */
#define PRIMARY_FRAMEBUFFER_WIDTH       (1920)
#define PRIMARY_FRAMEBUFFER_HEIGHT      (720)
#define SECONDARY_FRAMEBUFFER_WIDTH     (1920)
#define SECONDARY_FRAMEBUFFER_HEIGHT    (720)
#define TERTIARY_FRAMEBUFFER_WIDTH      (0)
#define TERTIARY_FRAMEBUFFER_HEIGHT     (0)

// Choose bigger resolution between Primary and Secondary display device.
// and Should sync with hardware/telechips/common/hwcomposer/Hwrenderer.h
#define PRIMARY_TARGET_WIDTH            (1920)
#define PRIMARY_TARGET_HEIGHT           (720)
#define SECONDARY_TARGET_WIDTH          (0)
#define SECONDARY_TARGET_HEIGHT         (0)
#define TERTIARY_TARGET_WIDTH           (0)
#define TERTIARY_TARGET_HEIGHT          (0)

#if ((PRIMARY_TARGET_WIDTH * PRIMARY_TARGET_HEIGHT) > (SECONDARY_TARGET_WIDTH * SECONDARY_TARGET_HEIGHT))
#define SUPPORT_DISPLAY_MAX_WIDTH       (PRIMARY_TARGET_WIDTH)
#define SUPPORT_DISPLAY_MAX_HEIGHT      (PRIMARY_TARGET_HEIGHT)
#else
#define SUPPORT_DISPLAY_MAX_WIDTH       (SECONDARY_TARGET_WIDTH)
#define SUPPORT_DISPLAY_MAX_HEIGHT      (SECONDARY_TARGET_HEIGHT)
#endif

#define SUPPORT_VIQE_MAX_WIDTH          (1920)
#define SUPPORT_VIQE_MAX_HEIGHT         (1088)

/* Should sync SUPPORT_VIDEO_MAX_WIDTH/HEIGHT */
#define SUPPORT_VIDEO_4K_WIDTH		(4096)
#define SUPPORT_VIDEO_4K_HEIGHT		(2176)

/*------------------------------------------------------------------------------
 * Size
 *------------------------------------------------------------------------------
 */
#ifdef CONFIG_VIOC_AFBCDEC
#define PMAP_SIZE_FB_VIDEO	\
	(ARRAY_MBYTE((TCC_ALIGN(PRIMARY_FRAMEBUFFER_WIDTH, 16) * TCC_ALIGN(PRIMARY_FRAMEBUFFER_HEIGHT, 16) * 4 \
	+ TCC_ALIGN(PRIMARY_FRAMEBUFFER_WIDTH, 16) * TCC_ALIGN(PRIMARY_FRAMEBUFFER_HEIGHT, 16) / 16 ) * 3) \
	+ (ARRAY_MBYTE(SECONDARY_FRAMEBUFFER_WIDTH * SECONDARY_FRAMEBUFFER_HEIGHT * 4 * 3)) + (1*SZ_1MB))
#else
#define PMAP_SIZE_FB_VIDEO	\
	(ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * PRIMARY_FRAMEBUFFER_HEIGHT * 4 * 3) \
	+ (ARRAY_MBYTE(SECONDARY_FRAMEBUFFER_WIDTH * SECONDARY_FRAMEBUFFER_HEIGHT * 4 * 3)))
#endif

#define PMAP_SIZE_FB1_VIDEO	(0x00000000)
#define PMAP_SIZE_FB2_VIDEO	(0x00000000)
#define PMAP_SIZE_FB3_VIDEO	(0x00000000)

#define PMAP_SIZE_OVERLAY	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)
#define PMAP_SIZE_OVERLAY1	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)
#define PMAP_SIZE_OVERLAY_ROT	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 2)
#define PMAP_SIZE_VIQE0		ARRAY_MBYTE((SUPPORT_VIQE_MAX_WIDTH * (SUPPORT_VIQE_MAX_HEIGHT / 2 ) * 4 * 4 * 3) / 2)
#define PMAP_SIZE_VIQE1		ARRAY_MBYTE((SUPPORT_VIQE_MAX_WIDTH * (SUPPORT_VIQE_MAX_HEIGHT / 2 ) * 4 * 4 * 3) / 2)
#define PMAP_SIZE_OSD		(0x00000000)
#define PMAP_SIZE_VIDEO_DUAL	(0x00000000)
#define PMAP_SIZE_DUAL_DISPLAY	(0x00000000)

#ifdef CONFIG_USE_FORCE_8BIT_OUT_LASTFRAME
	#define BPP_FACTOR 1
#else
	#define BPP_FACTOR 2 //10bit
#endif

#define SWAP_BUFFER_FB_WMIXER	ARRAY_MBYTE((((SUPPORT_VIDEO_4K_WIDTH * 25 / 10) * SUPPORT_VIDEO_4K_HEIGHT * 15 / 10) + 0x80000) * 2)
#define LAST_BUFFER_FB_WMIXER	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * BPP_FACTOR)
#define EXT_BUFFER_FB_WMIXER	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * BPP_FACTOR * 2)

#ifdef CONFIG_PLATFORM_AVN
	#ifdef CONFIG_ANDROID
	#define SIZE_FB_WMIXER	(EXT_BUFFER_FB_WMIXER)
	#else
	#define SIZE_FB_WMIXER	0x01000000
	#endif
#else
	#if (SWAP_BUFFER_FB_WMIXER > LAST_BUFFER_FB_WMIXER)
	#define SIZE_FB_WMIXER	(SWAP_BUFFER_FB_WMIXER)
	#else
	#define SIZE_FB_WMIXER	(LAST_BUFFER_FB_WMIXER)
	#endif
#endif

#define PMAP_SIZE_FB_WMIXER	(SIZE_FB_WMIXER)

#endif	//DT_BINDINGS_PMAP_TCC807X_ANDROID_IVI_DISPLAY_H
