/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC807X_LINUX_SUBCORE_DISPLAY_H
#define DT_BINDINGS_PMAP_TCC807X_LINUX_SUBCORE_DISPLAY_H

#undef SZ_1MB
#undef ARRAY_16MBYTE
#undef ARRAY_MBYTE
#undef ARRAY_256KBYTE
#define SZ_1MB			(1024 * 1024)
#define ARRAY_16MBYTE(x)	((((x) + ((16 * SZ_1MB) - 1)) >> 24) << 24)
#define ARRAY_MBYTE(x)		((((x) + (SZ_1MB - 1)) >> 20) << 20)
#define ARRAY_256KBYTE(x)	((((x) + ((SZ_1MB / 4) - 1)) >> 18) << 18)

/*------------------------------------------------------------------------------
 * Define
 *------------------------------------------------------------------------------
 */
#define PRIMARY_FRAMEBUFFER_WIDTH	(1920)
#define PRIMARY_FRAMEBUFFER_HEIGHT	(720)
#define SECONDARY_FRAMEBUFFER_WIDTH	(0)
#define SECONDARY_FRAMEBUFFER_HEIGHT	(0)
#define TERTIARY_FRAMEBUFFER_WIDTH	(0)
#define TERTIARY_FRAMEBUFFER_HEIGHT	(0)
#define QUATERNARY_FRAMEBUFFER_WIDTH	(0)
#define QUATERNARY_FRAMEBUFFER_HEIGHT	(0)

#define FRAMES_OVERLAY_ROT		(0)

/*------------------------------------------------------------------------------
 * Size
 *------------------------------------------------------------------------------
 */
#define PMAP_SIZE_FB_VIDEO	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * PRIMARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB1_VIDEO	ARRAY_MBYTE(SECONDARY_FRAMEBUFFER_WIDTH * SECONDARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB2_VIDEO	ARRAY_MBYTE(TERTIARY_FRAMEBUFFER_WIDTH * TERTIARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB3_VIDEO	ARRAY_MBYTE(QUATERNARY_FRAMEBUFFER_WIDTH * QUATERNARY_FRAMEBUFFER_HEIGHT * 4 * 3)

#define PMAP_SIZE_OVERLAY_ROT	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * PRIMARY_FRAMEBUFFER_HEIGHT * 4 * FRAMES_OVERLAY_ROT)
#define PMAP_SIZE_V4L2_VOUT0	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * PRIMARY_FRAMEBUFFER_HEIGHT * 3 * 2)
#define PMAP_SIZE_VIQE0		ARRAY_MBYTE((PRIMARY_FRAMEBUFFER_WIDTH * (PRIMARY_FRAMEBUFFER_HEIGHT / 2 ) * 4 * 4 * 3) / 2)
#define RESERVED_SUBCORE_MEM_BASE       (0x4A800000)
#define RESERVED_SUBCORE_MEM_SIZE       (0x15800000)

#define FB_VIDEO_BASE                   (RESERVED_SUBCORE_MEM_BASE)
#endif	//DT_BINDINGS_PMAP_TCC807X_LINUX_IVI_SUBCORE_DISPLAY_H
