/* SPDX-License-Identifier: (GPL-2.0-or-later OR MIT) */
/*
 * Copyright (C) 2023 Telechips Inc.
 */
#ifndef DT_BINDINGS_PMAP_TCC807X_LINUX_IVI_DISPLAY_H
#define DT_BINDINGS_PMAP_TCC807X_LINUX_IVI_DISPLAY_H

#undef SZ_1MB
#undef ARRAY_16MBYTE
#undef ARRAY_MBYTE
#undef ARRAY_256KBYTE
#define SZ_1MB			(1024 * 1024)
#define ARRAY_16MBYTE(x)	((((x) + ((16 * SZ_1MB) - 1)) >> 24) << 24)
#define ARRAY_MBYTE(x)		((((x) + (SZ_1MB - 1)) >> 20) << 20)
#define ARRAY_256KBYTE(x)	((((x) + ((SZ_1MB / 4) - 1)) >> 18) << 18)

/*------------------------------------------------------------------------------
 * Define
 *------------------------------------------------------------------------------
 */
#define PRIMARY_FRAMEBUFFER_WIDTH	(1920)
#define PRIMARY_FRAMEBUFFER_HEIGHT	(720)
#define SECONDARY_FRAMEBUFFER_WIDTH	(0)
#define SECONDARY_FRAMEBUFFER_HEIGHT	(0)
#define TERTIARY_FRAMEBUFFER_WIDTH	(0)
#define TERTIARY_FRAMEBUFFER_HEIGHT	(0)
#define QUATERNARY_FRAMEBUFFER_WIDTH	(0)
#define QUATERNARY_FRAMEBUFFER_HEIGHT	(0)

#define SUPPORT_DISPLAY_MAX_WIDTH	(PRIMARY_FRAMEBUFFER_WIDTH)
#define SUPPORT_DISPLAY_MAX_HEIGHT	(PRIMARY_FRAMEBUFFER_HEIGHT)

#define SUPPORT_VIQE_MAX_WIDTH		(1920)
#define SUPPORT_VIQE_MAX_HEIGHT		(1088)

/* Should sync SUPPORT_VIDEO_MAX_WIDTH/HEIGHT */
#define SUPPORT_VIDEO_4K_WIDTH		(4096)
#define SUPPORT_VIDEO_4K_HEIGHT		(2176)

#define FRAMES_OVERLAY_ROT		(1)

/*------------------------------------------------------------------------------
 * Size
 *------------------------------------------------------------------------------
 */
#define PMAP_SIZE_FB_VIDEO	ARRAY_MBYTE(PRIMARY_FRAMEBUFFER_WIDTH * PRIMARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB1_VIDEO	ARRAY_MBYTE(SECONDARY_FRAMEBUFFER_WIDTH * SECONDARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB2_VIDEO	ARRAY_MBYTE(TERTIARY_FRAMEBUFFER_WIDTH * TERTIARY_FRAMEBUFFER_HEIGHT * 4 * 3)
#define PMAP_SIZE_FB3_VIDEO	ARRAY_MBYTE(QUATERNARY_FRAMEBUFFER_WIDTH * QUATERNARY_FRAMEBUFFER_HEIGHT * 4 * 3)

#define PMAP_SIZE_OSD		ARRAY_MBYTE(0)	// 0x01d00000 = 2560 * 1440 * 4 * 2

#define PMAP_SIZE_OVERLAY	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)
#define PMAP_SIZE_OVERLAY1	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)
#define PMAP_SIZE_OVERLAY_ROT	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 10 * FRAMES_OVERLAY_ROT)

#define PMAP_SIZE_V4L2_VOUT0	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)
#define PMAP_SIZE_V4L2_VOUT1	ARRAY_MBYTE(SUPPORT_DISPLAY_MAX_WIDTH * SUPPORT_DISPLAY_MAX_HEIGHT * 2 * 3)

#define PMAP_SIZE_VIQE0		ARRAY_MBYTE((SUPPORT_VIQE_MAX_WIDTH * (SUPPORT_VIQE_MAX_HEIGHT / 2) * 4 * 4 * 3) / 2)
#define PMAP_SIZE_VIQE1		ARRAY_MBYTE((SUPPORT_VIQE_MAX_WIDTH * (SUPPORT_VIQE_MAX_HEIGHT / 2) * 4 * 4 * 3) / 2)

#define PMAP_SIZE_FB_WMIXER	ARRAY_MBYTE((((SUPPORT_VIDEO_4K_WIDTH * 25 / 10) * SUPPORT_VIDEO_4K_HEIGHT * 15 / 10) + 0x80000) * 2)

#endif	//DT_BINDINGS_PMAP_TCC807X_LINUX_IVI_DISPLAY_H
