#ifndef TCC_VPU_SUPPORTED_MEDIA_FORMAT_IF_H
#define TCC_VPU_SUPPORTED_MEDIA_FORMAT_IF_H

#define TCC_VPU_DEC_H264_MIN_W		(64U)
#define TCC_VPU_DEC_H264_MIN_H		(64U)
#define TCC_VPU_DEC_H264_MAX_W		(1920U)
#define TCC_VPU_DEC_H264_MAX_H		(1088U)
#define TCC_VPU_DEC_H264_STEPSIZE_W (1U)
#define TCC_VPU_DEC_H264_STEPSIZE_H (1U)

#define TCC_VPU_DEC_VP8_MIN_W		(64U)
#define TCC_VPU_DEC_VP8_MIN_H		(64U)
#define TCC_VPU_DEC_VP8_MAX_W		(1920U)
#define TCC_VPU_DEC_VP8_MAX_H		(1088U)
#define TCC_VPU_DEC_VP8_STEPSIZE_W 	(16U)
#define TCC_VPU_DEC_VP8_STEPSIZE_H 	(16U)

#define TCC_VPU_DEC_VP9_MIN_W		(64U)
#define TCC_VPU_DEC_VP9_MIN_H		(64U)
#define TCC_VPU_DEC_VP9_MAX_W		(4096U)
#define TCC_VPU_DEC_VP9_MAX_H		(2160U)
#define TCC_VPU_DEC_VP9_STEPSIZE_W 	(16U)
#define TCC_VPU_DEC_VP9_STEPSIZE_H 	(16U)

#define TCC_VPU_DEC_HEVC_MIN_W		(64U)
#define TCC_VPU_DEC_HEVC_MIN_H		(64U)
#define TCC_VPU_DEC_HEVC_MAX_W		(4096U)
#define TCC_VPU_DEC_HEVC_MAX_H		(2160U)
#define TCC_VPU_DEC_HEVC_STEPSIZE_W (1U)
#define TCC_VPU_DEC_HEVC_STEPSIZE_H (1U)

#endif