# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

ifneq ($(CONFIG_OF_ALL_DTBS)$(CONFIG_ARCH_TELECHIPS),)
subdir-y += tcc750x
subdir-y += tcc803x
subdir-y += tcc805x
subdir-y += tcc807x
endif
