obj-$(CONFIG_TELECHIPS_TOUCH_BRIDGE) += touch_bridge.o
touch_bridge-objs = tcc_touch_bridge.o tcc_touch_cmd.o
 
obj-$(CONFIG_TELECHIPS_TOUCH_RECEIVE) += touch_receive.o
touch_receive-objs = tcc_touch_receive.o tcc_touch_cmd.o
