# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.
#

#
# module name is tcc_viqe_interface.ko
#
obj-$(CONFIG_VIOC_VIQE) += tcc_viqe_interface.o
tcc_viqe_interface-$(CONFIG_VIOC_VIQE) += viqe.o tcc_vioc_viqe_interface.o

#
# module name is tcc_vioc_viqe.ko
#
obj-$(CONFIG_TELECHIPS_VIQE) += tcc_vioc_viqe.o

#
# module name is tcc_vsync.ko
#
obj-$(CONFIG_VIDEO_DISPLAY_BY_VSYNC_INT) += tcc_vsync.o
