# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

obj-$(CONFIG_TELECHIPS_BOOTSTAGE)	+= bootstage.o
obj-$(CONFIG_TELECHIPS_CHIPINFO)	+= chipinfo.o
obj-$(CONFIG_TELECHIPS_PIC)		+= irq-pic.o
obj-$(CONFIG_TELECHIPS_TIMER)		+= timer.o
obj-$(CONFIG_PROC_RESERVED_MEM)		+= reserved_mem.o
