# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Telechips Inc.
#

# Video Decoder
obj-$(CONFIG_VIDEO_TCC_ADV7182)		+= tcc-adv7182.o
obj-$(CONFIG_VIDEO_TCC_ISL79988) 	+= tcc-isl79988.o

# Camera image sensor
obj-$(CONFIG_VIDEO_TCC_IMX424)		+= tcc-imx424.o
obj-$(CONFIG_VIDEO_TCC_ARXXXX)		+= tcc-arxxxx.o
obj-$(CONFIG_VIDEO_TCC_AR0820)		+= tcc-ar0820.o
obj-$(CONFIG_VIDEO_TCC_AR0147)		+= tcc-ar0147.o
obj-$(CONFIG_VIDEO_TCC_AR0231)		+= tcc-ar0231.o
obj-$(CONFIG_VIDEO_TCC_AR0144)		+= tcc-ar0144.o
obj-$(CONFIG_VIDEO_TCC_AR0239)		+= tcc-ar0239.o
obj-$(CONFIG_VIDEO_TCC_IMX219)		+= imx219.o
# External ISP(in camera module)
obj-$(CONFIG_VIDEO_TCC_CXD5700)		+= tcc-cxd5700.o
# deserializer
obj-$(CONFIG_VIDEO_TCC_MAX9275)		+= tcc-max9275.o
obj-$(CONFIG_VIDEO_TCC_MAX9286)		+= tcc-max9286.o
# serializer
obj-$(CONFIG_VIDEO_TCC_MAX96717)	+= tcc-max96717.o
obj-$(CONFIG_VIDEO_TCC_MAX9295)		+= tcc-max9295.o
obj-$(CONFIG_VIDEO_TCC_MAX96701)	+= tcc-max96701.o
obj-$(CONFIG_VIDEO_TCC_MAX96705)	+= tcc-max96705.o
obj-$(CONFIG_VIDEO_TCC_MAX96712)	+= tcc-max96712.o
