/* 
* SPDX-License-Identifier: BSD-3-Clause OR GPL-2.0
* Copyright 2025 Telechips Inc. 
* Contact: jayhouse@telechips.com
*/

#ifndef TCC_VPU_V3_IOCTL_H
#define TCC_VPU_V3_IOCTL_H

#include <linux/ioctl.h>

#define VPU_V3_IOWR(base, num) 	((base) + (num))

#define VPU_V3_IO_COM	100
#define VPU_V3_IO_DEC	200
#define VPU_V3_IO_ENC	300

#define KERNEL_OFFSET  0x10000

//vpu v3 common i/o
#define VPU_V3_COM_BASE 					VPU_V3_IOWR(VPU_V3_IO_COM, 0)
#define VPU_V3_GET_DRV_VERSION_SYNC 		VPU_V3_IOWR(VPU_V3_IO_COM, 1)
#define VPU_V3_GET_CAPABILITY_SYNC 			VPU_V3_IOWR(VPU_V3_IO_COM, 2)

//vpu v3 decoder i/o
#define VDEC_V3_BASE						VPU_V3_IOWR(VPU_V3_IO_DEC, 0)
#define VDEC_V3_INIT 						VPU_V3_IOWR(VPU_V3_IO_DEC, 1)
#define VDEC_V3_INIT_RESULT 				VPU_V3_IOWR(VPU_V3_IO_DEC, 2)
#define VDEC_V3_SEQ_HEADER 					VPU_V3_IOWR(VPU_V3_IO_DEC, 3)
#define VDEC_V3_SEQ_HEADER_RESULT 			VPU_V3_IOWR(VPU_V3_IO_DEC, 4)
#define VDEC_V3_DECODE 						VPU_V3_IOWR(VPU_V3_IO_DEC, 5)
#define VDEC_V3_DECODE_RESULT 				VPU_V3_IOWR(VPU_V3_IO_DEC, 6)
#define VDEC_V3_BUF_CLEAR					VPU_V3_IOWR(VPU_V3_IO_DEC, 7)
#define VDEC_V3_BUF_CLEAR_RESULT 			VPU_V3_IOWR(VPU_V3_IO_DEC, 8)
#define VDEC_V3_DRAIN 						VPU_V3_IOWR(VPU_V3_IO_DEC, 9)
#define VDEC_V3_DRAIN_RESULT 				VPU_V3_IOWR(VPU_V3_IO_DEC, 10)
#define VDEC_V3_FLUSH 						VPU_V3_IOWR(VPU_V3_IO_DEC, 11)
#define VDEC_V3_FLUSH_RESULT 				VPU_V3_IOWR(VPU_V3_IO_DEC, 12)
#define VDEC_V3_CLOSE 						VPU_V3_IOWR(VPU_V3_IO_DEC, 13)
#define VDEC_V3_CLOSE_RESULT 				VPU_V3_IOWR(VPU_V3_IO_DEC, 14)
#define VDEC_V3_REG_FRAMEBUFFER 			VPU_V3_IOWR(VPU_V3_IO_DEC, 15)
#define VDEC_V3_REG_FRAMEBUFFER_RESULT		VPU_V3_IOWR(VPU_V3_IO_DEC, 16)
#define VDEC_V3_GET_NEXT_RESULT_SYNC		VPU_V3_IOWR(VPU_V3_IO_DEC, 17)
#define VDEC_V3_ALLOC_MEMORY_SYNC 			VPU_V3_IOWR(VPU_V3_IO_DEC, 18)

//vpu v3 encoder i/o
#define VENC_V3_BASE	 					VPU_V3_IOWR(VPU_V3_IO_ENC, 0)
#define VENC_V3_INIT	 					VPU_V3_IOWR(VPU_V3_IO_ENC, 1)
#define VENC_V3_INIT_RESULT 				VPU_V3_IOWR(VPU_V3_IO_ENC, 2)
#define VENC_V3_PUT_HEADER 					VPU_V3_IOWR(VPU_V3_IO_ENC, 3)
#define VENC_V3_PUT_HEADER_RESULT 			VPU_V3_IOWR(VPU_V3_IO_ENC, 4)
#define VENC_V3_ENCODE 						VPU_V3_IOWR(VPU_V3_IO_ENC, 5)
#define VENC_V3_ENCODE_RESULT 				VPU_V3_IOWR(VPU_V3_IO_ENC, 6)
#define VENC_V3_CLOSE 						VPU_V3_IOWR(VPU_V3_IO_ENC, 7)
#define VENC_V3_CLOSE_RESULT 				VPU_V3_IOWR(VPU_V3_IO_ENC, 8)
#define VENC_V3_ALLOC_MEMORY_SYNC 			VPU_V3_IOWR(VPU_V3_IO_ENC, 9)


//Definition of ioctl for calling from kernel space
#define VPU_V3_COM_BASE_KERNEL                      (VPU_V3_IOWR(VPU_V3_COM_BASE + KERNEL_OFFSET, 0))
#define VPU_V3_GET_DRV_VERSION_SYNC_KERNEL         (VPU_V3_COM_BASE_KERNEL + 1)
#define VPU_V3_GET_CAPABILITY_SYNC_KERNEL          (VPU_V3_COM_BASE_KERNEL + 2)

#define VDEC_V3_BASE_KERNEL                        (VPU_V3_IOWR(VPU_V3_IO_DEC + KERNEL_OFFSET, 0))
#define VDEC_V3_INIT_KERNEL                        (VDEC_V3_BASE_KERNEL + 1)
#define VDEC_V3_INIT_RESULT_KERNEL                 (VDEC_V3_BASE_KERNEL + 2)
#define VDEC_V3_SEQ_HEADER_KERNEL                  (VDEC_V3_BASE_KERNEL + 3)
#define VDEC_V3_SEQ_HEADER_RESULT_KERNEL           (VDEC_V3_BASE_KERNEL + 4)
#define VDEC_V3_DECODE_KERNEL                      (VDEC_V3_BASE_KERNEL + 5)
#define VDEC_V3_DECODE_RESULT_KERNEL               (VDEC_V3_BASE_KERNEL + 6)
#define VDEC_V3_BUF_CLEAR_KERNEL                   (VDEC_V3_BASE_KERNEL + 7)
#define VDEC_V3_BUF_CLEAR_RESULT_KERNEL            (VDEC_V3_BASE_KERNEL + 8)
#define VDEC_V3_DRAIN_KERNEL                       (VDEC_V3_BASE_KERNEL + 9)
#define VDEC_V3_DRAIN_RESULT_KERNEL                (VDEC_V3_BASE_KERNEL + 10)
#define VDEC_V3_FLUSH_KERNEL                       (VDEC_V3_BASE_KERNEL + 11)
#define VDEC_V3_FLUSH_RESULT_KERNEL                (VDEC_V3_BASE_KERNEL + 12)
#define VDEC_V3_CLOSE_KERNEL                       (VDEC_V3_BASE_KERNEL + 13)
#define VDEC_V3_CLOSE_RESULT_KERNEL                (VDEC_V3_BASE_KERNEL + 14)
#define VDEC_V3_REG_FRAMEBUFFER_KERNEL             (VDEC_V3_BASE_KERNEL + 15)
#define VDEC_V3_REG_FRAMEBUFFER_RESULT_KERNEL      (VDEC_V3_BASE_KERNEL + 16)
#define VDEC_V3_GET_NEXT_RESULT_SYNC_KERNEL        (VDEC_V3_BASE_KERNEL + 17)
#define VDEC_V3_ALLOC_MEMORY_SYNC_KERNEL           (VDEC_V3_BASE_KERNEL + 18)

#define VENC_V3_BASE_KERNEL                        (VPU_V3_IOWR(VPU_V3_IO_ENC + KERNEL_OFFSET, 0))
#define VENC_V3_INIT_KERNEL                        (VENC_V3_BASE_KERNEL + 1)
#define VENC_V3_INIT_RESULT_KERNEL                 (VENC_V3_BASE_KERNEL + 2)
#define VENC_V3_PUT_HEADER_KERNEL                  (VENC_V3_BASE_KERNEL + 3)
#define VENC_V3_PUT_HEADER_RESULT_KERNEL           (VENC_V3_BASE_KERNEL + 4)
#define VENC_V3_ENCODE_KERNEL                      (VENC_V3_BASE_KERNEL + 5)
#define VENC_V3_ENCODE_RESULT_KERNEL               (VENC_V3_BASE_KERNEL + 6)
#define VENC_V3_CLOSE_KERNEL                       (VENC_V3_BASE_KERNEL + 7)
#define VENC_V3_CLOSE_RESULT_KERNEL                (VENC_V3_BASE_KERNEL + 8)
#define VENC_V3_ALLOC_MEMORY_SYNC_KERNEL           (VENC_V3_BASE_KERNEL + 9)

#endif //TCC_VPU_V3_IOCTL_H

