# SPDX-License-Identifier: GPL-2.0 OR MIT
#
# (C) COPYRIGHT 2021-2023 Arm Limited or its affiliates. All rights reserved.
#
#

src:=$(if $(patsubst /%,,$(src)),$(srctree)/$(src),$(src))
ccflags-y += \
	-I$(src)/../../../midgard/arbiter

obj-$(CONFIG_MALI_ARBITER_MODULES) := mali_emu_kbase.o
