
obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_hevc_dec_dev.o
vpu_hevc_dec_dev-y += vpu_hevc_dec_mgr_devices.o
vpu_hevc_dec_dev-y += vpu_hevc_dec_mgr.o
vpu_hevc_dec_dev-y += vpu_hevc_dec_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += jpu_dev.o
jpu_dev-y += jpu_devices.o
jpu_dev-y += jpu_mgr.o
jpu_dev-y += jpu_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_4k_d2_dev.o
vpu_4k_d2_dev-y += vpu_4k_d2_devices.o
vpu_4k_d2_dev-y += vpu_4k_d2_mgr.o
vpu_4k_d2_dev-y += vpu_4k_d2_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_hevc_enc_dev.o
vpu_hevc_enc_dev-y += vpu_hevc_enc_devices.o
vpu_hevc_enc_dev-y += vpu_hevc_enc_mgr.o
vpu_hevc_enc_dev-y += vpu_hevc_enc_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_hevc_enc2_dev.o
vpu_hevc_enc2_dev-y += vpu_hevc_enc2_devices.o
vpu_hevc_enc2_dev-y += vpu_hevc_enc2_mgr.o
vpu_hevc_enc2_dev-y += vpu_hevc_enc2_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_c7_dev.o
vpu_c7_dev-y += vpu_c7_devices.o
vpu_c7_dev-y += vpu_c7_mgr.o
vpu_c7_dev-y += vpu_c7_mgr_sys.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu.o
vpu-y += vpu_mgr.o vpu_mgr_common.o vpu_mgr_decode.o vpu_mgr_encode.o vpu_mgr_context.o vpu_mem.o vpu_etc.o vpu_dbg.o vpu_rm.o vpu_sys_common.o
vpu-y += vpu_list_manager.o vpu_dllist.o vpu_memtrace.o vpu_dbg_string.o
vpu-y += vpu_devices.o
vpu-y += vpu_dbg_info.o

obj-$(CONFIG_TELECHIPS_VPU_V3_DRV) += vpu_drv_dev.o
vpu_drv_dev-y += vpu_drv_devices.o
vpu_drv_dev-y += vpu_dec.o
vpu_drv_dev-y += vpu_enc.o

