# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2023 Telechips Inc.

obj-$(CONFIG_TELECHIPS_DPTX_AUDIO)         += dptx_audio/
obj-$(CONFIG_SND_SOC_TELECHIPS) += tcc_adma_pcm.o tcc_i2s.o tcc_spdif.o
obj-$(CONFIG_SND_SOC_TELECHIPS_AUDIO_CHMUX) += tcc_audio_chmux.o

obj-y		+= asrc/

obj-$(CONFIG_SND_SOC_TELECHIPS_CARD) += tcc-snd-card.o
